//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESS_ROUTINES
    {
        public string NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> NUM_ARGS { get; set; }
        public string TYPE { get; set; }
        public string ARGUMENT1 { get; set; }
        public string ARGUMENT2 { get; set; }
        public string ARGUMENT3 { get; set; }
        public string ARGUMENT4 { get; set; }
        public string ARGUMENT5 { get; set; }
        public string ARGUMENT6 { get; set; }
        public string ARGUMENT7 { get; set; }
        public string ARGUMENT8 { get; set; }
        public string ARGUMENT9 { get; set; }
        public string ARGUMENT10 { get; set; }
        public string ARGUMENT11 { get; set; }
        public string ARGUMENT12 { get; set; }
        public string ARGUMENT13 { get; set; }
        public string ARGUMENT14 { get; set; }
        public string ARGUMENT15 { get; set; }
        public string ARGUMENT16 { get; set; }
        public string ARGUMENT17 { get; set; }
        public string ARGUMENT18 { get; set; }
        public string ARGUMENT19 { get; set; }
        public string ARGUMENT20 { get; set; }
        public string ROUTINE { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
    }
}
