//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_HOC_COMPONENT
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string RESULT_NAME { get; set; }
        public string RESULT_TYPE { get; set; }
        public string UNITS { get; set; }
        public Nullable<short> PLACES { get; set; }
        public string LIST_KEY { get; set; }
        public string ROUND { get; set; }
        public string REPORTABLE { get; set; }
        public string FACTOR_VALUE { get; set; }
        public string FACTOR_OPERATOR { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
        public string FORMAT_CALCULATION { get; set; }
    }
}
