//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERT
    {
        public int ALERT_NUMBER { get; set; }
        public Nullable<int> CONTACT_NUMBER { get; set; }
        public string USER_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string ACKNOWLEDGED { get; set; }
        public Nullable<System.DateTime> ACKNOWLEDGED_DATE { get; set; }
        public string RESPONSE_REQD { get; set; }
        public string RESPONSE { get; set; }
        public string READ_RECEIPT_REQD { get; set; }
        public string READ_RECEIPT_SENT { get; set; }
        public string ACK_RECEIPT_REQD { get; set; }
        public string ACK_RECEIPT_SENT { get; set; }
        public string READ { get; set; }
        public string SEND_EMAIL { get; set; }
    }
}
