//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYSIS
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string X_WORK { get; set; }
        public string ACTIVE { get; set; }
        public string REPORTED_NAME { get; set; }
        public string COMMON_NAME { get; set; }
        public string ANALYSIS_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string NORM_DOC { get; set; }
        public string X_NTD { get; set; }
        public string LAB { get; set; }
        public string INST_GROUP { get; set; }
        public string INSTRUMENT { get; set; }
        public string TEST_LOCATION { get; set; }
        public Nullable<int> EXPECTED_DATE { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<float> COST_UNITS { get; set; }
        public Nullable<float> REQD_VOLUME { get; set; }
        public string DESTRUCTIVE { get; set; }
        public string PARAMETER_NAME { get; set; }
        public string PARAMETER_TAG { get; set; }
        public string DISPLAY_MESSAGE { get; set; }
        public string KEY_CONTACT { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
        public string TEST_TEMPLATE { get; set; }
        public string ALIAS_NAME { get; set; }
        public string BATCH_LINK { get; set; }
        public string AUTO_AUTHORIZE { get; set; }
        public string AUTO_REJECT { get; set; }
        public string CALC_ON_SAVE { get; set; }
        public string STORE_INCMP_OPTS { get; set; }
        public string ATTRIBUTE_1 { get; set; }
        public string ATTRIBUTE_2 { get; set; }
        public string ATTRIBUTE_3 { get; set; }
        public string ATTRIBUTE_4 { get; set; }
        public string ATTRIBUTE_5 { get; set; }
        public string ALIQUOT_GROUP { get; set; }
        public string SPLIT_REPLICATES { get; set; }
        public string CROSS_SAMPLE { get; set; }
        public string SAMPLE_TYPE { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public string STORAGE_CONDITION { get; set; }
        public string APPROVAL_ROLE { get; set; }
        public string QUICK_CODE { get; set; }
        public string VOLUME_UNITS { get; set; }
        public string HIDE_ON_ORDER_FORM { get; set; }
        public Nullable<int> TEST_SEQUENCE_NO { get; set; }
        public string DOUBLE_ENTRY { get; set; }
        public string X_VKK_FLAG { get; set; }
        public string TRANSFER_USES_INST { get; set; }
        public string T_TEST_METHOD_INV { get; set; }
        public string X_NEED_INSTRUMENT { get; set; }
    }
}
