//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYSIS_VARIATION
    {
        public string ANALYSIS { get; set; }
        public string VARIATION { get; set; }
        public int VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string BLANKS_OVERRIDE { get; set; }
    }
}
