//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYSIS_RULES
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string ANALYSIS { get; set; }
        public string LINK_FIELD { get; set; }
        public string LINK_KEY { get; set; }
        public string ANALYSIS_RULE { get; set; }
        public string AUTO_ASSIGN { get; set; }
        public string ASSIGN_IF_PRESENT { get; set; }
        public Nullable<int> REPLICATE_COUNT { get; set; }
        public string USER_WRITTEN { get; set; }
        public string SOURCE_CODE { get; set; }
        public string CHILD_TEST { get; set; }
    }
}
