//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROVAL
    {
        public int APPROVAL_ID { get; set; }
        public string APPROVAL_ROUTING { get; set; }
        public string APPROVAL_GROUP { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVAL_START { get; set; }
        public Nullable<System.DateTime> APPROVAL_COMPLETE { get; set; }
        public string TABLE_NAME { get; set; }
        public string RECORD_KEY { get; set; }
        public Nullable<int> RECORD_VERSION { get; set; }
        public string REPORT_FORMAT { get; set; }
        public string APPROVAL_REPORT { get; set; }
        public string CANCELED_REASON { get; set; }
        public string CANCELED_BY { get; set; }
        public Nullable<System.DateTime> CANCELED_ON { get; set; }
    }
}
