//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROVAL_GROUPS
    {
        public string APPROVAL_ROUTING { get; set; }
        public string APPROVAL_GROUP { get; set; }
        public string REPORT_FORMAT { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMPLETE_ACTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
