//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROVAL_STEPS
    {
        public string APPROVAL_ROUTING { get; set; }
        public string APPROVAL_GROUP { get; set; }
        public string APPROVAL_STEP { get; set; }
        public string APPROVAL_ROLE { get; set; }
        public Nullable<int> APPROVAL_ORDER { get; set; }
        public string APPROVAL_REASON { get; set; }
        public Nullable<int> WAIT_TIMEOUT { get; set; }
        public string SEND_ALERTS { get; set; }
        public string SEND_EMAIL { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
