//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROVAL_DETAILS
    {
        public int APPROVAL_ID { get; set; }
        public string APPROVAL_STEP { get; set; }
        public string APPROVAL_ROLE { get; set; }
        public string APPROVAL_REASON { get; set; }
        public Nullable<int> APPROVAL_ORDER { get; set; }
        public Nullable<System.DateTime> DATE_ASSIGNED { get; set; }
        public Nullable<System.DateTime> DATE_APPROVAL_DUE { get; set; }
        public Nullable<System.DateTime> DATE_APPROVED { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string APPROVED { get; set; }
        public string APPROVED_BY { get; set; }
        public string FULL_USER_NAME { get; set; }
        public string ASSIGNED { get; set; }
        public Nullable<int> WAIT_TIMEOUT { get; set; }
        public string SEND_ALERTS { get; set; }
        public string SEND_EMAIL { get; set; }
        public string APPROVAL_COMMENT { get; set; }
        public string RTF_COMMENT { get; set; }
    }
}
