//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVE_DOC_FILE
    {
        public int N_COUNT { get; set; }
        public byte[] IMAGE { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_TYPE { get; set; }
    }
}
