//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVE_DOC
    {
        public int N_COUNT { get; set; }
        public string TYPE { get; set; }
        public string GROUP_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DOC_NUMBER { get; set; }
        public Nullable<int> SAMPLE_NUMBER { get; set; }
    }
}
