//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_LOG_TRANSACTIONS
    {
        public int AUDIT_LOG_TRANSACTION_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public byte AUDIT_ACTION_ID { get; set; }
        public string HOST_NAME { get; set; }
        public string APP_NAME { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int AFFECTED_ROWS { get; set; }
        public Nullable<int> SYSOBJ_ID { get; set; }
    }
}
