//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_ESIG_EVENTS
    {
        public int ENTRY_CODE { get; set; }
        public string TABLE_NAME { get; set; }
        public string INSERT_EVENT { get; set; }
        public string UPDATE_EVENT { get; set; }
        public string DELETE_EVENT { get; set; }
        public string FIELD_NAME_1 { get; set; }
        public string HAS_VALUE_1 { get; set; }
        public string CHANGED_FROM_1 { get; set; }
        public string CHANGED_TO_1 { get; set; }
        public string FIELD_NAME_2 { get; set; }
        public string HAS_VALUE_2 { get; set; }
        public string CHANGED_FROM_2 { get; set; }
        public string CHANGED_TO_2 { get; set; }
        public string FIELD_NAME_3 { get; set; }
        public string HAS_VALUE_3 { get; set; }
        public string CHANGED_FROM_3 { get; set; }
        public string CHANGED_TO_3 { get; set; }
        public string DISPLAY_PHRASE { get; set; }
        public string REASON_LIST { get; set; }
        public string PROMPT_AUDIT { get; set; }
        public string E_SIGNATURE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string E_RECORD { get; set; }
    }
}
