//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASIC_ERROR_LOG
    {
        public int LOG_NUMBER { get; set; }
        public Nullable<System.DateTime> FAILURE_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string WORKSTATION { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string ERROR_MSG { get; set; }
        public string SYSTEM_INFO { get; set; }
        public string PROCESS_NAME { get; set; }
        public string SOURCE_CODE { get; set; }
    }
}
