//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_OBJECTS
    {
        public string BATCH { get; set; }
        public int OBJECT_ID { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string SAMPLE_TYPE { get; set; }
        public Nullable<int> REFERENCE_SAMPLE { get; set; }
        public string PARAMETER_1 { get; set; }
        public string PARAMETER_2 { get; set; }
        public Nullable<int> SAMPLE_NUMBER { get; set; }
    }
}
