//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_ACTION_DEF
    {
        public string NAME { get; set; }
        public string TEMPLATE { get; set; }
        public int VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public Nullable<int> WAIT_TIME { get; set; }
        public string TIME_FIELD { get; set; }
        public string START_CALCULATION { get; set; }
        public string STOP_CALCULATION { get; set; }
        public Nullable<int> SEQ_NUM { get; set; }
        public string REQUIRED { get; set; }
    }
}
