//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_STANDARD
    {
        public string BATCH_PROTOCOL { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string STANDARD { get; set; }
        public Nullable<int> POSITION { get; set; }
        public Nullable<int> STARTING_POS { get; set; }
        public Nullable<int> REPEAT_INTERVAL { get; set; }
        public string REPEATING_STD { get; set; }
        public string STANDARD_REAGENT { get; set; }
        public string STANDARD_REAG_TMPL { get; set; }
        public string CONCENTRATION { get; set; }
    }
}
