//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string EXT_LINK { get; set; }
        public string GLOBAL_FLAG { get; set; }
        public string GROUP_NAME { get; set; }
        public string TEMPLATE { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string BATCH_COMMENT { get; set; }
        public string OWNER { get; set; }
        public Nullable<int> TEMPLATE_VERSION { get; set; }
        public string INSTRUMENT { get; set; }
        public string BATCH_TYPE { get; set; }
        public string BATCH_STATUS { get; set; }
        public string ASSIGN_TO_OBJECTS { get; set; }
        public string ANALYSIS_LINK_FIELD { get; set; }
        public string ANALYSIS_LINK_KEY { get; set; }
        public string CHANGE_LINK_KEY { get; set; }
        public string CLOSED { get; set; }
        public Nullable<int> REFRESH_INTERVAL { get; set; }
        public string VARIATION { get; set; }
        public string SIGNED { get; set; }
        public string INVESTIGATED { get; set; }
    }
}
