//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_HDR_TEMPLATE
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string EXT_LINK { get; set; }
        public string GROUP_NAME { get; set; }
        public string REMOVED { get; set; }
        public string NAME_PREFIX { get; set; }
        public string ID_CONFIG { get; set; }
        public string GLOBAL_FLAG { get; set; }
        public string BATCH_PROTOCOL { get; set; }
        public string ASSIGN_TO_OBJECTS { get; set; }
        public string ANALYSIS_LINK_FIELD { get; set; }
        public string ANALYSIS_LINK_KEY { get; set; }
        public string CHANGE_LINK_KEY { get; set; }
        public string FOLDER_TAG { get; set; }
        public Nullable<int> REQUIRED_NUM { get; set; }
        public Nullable<int> MAXIMUM_NUM { get; set; }
        public Nullable<int> REFRESH_INTERVAL { get; set; }
        public string ADD_IF_BATCHED { get; set; }
        public string BATCH_REPORT { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string SCAN_FIELD { get; set; }
        public string BATCH_TYPE { get; set; }
        public string EDIT_TEST_TEMP { get; set; }
        public string EDIT_SAMPLE_TEMP { get; set; }
        public string CHART_GROUP { get; set; }
    }
}
