//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_COMPONENT
    {
        public string TEMPLATE { get; set; }
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string RESULT_TYPE { get; set; }
        public string UNITS { get; set; }
        public string MINIMUM { get; set; }
        public string MAXIMUM { get; set; }
        public string ALLOW_OUT { get; set; }
        public Nullable<int> PLACES { get; set; }
        public Nullable<int> NUM_REPLICATES { get; set; }
        public string USES_CODES { get; set; }
        public string AUTO_CALC { get; set; }
        public string LIST_KEY { get; set; }
        public string ALLOW_CANCEL { get; set; }
        public string CAS_NUMBER { get; set; }
        public string ALIAS_NAME { get; set; }
        public string REPORTABLE { get; set; }
        public string OPTIONAL { get; set; }
        public string ROUND { get; set; }
        public string CLAMP_LOW { get; set; }
        public string CLAMP_HIGH { get; set; }
        public string STD_REAG_TEMPLATE { get; set; }
        public string HAS_ATTRIBUTES { get; set; }
        public string FORMAT_CALCULATION { get; set; }
        public string DISPLAYED { get; set; }
        public string VERSION_FILES { get; set; }
        public string STEP { get; set; }
    }
}
