//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_STEPS
    {
        public string STEP { get; set; }
        public string TEMPLATE { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public Nullable<int> NUM_SAMPLES { get; set; }
    }
}
