//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BROWSE_TAG_PROPS
    {
        public string QUERY_TAG { get; set; }
        public string TABLE_NAME { get; set; }
        public string PROMPT_TEXT { get; set; }
        public string WHERE_CLAUSE { get; set; }
    }
}
