//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALC_TRIGGER
    {
        public Nullable<int> ORIGINAL_SAMPLE { get; set; }
        public string CALC_GROUP { get; set; }
        public int SAMPLE_NUMBER { get; set; }
        public int TEST_NUMBER { get; set; }
        public string ANALYSIS { get; set; }
        public string COMPONENT { get; set; }
    }
}
