//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALC_VARIABLES
    {
        public string ANALYSIS { get; set; }
        public string COMPONENT { get; set; }
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string REFERENCE_TYPE { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string ATTRIBUTE_1 { get; set; }
        public string RETURN_VALUE { get; set; }
        public string SCOPE { get; set; }
        public string FUNCTION { get; set; }
        public string RESULT_FIELD { get; set; }
        public string SPECIFIC_ANALYSIS { get; set; }
        public string ATTRIBUTE_2 { get; set; }
        public string CALC_TRIGGER { get; set; }
    }
}
