//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR_SCHEDULE
    {
        public System.DateTime SCHEDULE_DATE { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public Nullable<int> NUM_SAMPLES { get; set; }
        public string TEST_LIST { get; set; }
        public string COMPLETE { get; set; }
        public string WORKSTATION { get; set; }
        public string BATCH_TEMPLATE { get; set; }
        public string REPORT_TAG { get; set; }
        public string SUBROUTINE { get; set; }
    }
}
