//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGES
    {
        public int CHARGE_ENTRY { get; set; }
        public string CHARGE_CODE { get; set; }
        public Nullable<float> CHARGE { get; set; }
        public string DESCRIPTION { get; set; }
        public string PROJECT { get; set; }
        public string CHARGE_TYPE { get; set; }
        public string CHARGED_BY { get; set; }
        public Nullable<System.DateTime> CHARGED_ON { get; set; }
        public Nullable<System.DateTime> CHARGED_DATE { get; set; }
    }
}
