//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_INSTANCE
    {
        public string CLIENT_NAME { get; set; }
        public string SERVICE { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string AVAILABLE { get; set; }
        public Nullable<int> NUM_USERS { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<int> SOCKET_TIMEOUT { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<int> SLL_HASH { get; set; }
    }
}
