//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENT_FACTORS
    {
        public string ANALYSIS { get; set; }
        public string COMPONENT { get; set; }
        public int VERSION { get; set; }
        public int REPLICATE_COUNT { get; set; }
        public string VALUE { get; set; }
        public string OPERATOR { get; set; }
    }
}
