//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENT
    {
        public string ANALYSIS { get; set; }
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string RESULT_TYPE { get; set; }
        public string UNITS { get; set; }
        public string MINIMUM { get; set; }
        public string MAXIMUM { get; set; }
        public string ALLOW_OUT { get; set; }
        public Nullable<int> PLACES { get; set; }
        public Nullable<int> NUM_REPLICATES { get; set; }
        public string USES_INSTRUMENT { get; set; }
        public string USES_CODES { get; set; }
        public string AUTO_CALC { get; set; }
        public string LIST_KEY { get; set; }
        public string ALLOW_CANCEL { get; set; }
        public string CAS_NUMBER { get; set; }
        public string ALIAS_NAME { get; set; }
        public string REPORTABLE { get; set; }
        public string OPTIONAL { get; set; }
        public string ROUND { get; set; }
        public string CLAMP_LOW { get; set; }
        public string CLAMP_HIGH { get; set; }
        public string STD_REAG_TEMPLATE { get; set; }
        public string HAS_ATTRIBUTES { get; set; }
        public string FORMAT_CALCULATION { get; set; }
        public string DISPLAYED { get; set; }
        public string VERSION_FILES { get; set; }
        public string STEP { get; set; }
        public string ATTRIBUTE_1 { get; set; }
        public string ATTRIBUTE_2 { get; set; }
        public string ATTRIBUTE_3 { get; set; }
        public string ATTRIBUTE_4 { get; set; }
        public string ATTRIBUTE_5 { get; set; }
        public string F25PARAM_ID { get; set; }
        public string F25COMP_ITEM { get; set; }
        public string REPORTABLE_PASSPORT { get; set; }
        public string C_707_3631_EXP { get; set; }
        public string C_708_2848 { get; set; }
        public string C_707_3636 { get; set; }
        public string C_708_2862 { get; set; }
        public string C_707_3644 { get; set; }
        public string C_707_3591 { get; set; }
        public string C_708_2832 { get; set; }
        public string C_708_2830 { get; set; }
        public string C_708_2948 { get; set; }
        public string BROWSE_SUBROUTINE { get; set; }
        public string NWA_NAME { get; set; }
        public string X_VKK_FLAG { get; set; }
        public string REPORTED_NAME { get; set; }
    }
}
