//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_PACK_TABLE
    {
        public string CONFIG_PACKAGE { get; set; }
        public int VERSION { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string ACTION { get; set; }
        public string DATA_TYPE { get; set; }
        public Nullable<int> FIELD_SIZE { get; set; }
    }
}
