//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_PACK_OBJECT
    {
        public string CONFIG_PACKAGE { get; set; }
        public int VERSION { get; set; }
        public Nullable<int> CONFIG_ELEMENT_ID { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string OBJECT_CLASS { get; set; }
        public Nullable<int> OBJECT_ID { get; set; }
        public string OBJECT_NAME { get; set; }
        public Nullable<int> OBJECT_VERSION { get; set; }
        public string OVERWRITE { get; set; }
        public string CHECKED_OUT_BY { get; set; }
        public Nullable<System.DateTime> CHECKED_OUT_ON { get; set; }
        public string OBJ_CHANGED_BY { get; set; }
        public Nullable<System.DateTime> OBJ_CHANGED_ON { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> ADDED_ON { get; set; }
        public string DBFILE_NAME { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> CONFIG_HISTORY_ID { get; set; }
        public string ORIG_CHANGED_BY { get; set; }
        public Nullable<System.DateTime> ORIG_CHANGED_ON { get; set; }
    }
}
