//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_PACKAGE
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string ITEM_TABLES { get; set; }
        public string ITEM_TEMPLATES { get; set; }
        public string PARENT_PACKAGE { get; set; }
        public string CLOSED { get; set; }
        public string CHECKED_OUT_BY { get; set; }
        public Nullable<System.DateTime> CHECKED_OUT_ON { get; set; }
        public string PACKAGE_NOTES { get; set; }
        public Nullable<int> DB_BUILD_NUMBER { get; set; }
        public string USE_DB_BUILD_NUMBER { get; set; }
        public string PRE_BUILD_SUB { get; set; }
        public string POST_BUILD_SUB { get; set; }
        public string PRE_INSTALL_SUB { get; set; }
        public string POST_INSTALL_SUB { get; set; }
    }
}
