//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_PACK_WINDOW
    {
        public string CONFIG_PACKAGE { get; set; }
        public int VERSION { get; set; }
        public int CONFIG_ELEMENT_ID { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string WINDOW_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> ADDED_ON { get; set; }
        public string OVERWRITE { get; set; }
    }
}
