//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_PACK_FILE
    {
        public string CONFIG_PACKAGE { get; set; }
        public int VERSION { get; set; }
        public int CONFIG_ELEMENT_ID { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string ROOT_DIR { get; set; }
        public string SUB_DIR { get; set; }
        public string FILE_NAME { get; set; }
        public string OVERWRITE { get; set; }
        public Nullable<System.DateTime> FILE_CHANGED_ON { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> ADDED_ON { get; set; }
        public string DBFILE_NAME { get; set; }
        public Nullable<int> CONFIG_HISTORY_ID { get; set; }
    }
}
