//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int CONTACT_NUMBER { get; set; }
        public string CUSTOMER { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TYPE { get; set; }
        public Nullable<int> SAMPLE_REFERENCE { get; set; }
        public string PROJECT_REFERENCE { get; set; }
        public string ANALYSIS_REFERENCE { get; set; }
        public string REASON { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> ENTERED_ON { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> ALERT_NUMBER { get; set; }
        public string EXT_LINK { get; set; }
        public string INVESTIGATION { get; set; }
        public string TABLE_NAME { get; set; }
        public string KEY_VALUE { get; set; }
        public string TEMPLATE { get; set; }
        public string NOTIFIED { get; set; }
        public string NOTIFIED_BY { get; set; }
        public Nullable<System.DateTime> NOTIFIED_ON { get; set; }
        public string GROUP_NAME { get; set; }
        public string REMOVED { get; set; }
        public string ORDER_NUM { get; set; }
    }
}
