//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_EXPLORER_FLDS
    {
        public string DATA_EXPLORER { get; set; }
        public int COL_NUM { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string SORT_ORDER { get; set; }
        public string SHOW_FLAG { get; set; }
        public string CRITERIA { get; set; }
        public string OR_1 { get; set; }
        public string OR_2 { get; set; }
        public string OR_3 { get; set; }
        public string OR_4 { get; set; }
        public string OR_5 { get; set; }
        public string OR_6 { get; set; }
        public string OR_7 { get; set; }
        public string OR_8 { get; set; }
        public string OR_9 { get; set; }
        public string OR_10 { get; set; }
    }
}
