//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATABASE_EVENTS
    {
        public string TABLE_NAME { get; set; }
        public string EVENT_NAME { get; set; }
        public string SUB_NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string OR_FIELDS { get; set; }
        public string FIELD_NAME_1 { get; set; }
        public string HAS_VALUE_1 { get; set; }
        public string CHANGED_FROM_1 { get; set; }
        public string CHANGED_TO_1 { get; set; }
        public string FIELD_NAME_2 { get; set; }
        public string HAS_VALUE_2 { get; set; }
        public string CHANGED_FROM_2 { get; set; }
        public string CHANGED_TO_2 { get; set; }
    }
}
