//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAYLIGHT_SAVINGS
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<System.DateTime> START_DATE_TIME { get; set; }
        public Nullable<System.DateTime> END_DATE_TIME { get; set; }
        public Nullable<int> TIME_OFFSET_MIN { get; set; }
        public string START_DAY_RANK { get; set; }
        public string START_WEEK_DAY { get; set; }
        public string START_MONTH { get; set; }
        public string START_TIME { get; set; }
        public string END_DAY_RANK { get; set; }
        public string END_WEEK_DAY { get; set; }
        public string END_MONTH { get; set; }
        public string END_TIME { get; set; }
        public string SET_FIX_DATE { get; set; }
    }
}
