//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_FILES
    {
        public Nullable<int> DIR_NUM { get; set; }
        public string FILE_NAME { get; set; }
        public string ORIGINAL_PATH { get; set; }
        public string ORIGINAL_NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string HASH { get; set; }
        public string FILE_LABEL { get; set; }
        public string POSTED { get; set; }
        public string INSTRUMENT { get; set; }
        public byte[] FILE_CONTENTS { get; set; }
    }
}
