//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SCRIPTS
    {
        public int ORDER_NUMBER { get; set; }
        public string DATABASE_TYPE { get; set; }
        public string ACCESS_DATA_TYPE { get; set; }
        public string DB_DATA_TYPE { get; set; }
        public string STATEMENT_SUFFIX { get; set; }
    }
}
