//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISP_REPORT
    {
        public string X_PROCESS_UNIT { get; set; }
        public string Product { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string NAME { get; set; }
        public string Id { get; set; }
    }
}
