//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPLAY_FIELDS
    {
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
