//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTS
    {
        public string EVENT { get; set; }
        public string TEMPLATE { get; set; }
        public string TYPE { get; set; }
        public string ENABLED_FLAG { get; set; }
        public string REPORT_ID { get; set; }
        public string PRINT_FLAG { get; set; }
        public string FILE_FLAG { get; set; }
        public string FILE_NAME { get; set; }
        public string INCREMENT_FLAG { get; set; }
        public Nullable<int> FILE_VERSION { get; set; }
        public string MAIL_FLAG { get; set; }
        public string MAIL_TO { get; set; }
        public string MAIL_TO_SOURCE { get; set; }
        public string FORMULA_FLAG { get; set; }
        public string FORMULA { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
    }
}
