//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPIRATION_HISTORY
    {
        public string INSTRUMENT { get; set; }
        public System.DateTime DATE { get; set; }
        public string REASON { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> COMPLITED_DATE { get; set; }
    }
}
