//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_ITA
    {
        public Nullable<int> STAB_SAMPLE_NUMB { get; set; }
        public Nullable<float> CURR_AVRG { get; set; }
        public Nullable<int> SMPLS_NUMB { get; set; }
        public Nullable<int> FIRST_SMPL { get; set; }
        public Nullable<int> LAST_SMPL { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string PROJECT { get; set; }
        public int SEQ_NUM { get; set; }
    }
}
