//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_ITD
    {
        public string DATA_LOGIC { get; set; }
        public Nullable<int> SAMPLE_NUMB { get; set; }
        public Nullable<int> ORIGIN_SMPL { get; set; }
        public string STAND_REAG { get; set; }
        public string DONT_USE { get; set; }
        public string STOP_SER { get; set; }
        public string PROCESSED { get; set; }
        public Nullable<float> ATT_VAL { get; set; }
        public Nullable<float> SER_AVERAGE { get; set; }
        public Nullable<float> DELUTION { get; set; }
        public Nullable<float> ADDITION { get; set; }
        public Nullable<float> X_AVRG_0 { get; set; }
        public Nullable<float> X1 { get; set; }
        public Nullable<float> X2 { get; set; }
        public Nullable<float> X3 { get; set; }
        public Nullable<float> X4 { get; set; }
        public Nullable<float> X5 { get; set; }
        public Nullable<float> X_AVRG { get; set; }
        public Nullable<int> CERTIF_SUBDIAP { get; set; }
        public Nullable<int> PROT_SUBDIAP { get; set; }
        public string REP_MODE { get; set; }
        public string REP_NORM { get; set; }
        public Nullable<float> REP_RES { get; set; }
        public string REP_CONCL { get; set; }
        public string REP_INTERP { get; set; }
        public Nullable<float> REP_MIDDL { get; set; }
        public Nullable<float> REP_WARN { get; set; }
        public Nullable<float> REP_CNTRL { get; set; }
        public string PREC_MODE { get; set; }
        public string PREC_NORM { get; set; }
        public Nullable<int> PREV_PREC_SMPL { get; set; }
        public Nullable<float> PREC_RES { get; set; }
        public string PREC_CONCL { get; set; }
        public string PREC_INTERP { get; set; }
        public Nullable<float> PREC_MIDDL { get; set; }
        public Nullable<float> PREC_WARN { get; set; }
        public Nullable<float> PREC_CNTRL { get; set; }
        public string ACCUR_MODE { get; set; }
        public string ACCUR_NORM { get; set; }
        public Nullable<float> ACCUR_RES { get; set; }
        public string ACCUR_CONCL { get; set; }
        public string ACCUR_INTERP { get; set; }
        public Nullable<float> ACCUR_WARN { get; set; }
        public Nullable<float> ACCUR_CNTRL { get; set; }
        public string QSUM_NORM { get; set; }
        public Nullable<float> QSUM_RES { get; set; }
        public Nullable<float> QSUM_THRESH { get; set; }
        public Nullable<float> QSUM_CNTRL { get; set; }
        public string QSM_PLS_BEG { get; set; }
        public Nullable<float> QSUM_PLUS_1 { get; set; }
        public Nullable<float> QSUM_PLUS_2 { get; set; }
        public string QSUM_PLS_CNCL { get; set; }
        public string QSM_MNS_BEG { get; set; }
        public Nullable<float> QSUM_MINUS_1 { get; set; }
        public Nullable<float> QSUM_MINUS_2 { get; set; }
        public string QSUM_MNS_CNCL { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string PROJECT { get; set; }
        public int SEQ_NUM { get; set; }
        public string SAVED_PROJECT { get; set; }
        public Nullable<int> SAVED_ORD_NMB { get; set; }
    }
}
