//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_ITQ
    {
        public string PROJECT { get; set; }
        public string STD_REAG { get; set; }
        public Nullable<int> STAB_SMPL { get; set; }
        public Nullable<float> BASE_X { get; set; }
        public Nullable<float> D_X { get; set; }
        public Nullable<float> NEW_ABS_REP { get; set; }
        public Nullable<float> NEW_ABS_PREC { get; set; }
        public Nullable<float> AVRG_X { get; set; }
        public Nullable<float> THETA { get; set; }
        public Nullable<float> T { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<float> T_TBL { get; set; }
        public Nullable<float> CORRECTION { get; set; }
        public Nullable<float> NEW_ABS_TRUEN { get; set; }
        public Nullable<float> NEW_ABS_ACC { get; set; }
        public Nullable<float> GAMMA { get; set; }
        public Nullable<int> REP_MIN_L { get; set; }
        public Nullable<int> PREC_MIN_L { get; set; }
        public Nullable<int> ACC_MIN_L { get; set; }
        public Nullable<int> L_REP { get; set; }
        public Nullable<int> L_PREC { get; set; }
        public string REP_MODE { get; set; }
        public Nullable<float> NEW_REP { get; set; }
        public string PREC_MODE { get; set; }
        public Nullable<float> NEW_PREC { get; set; }
        public string ACC_MODE { get; set; }
        public Nullable<float> NEW_ACC { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public int SEQ_NUM { get; set; }
    }
}
