//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_ITP
    {
        public string DESCRIPTION { get; set; }
        public string STD_REAG { get; set; }
        public Nullable<float> ATT_VAL { get; set; }
        public string RESULTS { get; set; }
        public Nullable<float> X_AVRG { get; set; }
        public Nullable<float> STD_DEV { get; set; }
        public Nullable<float> X_DIFF { get; set; }
        public Nullable<float> PREC_NORM { get; set; }
        public Nullable<float> TRUEN_NORM { get; set; }
        public string CONCLUSION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public int SEQ_NUM { get; set; }
        public string PROJECT { get; set; }
    }
}
