//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_ITR
    {
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string IS_ACTIVE { get; set; }
        public string SIGFIGS_RND { get; set; }
        public Nullable<int> REP_RES_RND { get; set; }
        public Nullable<int> REP_CNTRL_LIM_RND { get; set; }
        public Nullable<int> PREC_RES_RND { get; set; }
        public Nullable<int> PREC_CNTRL_LIM_RND { get; set; }
        public Nullable<int> ACC_RES_RND { get; set; }
        public Nullable<int> ACC_CNTRL_LIM_RND { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public int SEQ_NUM { get; set; }
        public string PROJECT { get; set; }
    }
}
