//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_PR_PAR
    {
        public string F25CNTRL_PR_PAR1 { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CNTRL_ELEM { get; set; }
        public string CNTRL_FORM { get; set; }
        public string REP_CC_TYPE { get; set; }
        public string PREC_CC_TYPE { get; set; }
        public string ACCUR_CC_TYPE { get; set; }
        public string QSUM_ACCUR_CC { get; set; }
        public string METHOD { get; set; }
        public string USE_STD_REAG { get; set; }
        public string COMPAR_METH { get; set; }
        public Nullable<int> CMPR_MTH_VER { get; set; }
        public string ADD_FOR_PREC { get; set; }
        public string ADD_FOR_REP { get; set; }
        public string AS_ALIQUOT { get; set; }
        public string PERIOD_RELATIVE { get; set; }
        public string QUALITY_LEVEL { get; set; }
        public string CONTROL_GRADE { get; set; }
    }
}
