//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CERTIF
    {
        public string ANALYSIS { get; set; }
        public int VERSION { get; set; }
        public string CERTIFNAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> REITN { get; set; }
        public string UNITS { get; set; }
        public string USER_FUNK { get; set; }
        public string ATTEST_ORGANIZ { get; set; }
        public Nullable<int> CERT_NUMB { get; set; }
        public string ANALYS_NAME { get; set; }
        public string ORGANIZ { get; set; }
        public string DOCUMENT { get; set; }
        public string ATTEST { get; set; }
        public string ORGAN_HEAD { get; set; }
        public Nullable<System.DateTime> ORGAN_DATE { get; set; }
    }
}
