//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_PR_PAR_SMPL
    {
        public string F25CNTRL_PR_PAR { get; set; }
        public string F25CNTRL_PR_PAR_SMPL1 { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string DO_NOT_SHOW { get; set; }
    }
}
