//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_CNF
    {
        public string PROJECT { get; set; }
        public Nullable<int> MIN_SMPL { get; set; }
        public Nullable<int> MAX_SMPL { get; set; }
        public string SRC_OBJ { get; set; }
    }
}
