//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25CNTRL_PR_PAR_DTL
    {
        public string F25CNTRL_PR_PAR { get; set; }
        public string F25CNTRL_PR_PAR_DTL1 { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<float> LOW_LIM { get; set; }
        public Nullable<float> HIGH_LIM { get; set; }
        public string UNITS { get; set; }
        public Nullable<float> BASE_VAL { get; set; }
        public Nullable<float> R_REP { get; set; }
        public Nullable<float> R_PREC { get; set; }
        public Nullable<float> D_ACC { get; set; }
        public Nullable<float> R_REP_L { get; set; }
        public Nullable<float> R_PREC_L { get; set; }
        public Nullable<float> D_ACC_L { get; set; }
        public Nullable<float> GAMMA { get; set; }
        public Nullable<int> MIN_ACC_N { get; set; }
        public Nullable<int> MIN_PREC_N { get; set; }
        public Nullable<int> RECOM_N { get; set; }
        public Nullable<int> MONTH_OBS { get; set; }
        public Nullable<int> PER_RECOM_N { get; set; }
        public Nullable<int> PER_MONTH_OBS { get; set; }
    }
}
