//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25INS_ITC
    {
        public string DONT_USE { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<float> C_ATT { get; set; }
        public Nullable<float> D_C_ATT { get; set; }
        public Nullable<float> S_REPEAT_M { get; set; }
        public Nullable<float> X_M { get; set; }
        public Nullable<float> X_M_ADD { get; set; }
        public Nullable<float> ADD_AVRG { get; set; }
        public Nullable<float> S_PREC_M { get; set; }
        public Nullable<float> S_PREC_M_ADD { get; set; }
        public Nullable<float> THETA_M { get; set; }
        public Nullable<float> T_M { get; set; }
        public Nullable<float> T_TBL_M { get; set; }
        public Nullable<float> PREC_QI { get; set; }
        public Nullable<float> D_TRUEN_M { get; set; }
        public Nullable<float> D_ACCUR_M { get; set; }
        public Nullable<int> STD_SMPL_NUMB { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string PROJECT { get; set; }
        public int SEQ_NUM { get; set; }
    }
}
