//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25INS_ITR
    {
        public string QLT_IND { get; set; }
        public string USED { get; set; }
        public string DEVIDE { get; set; }
        public string PROC_MODE { get; set; }
        public string REGR_TYPE { get; set; }
        public Nullable<float> LMB1 { get; set; }
        public Nullable<float> LMB2 { get; set; }
        public Nullable<float> R_CORR { get; set; }
        public Nullable<float> R_TBL { get; set; }
        public string IS_OK { get; set; }
        public Nullable<float> DISTANCE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string PROJECT { get; set; }
        public int SEQ_NUM { get; set; }
    }
}
