//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25INS_ITD
    {
        public string DONT_USE { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<float> X_AVRG_0 { get; set; }
        public Nullable<float> X1 { get; set; }
        public Nullable<float> X2 { get; set; }
        public Nullable<float> X3 { get; set; }
        public Nullable<float> X4 { get; set; }
        public Nullable<float> X5 { get; set; }
        public Nullable<float> X_AVRG { get; set; }
        public Nullable<float> DISP_X { get; set; }
        public Nullable<float> C_ATT { get; set; }
        public Nullable<float> D_C_ATT { get; set; }
        public Nullable<float> ADDITION { get; set; }
        public Nullable<int> SAMPLE_NUMB { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string PROJECT { get; set; }
        public int SEQ_NUM { get; set; }
    }
}
