//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25OPERCONTR
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
        public string ANALYSIS { get; set; }
        public Nullable<int> AN_VERSION { get; set; }
        public string TEST { get; set; }
        public Nullable<int> IDENT_NUMB { get; set; }
        public string OBJECT { get; set; }
        public string COMPONENT { get; set; }
        public Nullable<float> X1 { get; set; }
        public Nullable<float> X2 { get; set; }
        public Nullable<float> X3 { get; set; }
        public Nullable<float> X4 { get; set; }
        public Nullable<float> X5 { get; set; }
        public Nullable<float> ATT_VAL { get; set; }
        public Nullable<float> REZ_AVR { get; set; }
        public Nullable<float> REZ { get; set; }
        public Nullable<float> LIMREZ { get; set; }
        public string CONCLUSION { get; set; }
        public string ADD_NOTE { get; set; }
        public string EXECUTOR { get; set; }
        public Nullable<float> SPECIFIC { get; set; }
        public Nullable<float> REZ_RAZB { get; set; }
        public Nullable<float> K_RAZB { get; set; }
        public Nullable<float> REZ_DOB { get; set; }
        public Nullable<float> DOBAV { get; set; }
        public string CNTRL_TYPE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
    }
}
