//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25PRJ_QIND
    {
        public string ROUND_MODE { get; set; }
        public Nullable<float> RANG_LOW { get; set; }
        public Nullable<float> RANG_HIGH { get; set; }
        public string RMSD_MODE { get; set; }
        public string RMSD_ROUND { get; set; }
        public string RMSDEVIAT_0 { get; set; }
        public string RMSDEVIAT_1 { get; set; }
        public string PREC_MODE { get; set; }
        public string PREC_ROUND { get; set; }
        public string PRECISION_0 { get; set; }
        public string PRECISION_1 { get; set; }
        public string TRUEN_MODE { get; set; }
        public string TRUEN_ROUND { get; set; }
        public string TRUENESS_0 { get; set; }
        public string TRUENESS_1 { get; set; }
        public string ACCUR_MODE { get; set; }
        public string ACCUR_ROUND { get; set; }
        public string ACCURACY_0 { get; set; }
        public string ACCURACY_1 { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string PROJECT { get; set; }
        public int SEQ_NUM { get; set; }
    }
}
