//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25PRODQINDS_INDS
    {
        public string ANALYSIS { get; set; }
        public int VERSION { get; set; }
        public string Product { get; set; }
        public string QINDSNAME { get; set; }
        public string INDSNAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<float> RANG_LOW { get; set; }
        public string RANG_LOW_MOD { get; set; }
        public Nullable<float> RANG_HIGH { get; set; }
        public string RANG_HIGH_MOD { get; set; }
        public string RMSD_MODE { get; set; }
        public string RMSDEVIAT_0 { get; set; }
        public string RMSDEVIAT_1 { get; set; }
        public string PREC_MODE { get; set; }
        public string PRECISION_0 { get; set; }
        public string PRECISION_1 { get; set; }
        public string TRUEN_MODE { get; set; }
        public string TRUENESS_0 { get; set; }
        public string TRUENESS_1 { get; set; }
        public string ACCUR_MODE { get; set; }
        public string ACCURACY_0 { get; set; }
        public string ACCURACY_1 { get; set; }
        public string X_DEPARTMENT { get; set; }
    }
}
