//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25PROCESS
    {
        public string F25PROCESS1 { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string TITLE { get; set; }
        public string ANALYSIS { get; set; }
        public Nullable<int> AN_VERSION { get; set; }
        public string VARIATION { get; set; }
        public string PARAM_ID { get; set; }
        public string Product { get; set; }
        public string OBJECT_DESCR { get; set; }
        public string USED_QINDS { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string PROC_TYPE { get; set; }
        public string CNFG_TP_PAR { get; set; }
        public string INSRT_TP_PAR { get; set; }
        public string CNTRL_TP_PAR { get; set; }
        public string STATUS { get; set; }
        public string PROJ_TMPL { get; set; }
        public Nullable<int> PROJ_TMPL_VERS { get; set; }
        public string PROJECT { get; set; }
        public string F25CAN_CHANGE { get; set; }
        public Nullable<int> BKK_VARIANT { get; set; }
        public string X_DEPARTMENT { get; set; }
    }
}
