//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class F25QINDS
    {
        public string ANALYSIS { get; set; }
        public int VERSION { get; set; }
        public string QINDSNAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> REITN { get; set; }
        public string UNITS { get; set; }
        public string USER_FUNK { get; set; }
        public string USER_FUNK_MODE { get; set; }
        public string LAB_DESCR { get; set; }
        public string ANALYS_NAME { get; set; }
        public string DOCUMENT { get; set; }
        public string BASIS { get; set; }
        public Nullable<System.DateTime> BEGDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string METROLOG { get; set; }
        public Nullable<System.DateTime> METR_DATE { get; set; }
        public string LAB_HEAD { get; set; }
        public Nullable<System.DateTime> LAB_DATE { get; set; }
        public string X_DEPARTMENT { get; set; }
    }
}
