//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_MASTER
    {
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string LINK_TABLE { get; set; }
        public string DATA_TYPE { get; set; }
        public string HIDDEN { get; set; }
        public string LIST_KEY { get; set; }
        public string RESET_TO_NULL { get; set; }
        public string MANDATORY { get; set; }
        public string WHERE_CLAUSE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string SET_DEFAULT_VALUE { get; set; }
    }
}
