//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLAGS
    {
        public int ENTRY_CODE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string TEMPLATE { get; set; }
        public string OBJECT_TYPE { get; set; }
        public Nullable<int> OBJECT_ID { get; set; }
        public string OBJECT_NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string DISPLAYED { get; set; }
        public string FLAG_SEVERITY { get; set; }
        public string REQUIRES_ACTION { get; set; }
        public string ACTIONED { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string FLAG_COMMENT { get; set; }
    }
}
