//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLDER_TEMPLATE
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string GLOBAL_FLAG { get; set; }
        public string AUTO_REFRESH_FLAG { get; set; }
        public string AUTO_REBUILD_FLAG { get; set; }
        public string GROUP_NAME { get; set; }
        public string QUERY_TAG { get; set; }
        public string REMOVED { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<int> REFRESH_INTERVAL { get; set; }
        public string SUMMARY_REPORT { get; set; }
        public string SAMPLE_REPORT { get; set; }
        public string TEST_REPORT { get; set; }
        public string RESULT_REPORT { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string TEST_TEMPLATE { get; set; }
        public string SAMPLE_DISP_FLDS { get; set; }
        public string TEST_DISP_FLDS { get; set; }
        public string GROUP_BY_FIELD { get; set; }
        public string GROUP_SAMPLE_RPT { get; set; }
        public string SCAN_FIELD { get; set; }
        public string LOAD_RESULTS { get; set; }
        public string LOGIN_TAB { get; set; }
        public string ENTER_RESULTS_TAB { get; set; }
        public string TEST_EDIT_TAB { get; set; }
        public Nullable<int> MAX_RECORDS { get; set; }
        public string LABEL_MASK { get; set; }
        public string CHART_GROUP { get; set; }
    }
}
