//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLDER
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string GLOBAL_FLAG { get; set; }
        public string OWNER { get; set; }
        public string AUTO_REFRESH_FLAG { get; set; }
        public string AUTO_REBUILD_FLAG { get; set; }
        public string GROUP_NAME { get; set; }
        public string TEMPLATE { get; set; }
        public string SQL { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> LAST_CHANGED { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string EXT_LINK { get; set; }
        public string SORT_FIELDS { get; set; }
        public Nullable<int> REFRESH_INTERVAL { get; set; }
        public string READ_ONLY { get; set; }
        public string SCAN_FIELD { get; set; }
        public string FOLDER_VIEW { get; set; }
        public string GROUP_BY_FIELD { get; set; }
    }
}
