//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_TEMP_FIELDS
    {
        public string TEMPLATE { get; set; }
        public Nullable<int> ENTRY_CODE { get; set; }
        public string FIELD_NAME { get; set; }
        public int VERSION { get; set; }
        public string ENTRY_MODE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string FIELD_LABEL { get; set; }
        public string LABEL_POSITION { get; set; }
        public string FORMULA { get; set; }
        public string ALLOW_USER_ENTRY { get; set; }
        public string DATA_TYPE { get; set; }
        public string DEPENDS_ON { get; set; }
        public string GROUP_TITLE { get; set; }
        public Nullable<int> FIELD_SIZE { get; set; }
        public string SEARCH_ON { get; set; }
        public Nullable<int> COL_SPAN { get; set; }
        public Nullable<int> NUM_ROWS { get; set; }
        public string LIST_NAME { get; set; }
        public string LINK_TABLE { get; set; }
        public Nullable<int> FIELD_NUMBER { get; set; }
        public Nullable<float> MIN_LIMIT { get; set; }
        public Nullable<float> MAX_LIMIT { get; set; }
        public string SECTION { get; set; }
    }
}
