//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULATION_TEMP
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string ID_CONFIG { get; set; }
        public string PROJECT_TEMPLATE { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string USES_RECIPE { get; set; }
        public string SAMPLE_FORM_FLD { get; set; }
        public string ITEM_TABLES { get; set; }
        public string ITEM_TEMPLATES { get; set; }
        public string REPORTS { get; set; }
        public string PACKAGE_TEMPLATE { get; set; }
        public string USES_INVENTORY { get; set; }
        public string MAN_ACTUAL_QUANT { get; set; }
        public string SCAN_FIELD { get; set; }
        public string CHECK_EXPIR_CLOSED { get; set; }
        public string AUTO_REFRESH_VIEW { get; set; }
        public string SHOW_ALIQUOTS { get; set; }
    }
}
