//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_TEMPLATE
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string ID_CONFIG { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_DESCRIPTION { get; set; }
        public string EXISTING_TABLE { get; set; }
        public string ITEM_TABLES { get; set; }
        public string DESCRIPTION_MASK { get; set; }
        public string SAVE_WHEN_PAGING { get; set; }
        public string EDIT_CHECK_FORMULA { get; set; }
        public string ADD_CLIN_TRL_SAMPS { get; set; }
        public string COMPLETE_SUB { get; set; }
        public string AUDIT { get; set; }
        public string ESIG_ON_REVIEW { get; set; }
    }
}
