//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_TEMP_SECTION
    {
        public string TEMPLATE { get; set; }
        public int VERSION { get; set; }
        public string SECTION { get; set; }
        public string ENABLE_FORMULA { get; set; }
        public string DEPENDS_ON { get; set; }
    }
}
