//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULATION
    {
        public string NAME { get; set; }
        public string TEMPLATE { get; set; }
        public Nullable<int> TEMPLATE_VERSION { get; set; }
        public string RECIPE { get; set; }
        public Nullable<int> RECIPE_VERSION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string CLOSED { get; set; }
        public Nullable<float> TARGET_QUANTITY { get; set; }
        public Nullable<float> ACTUAL_QUANTITY { get; set; }
        public Nullable<float> REMAINING_QUANTITY { get; set; }
        public string QUANTITY_UNITS { get; set; }
        public string PROJECT { get; set; }
        public string PACKAGES_CREATED { get; set; }
        public Nullable<System.DateTime> CLOSED_ON { get; set; }
        public string CLOSED_BY { get; set; }
        public string CHECK_EXPIR_DATES { get; set; }
        public string X_START_BY { get; set; }
        public Nullable<System.DateTime> X_EXP_DATE { get; set; }
        public Nullable<System.DateTime> X_START_DATE { get; set; }
        public string X_EXP_TEXT { get; set; }
    }
}
