//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULA_INGREDIENT
    {
        public int ENTRY_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string FORMULATION { get; set; }
        public string INGREDIENT { get; set; }
        public string INGREDIENT_LOT { get; set; }
        public string FORMULATION_RECIPE { get; set; }
        public string FORMULATION_INGRED { get; set; }
        public Nullable<int> RECIPE_INGREDIENT { get; set; }
        public Nullable<float> RECIPE_QUANTITY { get; set; }
        public Nullable<float> ACTUAL_QUANTITY { get; set; }
        public string QUANTITY_UNITS { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public Nullable<float> POTENCY { get; set; }
        public Nullable<float> INVENTORY_QUANTITY { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<float> QUANTITY_TOLERANCE { get; set; }
        public string X_IS_FLASK { get; set; }
        public string X_INVENTORY_ENTRY { get; set; }
        public string X_ENTRY_QUANTITY { get; set; }
        public Nullable<float> X_RECIPE_QUANTITY { get; set; }
    }
}
