//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTOGRAM
    {
        public string TEMPLATE { get; set; }
        public string Y_VALUE_FIELD { get; set; }
        public string Y_VAR_DESC { get; set; }
        public string TITLE { get; set; }
        public string TITLE_FONT { get; set; }
        public string TARGET { get; set; }
        public string LOWER_SPEC_LIMIT { get; set; }
        public string UPPER_SPEC_LIMIT { get; set; }
        public string LOWER_WARN_LIMIT { get; set; }
        public string Y_AXIS_SCALE { get; set; }
        public string LABEL_HEADER { get; set; }
        public string LABEL_FIELD { get; set; }
        public string WINDOW_LABEL { get; set; }
        public string SPECIFIC_ANALYSIS { get; set; }
        public string CHART_ANALYSIS { get; set; }
        public string CHART_COMPONENT { get; set; }
    }
}
