//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAY_SCHED_ENTRY
    {
        public string NAME { get; set; }
        public int MONTH { get; set; }
        public int YEAR { get; set; }
        public string DAY_1 { get; set; }
        public string DAY_2 { get; set; }
        public string DAY_3 { get; set; }
        public string DAY_4 { get; set; }
        public string DAY_5 { get; set; }
        public string DAY_6 { get; set; }
        public string DAY_7 { get; set; }
        public string DAY_8 { get; set; }
        public string DAY_9 { get; set; }
        public string DAY_10 { get; set; }
        public string DAY_11 { get; set; }
        public string DAY_12 { get; set; }
        public string DAY_13 { get; set; }
        public string DAY_14 { get; set; }
        public string DAY_15 { get; set; }
        public string DAY_16 { get; set; }
        public string DAY_17 { get; set; }
        public string DAY_18 { get; set; }
        public string DAY_19 { get; set; }
        public string DAY_20 { get; set; }
        public string DAY_21 { get; set; }
        public string DAY_22 { get; set; }
        public string DAY_23 { get; set; }
        public string DAY_24 { get; set; }
        public string DAY_25 { get; set; }
        public string DAY_26 { get; set; }
        public string DAY_27 { get; set; }
        public string DAY_28 { get; set; }
        public string DAY_29 { get; set; }
        public string DAY_30 { get; set; }
        public string DAY_31 { get; set; }
    }
}
