//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFO_RULES
    {
        public int SEQ_NUM { get; set; }
        public string TABLE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string FIELD_1_NAME { get; set; }
        public string FIELD_1_OPERATOR { get; set; }
        public string FIELD_1_VALUE { get; set; }
        public string FIELD_2_NAME { get; set; }
        public string FIELD_2_OPERATOR { get; set; }
        public string FIELD_2_VALUE { get; set; }
        public string ICON_NAME { get; set; }
        public string CLICKED_SUB { get; set; }
        public string MENU_1_TITLE { get; set; }
        public string MENU_1_SUB { get; set; }
        public string MENU_2_TITLE { get; set; }
        public string MENU_2_SUB { get; set; }
        public string MENU_3_TITLE { get; set; }
        public string MENU_3_SUB { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
    }
}
