//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT_LOT
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string INGREDIENT { get; set; }
        public string SUPPLIER { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public Nullable<float> REMAINING_QUANTITY { get; set; }
        public string QUANTITY_UNITS { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<float> POTENCY { get; set; }
    }
}
