//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUMENTS
    {
        public string NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string INST_GROUP { get; set; }
        public string ON_LINE { get; set; }
        public string LOCATION { get; set; }
        public string OPERATOR { get; set; }
        public string VENDOR { get; set; }
        public string SERIAL_NO { get; set; }
        public string X_APLICATION { get; set; }
        public Nullable<System.DateTime> PM_DATE { get; set; }
        public Nullable<int> PM_INTV { get; set; }
        public Nullable<System.DateTime> PM_EXPIRATION { get; set; }
        public Nullable<System.DateTime> CALIB_DATE { get; set; }
        public Nullable<int> CALIB_INTV { get; set; }
        public Nullable<System.DateTime> CALIB_EXPIRATION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
        public string LINK_LOCATION { get; set; }
        public string CALIB_TEMPLATE { get; set; }
        public string SERVICE_TEMPLATE { get; set; }
        public string INST_TEMPLATE { get; set; }
        public string PM_TEMPLATE { get; set; }
        public string PARENT_INSTRUMENT { get; set; }
        public string PARAMETER_1_NAME { get; set; }
        public string PARAMETER_1_VALUE { get; set; }
        public string PARAMETER_2_NAME { get; set; }
        public string PARAMETER_2_VALUE { get; set; }
        public string LABSTATION { get; set; }
        public string BAUD { get; set; }
        public string PARITY { get; set; }
        public string STOP_BITS { get; set; }
        public string DATA_BITS { get; set; }
        public string FLOW_CONTROL { get; set; }
        public Nullable<float> LOW_THRESHOLD { get; set; }
        public Nullable<float> HIGH_THRESHOLD { get; set; }
        public Nullable<float> STABILITY_DELTA { get; set; }
        public Nullable<int> STABILITY_NUMBER { get; set; }
        public string INSTRUMENT_CLASS { get; set; }
        public string NEEDS_CALIBRATION { get; set; }
        public string NEEDS_PM { get; set; }
        public string COMM_PORT { get; set; }
        public string HOLDS_SAMPLES { get; set; }
        public string DATA_PATH { get; set; }
        public Nullable<int> DISCARD_TIME { get; set; }
        public string FILTER_SCRIPT { get; set; }
        public string PARSING_SCRIPT { get; set; }
        public string POST_ARCHIVE_ACTION { get; set; }
        public Nullable<int> SIZE_LIMIT { get; set; }
        public string SYNC_PATTERN { get; set; }
        public string TERM_PATTERN { get; set; }
        public Nullable<int> TIME_OUT { get; set; }
        public string XMIT_PREFIX { get; set; }
        public string XMIT_SUFFIX { get; set; }
        public Nullable<int> POLLING_TIME { get; set; }
        public string RENAME_EXT { get; set; }
        public string SOURCE { get; set; }
        public string STEP { get; set; }
        public string INCLUDE_SUBDIRS { get; set; }
        public string FTP_USER { get; set; }
        public string DEBUG { get; set; }
        public string DIRECTORY { get; set; }
        public string FTP_MODE { get; set; }
        public string PASSWORD { get; set; }
        public string IP_ADDRESS { get; set; }
        public string SELLER { get; set; }
        public string INST_TYPE { get; set; }
        public Nullable<int> PORT_NUMBER { get; set; }
        public string X_ACCREDITATION { get; set; }
        public string X_REG_CARD_NUM { get; set; }
        public string X_INST_NAME { get; set; }
        public Nullable<System.DateTime> X_MANUFAC_DATE { get; set; }
        public string X_NOTES { get; set; }
        public string X_NUMBER_INVER { get; set; }
        public string X_PARTS { get; set; }
        public string X_PERIOD { get; set; }
        public string X_PROD_GROUP { get; set; }
        public string X_STATUS { get; set; }
        public Nullable<System.DateTime> DATA_ENTER { get; set; }
        public string STORE_IN_DB_FILE { get; set; }
        public string DB_FILE_PROMPT { get; set; }
        public string X_SI_TYPE { get; set; }
        public string X_SOFTWARE { get; set; }
        public string X_PM_CONTRACTOR { get; set; }
    }
}
