//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUM_SI_ATT
    {
        public string INSTRUMENTS { get; set; }
        public string INSTRUM_SI_ATT1 { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
