//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANS_TMP_FIELDS
    {
        public string TEMPLATE { get; set; }
        public string FIELD_NAME { get; set; }
        public string ENTRY_MODE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string FIELD_LABEL { get; set; }
        public string FORMULA { get; set; }
        public string ALLOW_USER_ENTRY { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string DATA_TYPE { get; set; }
        public string DEPENDS_ON { get; set; }
        public string GROUP_TITLE { get; set; }
    }
}
