//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GSO_METR_CHAR
    {
        public int N_COUNT { get; set; }
        public Nullable<int> INVENTORY_ITEM { get; set; }
        public string INVENTORY_ENTRY { get; set; }
        public string X_FOR_ITEM_ONLY { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string X_NAME { get; set; }
        public string X_VALUE { get; set; }
        public string X_UNITS { get; set; }
        public string X_CLASS { get; set; }
        public string X_UNITS_C { get; set; }
        public string X_NOTES { get; set; }
    }
}
