//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_ITEM
    {
        public int ITEM_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string LOCATION { get; set; }
        public string STOCK { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string UNITS { get; set; }
        public string INVENTORY_TYPE { get; set; }
        public string ALLOCATE_TO { get; set; }
        public string TEMPLATE { get; set; }
        public string PULL_TEMPLATE { get; set; }
        public string ADD_TEMPLATE { get; set; }
        public string ADJUST_TEMPLATE { get; set; }
        public string ENTRY_TEMPLATE { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<System.DateTime> T_EXPIRATION_DATE { get; set; }
        public string X_ACCREDITATION { get; set; }
        public string X_DEV { get; set; }
        public string X_GSO { get; set; }
        public string X_GSO_NAME { get; set; }
        public string X_GSO_NUM { get; set; }
        public string X_INDEX { get; set; }
        public string X_IS_GSO { get; set; }
        public string X_NORM_DOC { get; set; }
        public string X_PREPARATION_DOC { get; set; }
        public string X_NOTES { get; set; }
        public string X_PROD_GROUP { get; set; }
        public string X_STATUS { get; set; }
        public string X_USE { get; set; }
        public string INGREDIENT { get; set; }
        public string X_MANUFACTURER { get; set; }
        public string X_RECIPE { get; set; }
        public string ACTIVE { get; set; }
    }
}
