//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_ENTRY
    {
        public Nullable<int> ITEM_NUMBER { get; set; }
        public string ENTRY_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string UNITS { get; set; }
        public string INVENTORY_TYPE { get; set; }
        public string ALLOCATE_TO { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<int> STORAGE_LOC_NO { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string TEMPLATE { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public string ACTIVE { get; set; }
        public string FORMULATION { get; set; }
        public string LOT_NUMBER { get; set; }
        public string SUPPLIER { get; set; }
        public string DISPLAYED { get; set; }
        public int ITEM_ENTRY { get; set; }
        public Nullable<float> POTENCY { get; set; }
        public string X_BATCH { get; set; }
        public Nullable<System.DateTime> X_START_DATE { get; set; }
        public string X_QUALITY { get; set; }
        public string X_SUBSTANCE_FORM { get; set; }
        public string X_DOCUMENT { get; set; }
        public string X_EXPIRATION_TYPE { get; set; }
        public string LOCATION { get; set; }
        public Nullable<float> X_BALANCE_ON_1 { get; set; }
        public Nullable<float> X_NORM_DOC { get; set; }
        public Nullable<float> X_SOL_VOLUME { get; set; }
        public Nullable<float> X_INGR_NEED_QUANTITY { get; set; }
        public string X_INGR_NEED_UNITS { get; set; }
        public string X_SOL_CONSUMPTION { get; set; }
        public string X_PRIM { get; set; }
        public string X_NOTE { get; set; }
        public Nullable<float> X_ERROR { get; set; }
        public string X_FORMULATION { get; set; }
        public string INGREDIENT { get; set; }
        public string REAG_DRY_TYPE { get; set; }
        public Nullable<System.DateTime> X_BALANCE_DATE { get; set; }
        public string X_BALANCE_QUANTITY { get; set; }
    }
}
