//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_TRANS
    {
        public string ENTRY_CODE { get; set; }
        public string INVENTORY_ENTRY { get; set; }
        public Nullable<int> INVENTORY_ITEM { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string TRANSACTION_STATUS { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<System.DateTime> PLANNED_DATE { get; set; }
        public string TRANSACTION_BY { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXT_LINK { get; set; }
        public string TRANSACTION_COMMENT { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string ENTRY_NAME { get; set; }
        public string UNITS { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string OBJECT_ID { get; set; }
        public Nullable<int> X_INVENT_ANALYS_PULL { get; set; }
        public Nullable<int> X_INVENT_INFLOW { get; set; }
        public Nullable<int> X_INVENT_INFLOW_E { get; set; }
        public Nullable<int> X_INVENT_MOVE_REQ { get; set; }
        public Nullable<int> X_INVENT_MOVE_REQ_E { get; set; }
        public Nullable<int> X_INVENT_PULL { get; set; }
        public Nullable<int> X_INVENT_PULL_E { get; set; }
    }
}
