//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTIGATION
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXT_LINK { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string OWNER { get; set; }
        public string REVIEWED_BY { get; set; }
        public Nullable<System.DateTime> REVIEWED_ON { get; set; }
        public string CLOSED { get; set; }
        public string CLOSED_BY { get; set; }
        public Nullable<System.DateTime> CLOSED_ON { get; set; }
        public string TEMPLATE { get; set; }
        public string CONCLUSION { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string NOTES { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string USE_GROUP_LOGIN { get; set; }
        public string BATCH_TEMPLATE { get; set; }
        public string USE_GRID_LOGIN { get; set; }
        public string GROUP_NAME { get; set; }
        public string STATUS { get; set; }
        public string SIGNED { get; set; }
    }
}
