//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVEST_OBJECTS
    {
        public string INVESTIGATION { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string OBJECT_ID { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
