//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_IDEAL_TEMP
    {
        public string NAME { get; set; }
        public Nullable<double> HI_0_0 { get; set; }
        public Nullable<double> LO_0_0 { get; set; }
        public Nullable<double> HI_20_20 { get; set; }
        public Nullable<double> LO_20_20 { get; set; }
    }
}
