//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_PRESS
    {
        public string NAME { get; set; }
        public Nullable<double> Z_0 { get; set; }
        public Nullable<double> SQR_B_0 { get; set; }
        public Nullable<double> Z_20 { get; set; }
        public Nullable<double> SQR_B_20 { get; set; }
        public Nullable<double> MOL { get; set; }
    }
}
