//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABEL_LINE
    {
        public string PRINTER { get; set; }
        public Nullable<int> LINE_NUMBER { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string FIELD_TYPE { get; set; }
        public string BAR_CODE { get; set; }
        public string JUSTIFICATION { get; set; }
        public string LABEL { get; set; }
        public string FIELD { get; set; }
        public string VALUE { get; set; }
        public string FORMULA { get; set; }
        public Nullable<int> ENTRY_CODE { get; set; }
    }
}
