//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDAP_SERVER_MAPPING
    {
        public string LDAP_SERVER { get; set; }
        public string LDAP_FIELD { get; set; }
        public string LIMS_FIELD { get; set; }
    }
}
