//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENSE
    {
        public string CLIENT { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string ALLOCATED { get; set; }
        public string LOGIN_DISABLED { get; set; }
        public string RESTRICTED_USE { get; set; }
        public string WEB_SESSION { get; set; }
        public string ELN { get; set; }
    }
}
