//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class limsprodEntities : DbContext
    {
        public limsprodEntities()
            : base("name=limsprodEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESS_ENTRY> ACCESS_ENTRY { get; set; }
        public virtual DbSet<ACCESS_FUNCTION_IDS> ACCESS_FUNCTION_IDS { get; set; }
        public virtual DbSet<ACCESS_ROUTINES> ACCESS_ROUTINES { get; set; }
        public virtual DbSet<AD_HOC_COMPONENT> AD_HOC_COMPONENT { get; set; }
        public virtual DbSet<ADDRESS_BK_TMP_FLD> ADDRESS_BK_TMP_FLD { get; set; }
        public virtual DbSet<ADDRESS_BOOK> ADDRESS_BOOK { get; set; }
        public virtual DbSet<ADDRESS_BOOK_TEMP> ADDRESS_BOOK_TEMP { get; set; }
        public virtual DbSet<ALERT> ALERT { get; set; }
        public virtual DbSet<ANALYSIS> ANALYSIS { get; set; }
        public virtual DbSet<ANALYSIS_APPROVAL> ANALYSIS_APPROVAL { get; set; }
        public virtual DbSet<ANALYSIS_LIMITS> ANALYSIS_LIMITS { get; set; }
        public virtual DbSet<ANALYSIS_RULES> ANALYSIS_RULES { get; set; }
        public virtual DbSet<ANALYSIS_TYPES> ANALYSIS_TYPES { get; set; }
        public virtual DbSet<ANALYSIS_VARIATION> ANALYSIS_VARIATION { get; set; }
        public virtual DbSet<APPROVAL> APPROVAL { get; set; }
        public virtual DbSet<APPROVAL_DETAILS> APPROVAL_DETAILS { get; set; }
        public virtual DbSet<APPROVAL_GROUPS> APPROVAL_GROUPS { get; set; }
        public virtual DbSet<APPROVAL_ROLE> APPROVAL_ROLE { get; set; }
        public virtual DbSet<APPROVAL_ROUTING> APPROVAL_ROUTING { get; set; }
        public virtual DbSet<APPROVAL_STEPS> APPROVAL_STEPS { get; set; }
        public virtual DbSet<ARCHIVE_DOC> ARCHIVE_DOC { get; set; }
        public virtual DbSet<ARCHIVE_DOC_FILE> ARCHIVE_DOC_FILE { get; set; }
        public virtual DbSet<ARCHIVE_DOC_TYPES> ARCHIVE_DOC_TYPES { get; set; }
        public virtual DbSet<ARRAY_TAG_PROPS> ARRAY_TAG_PROPS { get; set; }
        public virtual DbSet<AUDIT_ESIG_EVENTS> AUDIT_ESIG_EVENTS { get; set; }
        public virtual DbSet<AUDIT_LOG_DATA> AUDIT_LOG_DATA { get; set; }
        public virtual DbSet<AUDIT_LOG_TRANSACTIONS> AUDIT_LOG_TRANSACTIONS { get; set; }
        public virtual DbSet<AUTOMATION_SCRIPT> AUTOMATION_SCRIPT { get; set; }
        public virtual DbSet<BASIC_ERROR_LOG> BASIC_ERROR_LOG { get; set; }
        public virtual DbSet<BASIC_SCHEDULER> BASIC_SCHEDULER { get; set; }
        public virtual DbSet<BATCH> BATCH { get; set; }
        public virtual DbSet<BATCH_ACTION> BATCH_ACTION { get; set; }
        public virtual DbSet<BATCH_ACTION_CALC> BATCH_ACTION_CALC { get; set; }
        public virtual DbSet<BATCH_ACTION_DEF> BATCH_ACTION_DEF { get; set; }
        public virtual DbSet<BATCH_AUDIT_CURRENT> BATCH_AUDIT_CURRENT { get; set; }
        public virtual DbSet<BATCH_AUDIT_LOG> BATCH_AUDIT_LOG { get; set; }
        public virtual DbSet<BATCH_AUDIT_OLD> BATCH_AUDIT_OLD { get; set; }
        public virtual DbSet<BATCH_AUDIT_RPT> BATCH_AUDIT_RPT { get; set; }
        public virtual DbSet<BATCH_CALC_VAR> BATCH_CALC_VAR { get; set; }
        public virtual DbSet<BATCH_CALCULATION> BATCH_CALCULATION { get; set; }
        public virtual DbSet<BATCH_COMP_CODES> BATCH_COMP_CODES { get; set; }
        public virtual DbSet<BATCH_COMPONENT> BATCH_COMPONENT { get; set; }
        public virtual DbSet<BATCH_HDR_TEMPLATE> BATCH_HDR_TEMPLATE { get; set; }
        public virtual DbSet<BATCH_HDR_TMP_FLDS> BATCH_HDR_TMP_FLDS { get; set; }
        public virtual DbSet<BATCH_ID_CONFIG> BATCH_ID_CONFIG { get; set; }
        public virtual DbSet<BATCH_LINK> BATCH_LINK { get; set; }
        public virtual DbSet<BATCH_OBJECTS> BATCH_OBJECTS { get; set; }
        public virtual DbSet<BATCH_PROTOCOL> BATCH_PROTOCOL { get; set; }
        public virtual DbSet<BATCH_RESULT> BATCH_RESULT { get; set; }
        public virtual DbSet<BATCH_STANDARD> BATCH_STANDARD { get; set; }
        public virtual DbSet<BATCH_STEPS> BATCH_STEPS { get; set; }
        public virtual DbSet<BATCH_TEMP_FIELDS> BATCH_TEMP_FIELDS { get; set; }
        public virtual DbSet<BATCH_TEMPLATE> BATCH_TEMPLATE { get; set; }
        public virtual DbSet<BROWSE_TAG_PROPS> BROWSE_TAG_PROPS { get; set; }
        public virtual DbSet<CALC_TRIGGER> CALC_TRIGGER { get; set; }
        public virtual DbSet<CALC_VARIABLES> CALC_VARIABLES { get; set; }
        public virtual DbSet<CALCULATION> CALCULATION { get; set; }
        public virtual DbSet<CALENDAR_SCHEDULE> CALENDAR_SCHEDULE { get; set; }
        public virtual DbSet<CALIB_HISTORY> CALIB_HISTORY { get; set; }
        public virtual DbSet<CANCELED_SAMPLE_LOG> CANCELED_SAMPLE_LOG { get; set; }
        public virtual DbSet<CHARGE_CODE> CHARGE_CODE { get; set; }
        public virtual DbSet<CHARGES> CHARGES { get; set; }
        public virtual DbSet<CHART_GROUPS> CHART_GROUPS { get; set; }
        public virtual DbSet<CHART_GROUPS_ENTRY> CHART_GROUPS_ENTRY { get; set; }
        public virtual DbSet<CHART_TEMPLATE> CHART_TEMPLATE { get; set; }
        public virtual DbSet<CHKSUM_FAILURE_LOG> CHKSUM_FAILURE_LOG { get; set; }
        public virtual DbSet<CM_INSTANCE> CM_INSTANCE { get; set; }
        public virtual DbSet<CODE_SNIPPETS> CODE_SNIPPETS { get; set; }
        public virtual DbSet<COMMON_NAME> COMMON_NAME { get; set; }
        public virtual DbSet<COMP_VARIATION> COMP_VARIATION { get; set; }
        public virtual DbSet<COMPONENT> COMPONENT { get; set; }
        public virtual DbSet<COMPONENT_CODES> COMPONENT_CODES { get; set; }
        public virtual DbSet<COMPONENT_FACTORS> COMPONENT_FACTORS { get; set; }
        public virtual DbSet<CONDITION> CONDITION { get; set; }
        public virtual DbSet<CONFIG_PACK_FILE> CONFIG_PACK_FILE { get; set; }
        public virtual DbSet<CONFIG_PACK_FUNCTION> CONFIG_PACK_FUNCTION { get; set; }
        public virtual DbSet<CONFIG_PACK_OBJECT> CONFIG_PACK_OBJECT { get; set; }
        public virtual DbSet<CONFIG_PACK_POST_SUB> CONFIG_PACK_POST_SUB { get; set; }
        public virtual DbSet<CONFIG_PACK_PRE_SUB> CONFIG_PACK_PRE_SUB { get; set; }
        public virtual DbSet<CONFIG_PACK_SQL> CONFIG_PACK_SQL { get; set; }
        public virtual DbSet<CONFIG_PACK_TABLE> CONFIG_PACK_TABLE { get; set; }
        public virtual DbSet<CONFIG_PACK_WINDOW> CONFIG_PACK_WINDOW { get; set; }
        public virtual DbSet<CONFIG_PACKAGE> CONFIG_PACKAGE { get; set; }
        public virtual DbSet<CONFIG_SYS> CONFIG_SYS { get; set; }
        public virtual DbSet<CONFIG_USER> CONFIG_USER { get; set; }
        public virtual DbSet<CONTACT> CONTACT { get; set; }
        public virtual DbSet<CONTACT_TEMP_FLDS> CONTACT_TEMP_FLDS { get; set; }
        public virtual DbSet<CONTACT_TEMP_GRPS> CONTACT_TEMP_GRPS { get; set; }
        public virtual DbSet<CONTACT_TEMPLATE> CONTACT_TEMPLATE { get; set; }
        public virtual DbSet<CONTAINER_TYPE> CONTAINER_TYPE { get; set; }
        public virtual DbSet<CONTCT_TMP_DSP_FLD> CONTCT_TMP_DSP_FLD { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<DATA_EXPLORER> DATA_EXPLORER { get; set; }
        public virtual DbSet<DATA_EXPLORER_FLDS> DATA_EXPLORER_FLDS { get; set; }
        public virtual DbSet<DATABASE_EVENTS> DATABASE_EVENTS { get; set; }
        public virtual DbSet<DAYLIGHT_SAVINGS> DAYLIGHT_SAVINGS { get; set; }
        public virtual DbSet<DB_DIRECTORY> DB_DIRECTORY { get; set; }
        public virtual DbSet<DB_FILES> DB_FILES { get; set; }
        public virtual DbSet<DB_SCRIPTS> DB_SCRIPTS { get; set; }
        public virtual DbSet<DISPLAY_FIELDS> DISPLAY_FIELDS { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<ESIG_LOG> ESIG_LOG { get; set; }
        public virtual DbSet<EVENTS> EVENTS { get; set; }
        public virtual DbSet<EXPIRATION_HISTORY> EXPIRATION_HISTORY { get; set; }
        public virtual DbSet<F25CERTIF> F25CERTIF { get; set; }
        public virtual DbSet<F25CERTIF_INDS> F25CERTIF_INDS { get; set; }
        public virtual DbSet<F25CNTRL_CNF> F25CNTRL_CNF { get; set; }
        public virtual DbSet<F25CNTRL_ITA> F25CNTRL_ITA { get; set; }
        public virtual DbSet<F25CNTRL_ITD> F25CNTRL_ITD { get; set; }
        public virtual DbSet<F25CNTRL_ITP> F25CNTRL_ITP { get; set; }
        public virtual DbSet<F25CNTRL_ITQ> F25CNTRL_ITQ { get; set; }
        public virtual DbSet<F25CNTRL_ITR> F25CNTRL_ITR { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR> F25CNTRL_PR_PAR { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR_AD> F25CNTRL_PR_PAR_AD { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR_ATT> F25CNTRL_PR_PAR_ATT { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR_CAL> F25CNTRL_PR_PAR_CAL { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR_DTL> F25CNTRL_PR_PAR_DTL { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR_SMPL> F25CNTRL_PR_PAR_SMPL { get; set; }
        public virtual DbSet<F25CNTRL_PR_PAR_STAB> F25CNTRL_PR_PAR_STAB { get; set; }
        public virtual DbSet<F25INS_ITC> F25INS_ITC { get; set; }
        public virtual DbSet<F25INS_ITD> F25INS_ITD { get; set; }
        public virtual DbSet<F25INS_ITR> F25INS_ITR { get; set; }
        public virtual DbSet<F25INSRT_PR_PAR> F25INSRT_PR_PAR { get; set; }
        public virtual DbSet<F25INSRT_PR_PAR_SMPL> F25INSRT_PR_PAR_SMPL { get; set; }
        public virtual DbSet<F25OPERCONTR> F25OPERCONTR { get; set; }
        public virtual DbSet<F25PRJ_QIND> F25PRJ_QIND { get; set; }
        public virtual DbSet<F25PROCESS> F25PROCESS { get; set; }
        public virtual DbSet<F25PROD> F25PROD { get; set; }
        public virtual DbSet<F25PRODQINDS> F25PRODQINDS { get; set; }
        public virtual DbSet<F25PRODQINDS_INDS> F25PRODQINDS_INDS { get; set; }
        public virtual DbSet<F25QINDS> F25QINDS { get; set; }
        public virtual DbSet<F25QINDS_INDS> F25QINDS_INDS { get; set; }
        public virtual DbSet<FACTORS> FACTORS { get; set; }
        public virtual DbSet<FIELD_MASTER> FIELD_MASTER { get; set; }
        public virtual DbSet<FLAG_TEMPLATE> FLAG_TEMPLATE { get; set; }
        public virtual DbSet<FLAG_TEMPLATE_FLDS> FLAG_TEMPLATE_FLDS { get; set; }
        public virtual DbSet<FLAGS> FLAGS { get; set; }
        public virtual DbSet<FLDR_ACTION_CALC> FLDR_ACTION_CALC { get; set; }
        public virtual DbSet<FLDR_ACTION_DEF> FLDR_ACTION_DEF { get; set; }
        public virtual DbSet<FLDR_TEMPLATE_FIELDS> FLDR_TEMPLATE_FIELDS { get; set; }
        public virtual DbSet<FOLDER> FOLDER { get; set; }
        public virtual DbSet<FOLDER_GROUP> FOLDER_GROUP { get; set; }
        public virtual DbSet<FOLDER_OBJECTS> FOLDER_OBJECTS { get; set; }
        public virtual DbSet<FOLDER_TEMPLATE> FOLDER_TEMPLATE { get; set; }
        public virtual DbSet<FORM_AUDIT_CURRENT> FORM_AUDIT_CURRENT { get; set; }
        public virtual DbSet<FORM_AUDIT_LOG> FORM_AUDIT_LOG { get; set; }
        public virtual DbSet<FORM_AUDIT_OLD> FORM_AUDIT_OLD { get; set; }
        public virtual DbSet<FORM_AUDIT_RPT> FORM_AUDIT_RPT { get; set; }
        public virtual DbSet<FORM_EXP_INGRED> FORM_EXP_INGRED { get; set; }
        public virtual DbSet<FORM_FLD_ATTRIBUTE> FORM_FLD_ATTRIBUTE { get; set; }
        public virtual DbSet<FORM_ID_CONFIG> FORM_ID_CONFIG { get; set; }
        public virtual DbSet<FORM_TEMP_FIELDS> FORM_TEMP_FIELDS { get; set; }
        public virtual DbSet<FORM_TEMP_GROUPS> FORM_TEMP_GROUPS { get; set; }
        public virtual DbSet<FORM_TEMP_SECTION> FORM_TEMP_SECTION { get; set; }
        public virtual DbSet<FORM_TEMPLATE> FORM_TEMPLATE { get; set; }
        public virtual DbSet<FORMAT_CALCULATION> FORMAT_CALCULATION { get; set; }
        public virtual DbSet<FORMULA_ID_CNFG> FORMULA_ID_CNFG { get; set; }
        public virtual DbSet<FORMULA_INGREDIENT> FORMULA_INGREDIENT { get; set; }
        public virtual DbSet<FORMULA_TMP_FIELDS> FORMULA_TMP_FIELDS { get; set; }
        public virtual DbSet<FORMULA_TMP_GRPS> FORMULA_TMP_GRPS { get; set; }
        public virtual DbSet<FORMULATION> FORMULATION { get; set; }
        public virtual DbSet<FORMULATION_TEMP> FORMULATION_TEMP { get; set; }
        public virtual DbSet<GROUP_ENTRY> GROUP_ENTRY { get; set; }
        public virtual DbSet<HAZARD> HAZARD { get; set; }
        public virtual DbSet<HISTOGRAM> HISTOGRAM { get; set; }
        public virtual DbSet<HOLIDAY_SCHED_ENTRY> HOLIDAY_SCHED_ENTRY { get; set; }
        public virtual DbSet<HOLIDAY_SCHEDULE> HOLIDAY_SCHEDULE { get; set; }
        public virtual DbSet<HTML_FILES> HTML_FILES { get; set; }
        public virtual DbSet<ICON_RULES> ICON_RULES { get; set; }
        public virtual DbSet<ID_CONFIGURATION> ID_CONFIGURATION { get; set; }
        public virtual DbSet<INCREMENTS> INCREMENTS { get; set; }
        public virtual DbSet<INFO_RULES> INFO_RULES { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENT { get; set; }
        public virtual DbSet<INGREDIENT_LOT> INGREDIENT_LOT { get; set; }
        public virtual DbSet<INST_EVENT_TMP> INST_EVENT_TMP { get; set; }
        public virtual DbSet<INST_EVNT_TMP_FLDS> INST_EVNT_TMP_FLDS { get; set; }
        public virtual DbSet<INST_TMP_FIELDS> INST_TMP_FIELDS { get; set; }
        public virtual DbSet<INSTRUM_SI_ATT> INSTRUM_SI_ATT { get; set; }
        public virtual DbSet<INSTRUMENT_APPROVAL> INSTRUMENT_APPROVAL { get; set; }
        public virtual DbSet<INSTRUMENT_LOG> INSTRUMENT_LOG { get; set; }
        public virtual DbSet<INSTRUMENT_TMP> INSTRUMENT_TMP { get; set; }
        public virtual DbSet<INSTRUMENTS> INSTRUMENTS { get; set; }
        public virtual DbSet<INV_AUDIT_CURRENT> INV_AUDIT_CURRENT { get; set; }
        public virtual DbSet<INV_AUDIT_OLD> INV_AUDIT_OLD { get; set; }
        public virtual DbSet<INV_ENTRY_ID_CONFIG> INV_ENTRY_ID_CONFIG { get; set; }
        public virtual DbSet<INV_ENTRY_TMP> INV_ENTRY_TMP { get; set; }
        public virtual DbSet<INV_ENTRY_TMP_FIELDS> INV_ENTRY_TMP_FIELDS { get; set; }
        public virtual DbSet<INV_ENTRY_TMP_GROUPS> INV_ENTRY_TMP_GROUPS { get; set; }
        public virtual DbSet<INV_FILTER_FIELDS> INV_FILTER_FIELDS { get; set; }
        public virtual DbSet<INV_FLTER_DSPLY_FLDS> INV_FLTER_DSPLY_FLDS { get; set; }
        public virtual DbSet<INV_GSO_METR_CHAR> INV_GSO_METR_CHAR { get; set; }
        public virtual DbSet<INV_TRANS_TMP> INV_TRANS_TMP { get; set; }
        public virtual DbSet<INV_TRANS_TMP_FIELDS> INV_TRANS_TMP_FIELDS { get; set; }
        public virtual DbSet<INV_TRANS_TMP_GROUPS> INV_TRANS_TMP_GROUPS { get; set; }
        public virtual DbSet<INVENTORY_AUDIT_RPT> INVENTORY_AUDIT_RPT { get; set; }
        public virtual DbSet<INVENTORY_ENTRY> INVENTORY_ENTRY { get; set; }
        public virtual DbSet<INVENTORY_FILTER> INVENTORY_FILTER { get; set; }
        public virtual DbSet<INVENTORY_ID_CONFIG> INVENTORY_ID_CONFIG { get; set; }
        public virtual DbSet<INVENTORY_ITEM> INVENTORY_ITEM { get; set; }
        public virtual DbSet<INVENTORY_LOCATION> INVENTORY_LOCATION { get; set; }
        public virtual DbSet<INVENTORY_LOG> INVENTORY_LOG { get; set; }
        public virtual DbSet<INVENTORY_TMP> INVENTORY_TMP { get; set; }
        public virtual DbSet<INVENTORY_TMP_FIELDS> INVENTORY_TMP_FIELDS { get; set; }
        public virtual DbSet<INVENTORY_TMP_GROUPS> INVENTORY_TMP_GROUPS { get; set; }
        public virtual DbSet<INVENTORY_TRANS> INVENTORY_TRANS { get; set; }
        public virtual DbSet<INVEST_AUDIT_CURRENT> INVEST_AUDIT_CURRENT { get; set; }
        public virtual DbSet<INVEST_AUDIT_LOG> INVEST_AUDIT_LOG { get; set; }
        public virtual DbSet<INVEST_AUDIT_OLD> INVEST_AUDIT_OLD { get; set; }
        public virtual DbSet<INVEST_AUDIT_RPT> INVEST_AUDIT_RPT { get; set; }
        public virtual DbSet<INVEST_EVENTS> INVEST_EVENTS { get; set; }
        public virtual DbSet<INVEST_ID_CONFIG> INVEST_ID_CONFIG { get; set; }
        public virtual DbSet<INVEST_OBJECTS> INVEST_OBJECTS { get; set; }
        public virtual DbSet<INVEST_TMP_FIELDS> INVEST_TMP_FIELDS { get; set; }
        public virtual DbSet<INVEST_TMP_GROUPS> INVEST_TMP_GROUPS { get; set; }
        public virtual DbSet<INVESTIGATION> INVESTIGATION { get; set; }
        public virtual DbSet<INVESTIGATION_TMP> INVESTIGATION_TMP { get; set; }
        public virtual DbSet<ITEM_TEMPLATE> ITEM_TEMPLATE { get; set; }
        public virtual DbSet<ITEM_TEMPLATE_FLDS> ITEM_TEMPLATE_FLDS { get; set; }
        public virtual DbSet<K_IDEAL_TEMP> K_IDEAL_TEMP { get; set; }
        public virtual DbSet<K_PRESS> K_PRESS { get; set; }
        public virtual DbSet<LABEL_LINE> LABEL_LINE { get; set; }
        public virtual DbSet<LABEL_PRINTER> LABEL_PRINTER { get; set; }
        public virtual DbSet<LABSTATION> LABSTATION { get; set; }
        public virtual DbSet<LAST_INST_DATA_LOG> LAST_INST_DATA_LOG { get; set; }
        public virtual DbSet<LDAP_SERVER_MAPPING> LDAP_SERVER_MAPPING { get; set; }
        public virtual DbSet<LDAP_SERVERS> LDAP_SERVERS { get; set; }
        public virtual DbSet<LICENSE> LICENSE { get; set; }
        public virtual DbSet<LICENSE_show> LICENSE_show { get; set; }
        public virtual DbSet<LICENSE_WEB> LICENSE_WEB { get; set; }
        public virtual DbSet<LIMS_CONSTANTS> LIMS_CONSTANTS { get; set; }
        public virtual DbSet<LIMS_HTML_NOTES> LIMS_HTML_NOTES { get; set; }
        public virtual DbSet<LIMS_MESSAGE> LIMS_MESSAGE { get; set; }
        public virtual DbSet<LIMS_NOTES> LIMS_NOTES { get; set; }
        public virtual DbSet<LIMS_USERS> LIMS_USERS { get; set; }
        public virtual DbSet<LIST> LIST { get; set; }
        public virtual DbSet<LIST_ENTRY> LIST_ENTRY { get; set; }
        public virtual DbSet<LOCATION> LOCATION { get; set; }
        public virtual DbSet<LOGIN_SCHEDULER> LOGIN_SCHEDULER { get; set; }
        public virtual DbSet<LOT> LOT { get; set; }
        public virtual DbSet<LOT_AUDIT_CURRENT> LOT_AUDIT_CURRENT { get; set; }
        public virtual DbSet<LOT_AUDIT_LOG> LOT_AUDIT_LOG { get; set; }
        public virtual DbSet<LOT_AUDIT_OLD> LOT_AUDIT_OLD { get; set; }
        public virtual DbSet<LOT_AUDIT_RPT> LOT_AUDIT_RPT { get; set; }
        public virtual DbSet<LOT_EVENTS> LOT_EVENTS { get; set; }
        public virtual DbSet<LOT_ID_CONFIG> LOT_ID_CONFIG { get; set; }
        public virtual DbSet<LOT_RESULT> LOT_RESULT { get; set; }
        public virtual DbSet<LOT_SAMPLING_POINT> LOT_SAMPLING_POINT { get; set; }
        public virtual DbSet<LOT_SOURCES> LOT_SOURCES { get; set; }
        public virtual DbSet<LOT_TEMP_FIELDS> LOT_TEMP_FIELDS { get; set; }
        public virtual DbSet<LOT_TEMP_GROUPS> LOT_TEMP_GROUPS { get; set; }
        public virtual DbSet<LOT_TEMPLATE> LOT_TEMPLATE { get; set; }
        public virtual DbSet<LS_JOBS> LS_JOBS { get; set; }
        public virtual DbSet<LS_SAMPLES> LS_SAMPLES { get; set; }
        public virtual DbSet<LS_TEMPLATES> LS_TEMPLATES { get; set; }
        public virtual DbSet<MENU_ROUTINE> MENU_ROUTINE { get; set; }
        public virtual DbSet<MENUS> MENUS { get; set; }
        public virtual DbSet<NOTEBOOK> NOTEBOOK { get; set; }
        public virtual DbSet<NOTEBOOK_REF> NOTEBOOK_REF { get; set; }
        public virtual DbSet<OBJ_GRP_ID_CONFIG> OBJ_GRP_ID_CONFIG { get; set; }
        public virtual DbSet<OBJ_GRP_TEMPLATE> OBJ_GRP_TEMPLATE { get; set; }
        public virtual DbSet<OBJECT_GROUP> OBJECT_GROUP { get; set; }
        public virtual DbSet<OBJECT_GROUP_GRP> OBJECT_GROUP_GRP { get; set; }
        public virtual DbSet<OBJECT_GROUP_OBJS> OBJECT_GROUP_OBJS { get; set; }
        public virtual DbSet<ORDER_AUDIT_CURRENT> ORDER_AUDIT_CURRENT { get; set; }
        public virtual DbSet<ORDER_AUDIT_LOG> ORDER_AUDIT_LOG { get; set; }
        public virtual DbSet<ORDER_AUDIT_OLD> ORDER_AUDIT_OLD { get; set; }
        public virtual DbSet<ORDER_AUDIT_RPT> ORDER_AUDIT_RPT { get; set; }
        public virtual DbSet<ORDER_ENTRY> ORDER_ENTRY { get; set; }
        public virtual DbSet<ORDER_FIELD_ATTRIB> ORDER_FIELD_ATTRIB { get; set; }
        public virtual DbSet<ORDER_ID_CONFIG> ORDER_ID_CONFIG { get; set; }
        public virtual DbSet<ORDER_TEMP_FIELDS> ORDER_TEMP_FIELDS { get; set; }
        public virtual DbSet<ORDER_TEMP_GROUPS> ORDER_TEMP_GROUPS { get; set; }
        public virtual DbSet<ORDER_TEMPLATE> ORDER_TEMPLATE { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<PARSING_FORMULA> PARSING_FORMULA { get; set; }
        public virtual DbSet<PARSING_SCRIPTS> PARSING_SCRIPTS { get; set; }
        public virtual DbSet<PASSWORD_HISTORY> PASSWORD_HISTORY { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PERSON_LINKING> PERSON_LINKING { get; set; }
        public virtual DbSet<PIMS> PIMS { get; set; }
        public virtual DbSet<PIMS_ANALYZES_NAMES> PIMS_ANALYZES_NAMES { get; set; }
        public virtual DbSet<PIMS_ANALYZES_NAMES_REL> PIMS_ANALYZES_NAMES_REL { get; set; }
        public virtual DbSet<PIMS_LIMS_Product> PIMS_LIMS_Product { get; set; }
        public virtual DbSet<PIMS_RESULT> PIMS_RESULT { get; set; }
        public virtual DbSet<PLOT15> PLOT15 { get; set; }
        public virtual DbSet<PLOT20> PLOT20 { get; set; }
        public virtual DbSet<PM_HISTORY> PM_HISTORY { get; set; }
        public virtual DbSet<PROC_SCHED_PARENT> PROC_SCHED_PARENT { get; set; }
        public virtual DbSet<PROCESS_SCHEDULE> PROCESS_SCHEDULE { get; set; }
        public virtual DbSet<PROCESS_UNIT> PROCESS_UNIT { get; set; }
        public virtual DbSet<PROD_FILTER_FIELDS> PROD_FILTER_FIELDS { get; set; }
        public virtual DbSet<PROD_GRADE_STAGE> PROD_GRADE_STAGE { get; set; }
        public virtual DbSet<PROD_TEMP_FIELDS> PROD_TEMP_FIELDS { get; set; }
        public virtual DbSet<PROD_TEMP_GROUPS> PROD_TEMP_GROUPS { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_FILTER> Product_FILTER { get; set; }
        public virtual DbSet<Product_GRADE> Product_GRADE { get; set; }
        public virtual DbSet<Product_HISTORY> Product_HISTORY { get; set; }
        public virtual DbSet<Product_SPEC> Product_SPEC { get; set; }
        public virtual DbSet<Product_TEMPLATE> Product_TEMPLATE { get; set; }
        public virtual DbSet<PROJ_AUDIT_CURRENT> PROJ_AUDIT_CURRENT { get; set; }
        public virtual DbSet<PROJ_AUDIT_OLD> PROJ_AUDIT_OLD { get; set; }
        public virtual DbSet<PROJ_FILTER_FIELDS> PROJ_FILTER_FIELDS { get; set; }
        public virtual DbSet<PROJ_TEMP_GROUPS> PROJ_TEMP_GROUPS { get; set; }
        public virtual DbSet<PROJECT> PROJECT { get; set; }
        public virtual DbSet<PROJECT_AUDIT_LOG> PROJECT_AUDIT_LOG { get; set; }
        public virtual DbSet<PROJECT_AUDIT_RPT> PROJECT_AUDIT_RPT { get; set; }
        public virtual DbSet<PROJECT_CALC_VAR> PROJECT_CALC_VAR { get; set; }
        public virtual DbSet<PROJECT_CALCULATION> PROJECT_CALCULATION { get; set; }
        public virtual DbSet<PROJECT_COMP_CODES> PROJECT_COMP_CODES { get; set; }
        public virtual DbSet<PROJECT_COMPONENT> PROJECT_COMPONENT { get; set; }
        public virtual DbSet<PROJECT_FILTER> PROJECT_FILTER { get; set; }
        public virtual DbSet<PROJECT_ID_CONFIG> PROJECT_ID_CONFIG { get; set; }
        public virtual DbSet<PROJECT_RESULT> PROJECT_RESULT { get; set; }
        public virtual DbSet<PROJECT_TEMP_FIELDS> PROJECT_TEMP_FIELDS { get; set; }
        public virtual DbSet<PROJECT_TEMPLATE> PROJECT_TEMPLATE { get; set; }
        public virtual DbSet<PROMPT_TAG_PROPS> PROMPT_TAG_PROPS { get; set; }
        public virtual DbSet<PROT_AUDIT_CURRENT> PROT_AUDIT_CURRENT { get; set; }
        public virtual DbSet<PROT_AUDIT_OLD> PROT_AUDIT_OLD { get; set; }
        public virtual DbSet<PROTOCOL_AUDIT_RPT> PROTOCOL_AUDIT_RPT { get; set; }
        public virtual DbSet<PSWD_FAILURE_LOG> PSWD_FAILURE_LOG { get; set; }
        public virtual DbSet<QC_SAMPLES> QC_SAMPLES { get; set; }
        public virtual DbSet<QUERY_TAG> QUERY_TAG { get; set; }
        public virtual DbSet<QUERY_TAG_PROPS> QUERY_TAG_PROPS { get; set; }
        public virtual DbSet<QUEUE_OBJECTS> QUEUE_OBJECTS { get; set; }
        public virtual DbSet<RECENT_TASKS> RECENT_TASKS { get; set; }
        public virtual DbSet<RECIPE> RECIPE { get; set; }
        public virtual DbSet<RECIPE_EXP_INGRED> RECIPE_EXP_INGRED { get; set; }
        public virtual DbSet<RECIPE_ID_CNFG> RECIPE_ID_CNFG { get; set; }
        public virtual DbSet<RECIPE_INGREDIENT> RECIPE_INGREDIENT { get; set; }
        public virtual DbSet<RECIPE_TEMP_FIELDS> RECIPE_TEMP_FIELDS { get; set; }
        public virtual DbSet<RECIPE_TEMP_GRPS> RECIPE_TEMP_GRPS { get; set; }
        public virtual DbSet<RECIPE_TEMPLATE> RECIPE_TEMPLATE { get; set; }
        public virtual DbSet<REGRESSION> REGRESSION { get; set; }
        public virtual DbSet<REPORT_OBJECTS> REPORT_OBJECTS { get; set; }
        public virtual DbSet<REPORT_SCHEDULER> REPORT_SCHEDULER { get; set; }
        public virtual DbSet<REPORT_WIZARD> REPORT_WIZARD { get; set; }
        public virtual DbSet<REPORTS> REPORTS { get; set; }
        public virtual DbSet<RESULT> RESULT { get; set; }
        public virtual DbSet<RESULT_SPEC> RESULT_SPEC { get; set; }
        public virtual DbSet<RUN_CHART> RUN_CHART { get; set; }
        public virtual DbSet<SAMP_TEMP_GROUPS> SAMP_TEMP_GROUPS { get; set; }
        public virtual DbSet<SAMPLE> SAMPLE { get; set; }
        public virtual DbSet<SAMPLE_ACTION> SAMPLE_ACTION { get; set; }
        public virtual DbSet<SAMPLE_AUDIT_CURRENT> SAMPLE_AUDIT_CURRENT { get; set; }
        public virtual DbSet<SAMPLE_AUDIT_LOG> SAMPLE_AUDIT_LOG { get; set; }
        public virtual DbSet<SAMPLE_AUDIT_OLD> SAMPLE_AUDIT_OLD { get; set; }
        public virtual DbSet<SAMPLE_AUDIT_RPT> SAMPLE_AUDIT_RPT { get; set; }
        public virtual DbSet<SAMPLE_DISP_ENTRY> SAMPLE_DISP_ENTRY { get; set; }
        public virtual DbSet<SAMPLE_DISP_FLDS> SAMPLE_DISP_FLDS { get; set; }
        public virtual DbSet<SAMPLE_FILTER> SAMPLE_FILTER { get; set; }
        public virtual DbSet<SAMPLE_FILTER_FIELDS> SAMPLE_FILTER_FIELDS { get; set; }
        public virtual DbSet<SAMPLE_PLAN> SAMPLE_PLAN { get; set; }
        public virtual DbSet<SAMPLE_PLAN_ENTRY> SAMPLE_PLAN_ENTRY { get; set; }
        public virtual DbSet<SAMPLE_RULES> SAMPLE_RULES { get; set; }
        public virtual DbSet<SAMPLE_TEMPLATE> SAMPLE_TEMPLATE { get; set; }
        public virtual DbSet<SAMPLING_POINT> SAMPLING_POINT { get; set; }
        public virtual DbSet<SCHED_TYPE_TEMP> SCHED_TYPE_TEMP { get; set; }
        public virtual DbSet<SCHED_TYPE_TMP_FLD> SCHED_TYPE_TMP_FLD { get; set; }
        public virtual DbSet<SCHEDULE_ENTRY> SCHEDULE_ENTRY { get; set; }
        public virtual DbSet<SCHEDULER> SCHEDULER { get; set; }
        public virtual DbSet<SEARCH_TEMP_FLDS> SEARCH_TEMP_FLDS { get; set; }
        public virtual DbSet<SEARCH_TEMP_GRPS> SEARCH_TEMP_GRPS { get; set; }
        public virtual DbSet<SEARCH_TEMPLATE> SEARCH_TEMPLATE { get; set; }
        public virtual DbSet<SEASON> SEASON { get; set; }
        public virtual DbSet<SELLER_INST> SELLER_INST { get; set; }
        public virtual DbSet<SERVER_ACTION> SERVER_ACTION { get; set; }
        public virtual DbSet<SNAPSHOT> SNAPSHOT { get; set; }
        public virtual DbSet<STANDARD_REAGENT> STANDARD_REAGENT { get; set; }
        public virtual DbSet<STATUS_RULES> STATUS_RULES { get; set; }
        public virtual DbSet<STD_ID_CONFIG> STD_ID_CONFIG { get; set; }
        public virtual DbSet<STD_REAG_TEMP> STD_REAG_TEMP { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<STORED_QUERY> STORED_QUERY { get; set; }
        public virtual DbSet<STYLE_LIST> STYLE_LIST { get; set; }
        public virtual DbSet<SUBROUTINE> SUBROUTINE { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
        public virtual DbSet<T_TEST_METHOD> T_TEST_METHOD { get; set; }
        public virtual DbSet<T_TEST_METHOD_ENTRY> T_TEST_METHOD_ENTRY { get; set; }
        public virtual DbSet<T_TEST_METHOD_INV> T_TEST_METHOD_INV { get; set; }
        public virtual DbSet<T_TEST_METHOD_INV_E> T_TEST_METHOD_INV_E { get; set; }
        public virtual DbSet<TABLE_AUDIT_CURRENT> TABLE_AUDIT_CURRENT { get; set; }
        public virtual DbSet<TABLE_AUDIT_LOG> TABLE_AUDIT_LOG { get; set; }
        public virtual DbSet<TABLE_AUDIT_OLD> TABLE_AUDIT_OLD { get; set; }
        public virtual DbSet<TABLE_AUDIT_RPT> TABLE_AUDIT_RPT { get; set; }
        public virtual DbSet<TABLE_DRILLDOWN> TABLE_DRILLDOWN { get; set; }
        public virtual DbSet<TABLE_FORMAT> TABLE_FORMAT { get; set; }
        public virtual DbSet<TABLE_LIST_DETAIL> TABLE_LIST_DETAIL { get; set; }
        public virtual DbSet<TABLE_LIST_HEADER> TABLE_LIST_HEADER { get; set; }
        public virtual DbSet<TABLE_MASTER> TABLE_MASTER { get; set; }
        public virtual DbSet<TABLE_TEMP_FIELDS> TABLE_TEMP_FIELDS { get; set; }
        public virtual DbSet<TABLE_TEMP_GROUPS> TABLE_TEMP_GROUPS { get; set; }
        public virtual DbSet<TABLE_TEMPLATE> TABLE_TEMPLATE { get; set; }
        public virtual DbSet<TEMPLATE_FIELDS> TEMPLATE_FIELDS { get; set; }
        public virtual DbSet<TEST> TEST { get; set; }
        public virtual DbSet<TEST_ACTION> TEST_ACTION { get; set; }
        public virtual DbSet<TEST_DISP_ENTRY> TEST_DISP_ENTRY { get; set; }
        public virtual DbSet<TEST_DISP_FLDS> TEST_DISP_FLDS { get; set; }
        public virtual DbSet<TEST_EVENTS> TEST_EVENTS { get; set; }
        public virtual DbSet<TEST_LIST> TEST_LIST { get; set; }
        public virtual DbSet<TEST_LIST_COMP> TEST_LIST_COMP { get; set; }
        public virtual DbSet<TEST_LIST_ENTRY> TEST_LIST_ENTRY { get; set; }
        public virtual DbSet<TEST_LOCATION> TEST_LOCATION { get; set; }
        public virtual DbSet<TEST_TEMP_FIELDS> TEST_TEMP_FIELDS { get; set; }
        public virtual DbSet<TEST_TEMPLATE> TEST_TEMPLATE { get; set; }
        public virtual DbSet<TIMEPOINT> TIMEPOINT { get; set; }
        public virtual DbSet<TMP> TMP { get; set; }
        public virtual DbSet<TOOLBAR> TOOLBAR { get; set; }
        public virtual DbSet<UNITS> UNITS { get; set; }
        public virtual DbSet<UNRESOLVED_TESTS> UNRESOLVED_TESTS { get; set; }
        public virtual DbSet<USER_ANALYSIS_LOG> USER_ANALYSIS_LOG { get; set; }
        public virtual DbSet<USER_DIALOG_TEMP> USER_DIALOG_TEMP { get; set; }
        public virtual DbSet<USER_DLG_MENUS> USER_DLG_MENUS { get; set; }
        public virtual DbSet<USER_DLG_TMP_FLDS> USER_DLG_TMP_FLDS { get; set; }
        public virtual DbSet<USER_DLG_TMP_GRPS> USER_DLG_TMP_GRPS { get; set; }
        public virtual DbSet<USER_INSTRUMENT_LOG> USER_INSTRUMENT_LOG { get; set; }
        public virtual DbSet<USER_PROGRAMS> USER_PROGRAMS { get; set; }
        public virtual DbSet<USER_ROLE> USER_ROLE { get; set; }
        public virtual DbSet<VARIABLE_CHART> VARIABLE_CHART { get; set; }
        public virtual DbSet<VENDOR> VENDOR { get; set; }
        public virtual DbSet<VERSIONS> VERSIONS { get; set; }
        public virtual DbSet<VISUAL_WORKFLOW> VISUAL_WORKFLOW { get; set; }
        public virtual DbSet<WEB_FUNCTION> WEB_FUNCTION { get; set; }
        public virtual DbSet<WEB_SUBROUTINE> WEB_SUBROUTINE { get; set; }
        public virtual DbSet<WORKFLOW_DETAIL> WORKFLOW_DETAIL { get; set; }
        public virtual DbSet<WORKSHEET> WORKSHEET { get; set; }
        public virtual DbSet<WORKSHEET_DATA> WORKSHEET_DATA { get; set; }
        public virtual DbSet<WORKSHEET_ID_CNFG> WORKSHEET_ID_CNFG { get; set; }
        public virtual DbSet<WORKSHEET_OBJECTS> WORKSHEET_OBJECTS { get; set; }
        public virtual DbSet<WORKSHEET_TEMPLATE> WORKSHEET_TEMPLATE { get; set; }
        public virtual DbSet<WORKSHEET_TMP_FLDS> WORKSHEET_TMP_FLDS { get; set; }
        public virtual DbSet<X_ACCRED_DOCS> X_ACCRED_DOCS { get; set; }
        public virtual DbSet<X_ACCRED_DOCS_ENTRY> X_ACCRED_DOCS_ENTRY { get; set; }
        public virtual DbSet<X_ANALYSIS_REAGENT> X_ANALYSIS_REAGENT { get; set; }
        public virtual DbSet<X_ATT_METHOD> X_ATT_METHOD { get; set; }
        public virtual DbSet<X_DAV_NACL> X_DAV_NACL { get; set; }
        public virtual DbSet<X_DAVNASPAR> X_DAVNASPAR { get; set; }
        public virtual DbSet<X_DEV> X_DEV { get; set; }
        public virtual DbSet<X_DUTY_TYPE> X_DUTY_TYPE { get; set; }
        public virtual DbSet<X_FOREIGN_STAFF> X_FOREIGN_STAFF { get; set; }
        public virtual DbSet<X_FORREPORTS> X_FORREPORTS { get; set; }
        public virtual DbSet<X_G_TABLE> X_G_TABLE { get; set; }
        public virtual DbSet<X_GAZ_PLOT> X_GAZ_PLOT { get; set; }
        public virtual DbSet<X_GLK> X_GLK { get; set; }
        public virtual DbSet<X_GLK_ENTRY> X_GLK_ENTRY { get; set; }
        public virtual DbSet<X_GR_SER_H> X_GR_SER_H { get; set; }
        public virtual DbSet<X_GR_TABLE> X_GR_TABLE { get; set; }
        public virtual DbSet<X_GSO> X_GSO { get; set; }
        public virtual DbSet<X_GSO_MET_CHAR> X_GSO_MET_CHAR { get; set; }
        public virtual DbSet<X_INSTR_ATT_DOC> X_INSTR_ATT_DOC { get; set; }
        public virtual DbSet<X_INSTR_ATT_MET> X_INSTR_ATT_MET { get; set; }
        public virtual DbSet<X_INSTR_CONDITIONS> X_INSTR_CONDITIONS { get; set; }
        public virtual DbSet<X_INSTR_PM_PLAN> X_INSTR_PM_PLAN { get; set; }
        public virtual DbSet<X_INSTR_REG_CARD> X_INSTR_REG_CARD { get; set; }
        public virtual DbSet<X_INSTR_RESEARCH_OBJ> X_INSTR_RESEARCH_OBJ { get; set; }
        public virtual DbSet<X_INSTR_SI_TYPE_DOC> X_INSTR_SI_TYPE_DOC { get; set; }
        public virtual DbSet<X_INSTR_SI_TYPES> X_INSTR_SI_TYPES { get; set; }
        public virtual DbSet<X_INSTR_TECH_CHAR> X_INSTR_TECH_CHAR { get; set; }
        public virtual DbSet<X_INSTR_TEST_TYPE> X_INSTR_TEST_TYPE { get; set; }
        public virtual DbSet<X_INVENT_ANALYS_PULL> X_INVENT_ANALYS_PULL { get; set; }
        public virtual DbSet<X_INVENT_INFLOW> X_INVENT_INFLOW { get; set; }
        public virtual DbSet<X_INVENT_INFLOW_E> X_INVENT_INFLOW_E { get; set; }
        public virtual DbSet<X_INVENT_MOVE_REQ> X_INVENT_MOVE_REQ { get; set; }
        public virtual DbSet<X_INVENT_MOVE_REQ_E> X_INVENT_MOVE_REQ_E { get; set; }
        public virtual DbSet<X_INVENT_PULL> X_INVENT_PULL { get; set; }
        public virtual DbSet<X_INVENT_PULL_E> X_INVENT_PULL_E { get; set; }
        public virtual DbSet<X_IQC_METROLOG_CHAR> X_IQC_METROLOG_CHAR { get; set; }
        public virtual DbSet<X_KOD_OKP> X_KOD_OKP { get; set; }
        public virtual DbSet<X_KOFF> X_KOFF { get; set; }
        public virtual DbSet<X_KSM> X_KSM { get; set; }
        public virtual DbSet<X_KSM_ENTRY> X_KSM_ENTRY { get; set; }
        public virtual DbSet<X_LAB_INFO> X_LAB_INFO { get; set; }
        public virtual DbSet<X_LAB_INFO_DEP> X_LAB_INFO_DEP { get; set; }
        public virtual DbSet<X_LAB_INFO_PROD> X_LAB_INFO_PROD { get; set; }
        public virtual DbSet<X_LOGIN_USER_LOG> X_LOGIN_USER_LOG { get; set; }
        public virtual DbSet<X_MAINTENANCE_PLAN> X_MAINTENANCE_PLAN { get; set; }
        public virtual DbSet<X_MENUS> X_MENUS { get; set; }
        public virtual DbSet<X_MENUS_ENTRY> X_MENUS_ENTRY { get; set; }
        public virtual DbSet<X_MENUS_SUB_ENTRY> X_MENUS_SUB_ENTRY { get; set; }
        public virtual DbSet<X_MM> X_MM { get; set; }
        public virtual DbSet<X_PASSPORT_TEMPLATES> X_PASSPORT_TEMPLATES { get; set; }
        public virtual DbSet<X_pCNO3> X_pCNO3 { get; set; }
        public virtual DbSet<X_PERIOD_QUALITY> X_PERIOD_QUALITY { get; set; }
        public virtual DbSet<X_PERIOD_QUALITY_ANA> X_PERIOD_QUALITY_ANA { get; set; }
        public virtual DbSet<X_PROD_CERTS> X_PROD_CERTS { get; set; }
        public virtual DbSet<X_Product_PROC_UNIT> X_Product_PROC_UNIT { get; set; }
        public virtual DbSet<X_ROOMS> X_ROOMS { get; set; }
        public virtual DbSet<X_SEND_MAIL> X_SEND_MAIL { get; set; }
        public virtual DbSet<X_SVNIINP_DOC> X_SVNIINP_DOC { get; set; }
        public virtual DbSet<X_SVNIINP_ENTRY> X_SVNIINP_ENTRY { get; set; }
        public virtual DbSet<X_T_TABLE> X_T_TABLE { get; set; }
        public virtual DbSet<X_TRAININGS> X_TRAININGS { get; set; }
        public virtual DbSet<X_UNIT_RPT_ANALYSIS> X_UNIT_RPT_ANALYSIS { get; set; }
        public virtual DbSet<X_UNIT_RPT_COMPONENT> X_UNIT_RPT_COMPONENT { get; set; }
        public virtual DbSet<X_UNIT_RPT_INFO> X_UNIT_RPT_INFO { get; set; }
        public virtual DbSet<X_UNIT_RPT_ROW> X_UNIT_RPT_ROW { get; set; }
        public virtual DbSet<X_USER_CONFIG> X_USER_CONFIG { get; set; }
        public virtual DbSet<X_USER_EDU_CHILD> X_USER_EDU_CHILD { get; set; }
        public virtual DbSet<X_USER_FUNC_CHILD> X_USER_FUNC_CHILD { get; set; }
        public virtual DbSet<X_USER_MEASURE_CHILD> X_USER_MEASURE_CHILD { get; set; }
        public virtual DbSet<X_USER_NOTES_CHILD> X_USER_NOTES_CHILD { get; set; }
        public virtual DbSet<X_USER_RSRCHS_CHILD> X_USER_RSRCHS_CHILD { get; set; }
        public virtual DbSet<X_USER_TESTS_CHILD> X_USER_TESTS_CHILD { get; set; }
        public virtual DbSet<X_USER_TRAIN_CHILD> X_USER_TRAIN_CHILD { get; set; }
        public virtual DbSet<X_VKK_ND> X_VKK_ND { get; set; }
        public virtual DbSet<X_VKK_PROJ_COMP> X_VKK_PROJ_COMP { get; set; }
        public virtual DbSet<X_VKK_REPORT> X_VKK_REPORT { get; set; }
        public virtual DbSet<X_VLK> X_VLK { get; set; }
        public virtual DbSet<X_VLK_ENTRY> X_VLK_ENTRY { get; set; }
        public virtual DbSet<X_WEB_LIMS_LOG> X_WEB_LIMS_LOG { get; set; }
        public virtual DbSet<ZIPCODES> ZIPCODES { get; set; }
        public virtual DbSet<DISP_REPORT> DISP_REPORT { get; set; }
    
        public virtual ObjectResult<string> dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<ProcProtocol_Result> ProcProtocol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcProtocol_Result>("ProcProtocol");
        }
    
        public virtual ObjectResult<UnitsP_Result> UnitsP(string x_PROCESS_UNIT, string pRODUCT, string sAMPLING_POINT, string nAME, string eNTERED_ON)
        {
            var x_PROCESS_UNITParameter = x_PROCESS_UNIT != null ?
                new ObjectParameter("X_PROCESS_UNIT", x_PROCESS_UNIT) :
                new ObjectParameter("X_PROCESS_UNIT", typeof(string));
    
            var pRODUCTParameter = pRODUCT != null ?
                new ObjectParameter("Product", pRODUCT) :
                new ObjectParameter("Product", typeof(string));
    
            var sAMPLING_POINTParameter = sAMPLING_POINT != null ?
                new ObjectParameter("SAMPLING_POINT", sAMPLING_POINT) :
                new ObjectParameter("SAMPLING_POINT", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eNTERED_ONParameter = eNTERED_ON != null ?
                new ObjectParameter("ENTERED_ON", eNTERED_ON) :
                new ObjectParameter("ENTERED_ON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnitsP_Result>("UnitsP", x_PROCESS_UNITParameter, pRODUCTParameter, sAMPLING_POINTParameter, nAMEParameter, eNTERED_ONParameter);
        }
    }
}
