//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMS_USERS
    {
        public string USER_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string BREF_NAME { get; set; }
        public string LAB { get; set; }
        public string X_LOCATION { get; set; }
        public string PHONE { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string X_POSITION_TYPE { get; set; }
        public string X_POSITION { get; set; }
        public string X_EDUCATION { get; set; }
        public string X_BIRTHDAY { get; set; }
        public string X_WORK { get; set; }
        public string X_PROTOKOL { get; set; }
        public string X_EXPERIENCE { get; set; }
        public string X_PROV_TYPE { get; set; }
        public string PSWD { get; set; }
        public Nullable<System.DateTime> EXPIRES { get; set; }
        public string EXPIRED { get; set; }
        public Nullable<int> INTERVAL { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string BROWSE_CONFIG { get; set; }
        public string TEST_BROWSE_CONFIG { get; set; }
        public string PROJ_BROWSE_CONFIG { get; set; }
        public string EXT_LINK { get; set; }
        public string SAMPLE_IF_MENUS { get; set; }
        public string SAMPLE_FILTER { get; set; }
        public string BROWSE_FILTER_REQD { get; set; }
        public Nullable<int> TIMEOUT_INTERVAL { get; set; }
        public string PROJECT_FILTER { get; set; }
        public string FOLDER_IF_MENUS { get; set; }
        public string PROJECT_IF_MENUS { get; set; }
        public string BATCH_IF_MENUS { get; set; }
        public string CLOSE_LINK { get; set; }
        public Nullable<int> NOTEBOOK_REF_NUM { get; set; }
        public string SYNC_CLOCK { get; set; }
        public Nullable<int> TIME_OFFSET { get; set; }
        public string SIGNATURE_FILE { get; set; }
        public string SIGNATURE_CHECK { get; set; }
        public string USER_ROLE { get; set; }
        public string IS_ROLE { get; set; }
        public string USES_ROLES { get; set; }
        public string USER_DISABLED { get; set; }
        public Nullable<System.DateTime> DATE_DISABLED { get; set; }
        public Nullable<int> GMT_OFFSET { get; set; }
        public string LOCK_ON_TIMEOUT { get; set; }
        public Nullable<int> LOCK_TIMEOUT { get; set; }
        public string ALLOCATE_LICENSE { get; set; }
        public string RESTRICTED_USE { get; set; }
        public string SELF_SIGN_FILE { get; set; }
        public string TOKEN_SERIAL_NO { get; set; }
        public string SELF_SIGN_EXPIRED { get; set; }
        public string HOLIDAY_SCHEDULE { get; set; }
        public string DEFAULT_WORKFLOW { get; set; }
        public string USE_CUSTOMER_TEMP { get; set; }
        public string SAMPLE_CONSTRAINT { get; set; }
        public string TEST_CONSTRAINT { get; set; }
        public string RESULT_CONSTRAINT { get; set; }
        public string SAMPLE_DISP_FLDS { get; set; }
        public string TEST_DISP_FLDS { get; set; }
        public string OPEN_MSG_WINDOW { get; set; }
        public string LDAP_UID { get; set; }
        public string LDAP_SERVER { get; set; }
        public string DAYLIGHT_SAVINGS { get; set; }
        public string SIGNING_PSWD { get; set; }
        public Nullable<System.DateTime> SIGNING_EXPIRES { get; set; }
        public string SIGNING_EXPIRED { get; set; }
        public Nullable<int> SIGNING_INTERVAL { get; set; }
        public string LANGUAGE_PREFIX { get; set; }
        public string X_EDUCATION_DETAILS { get; set; }
        public string WEB_REMEMBER_ME { get; set; }
        public string WEB_LABEL_PRINTER { get; set; }
        public string WEB_LABEL_PRINTER_PORT { get; set; }
        public Nullable<System.DateTime> LAST_FAILED_LOGIN { get; set; }
        public string LAST_FAILED_IP { get; set; }
        public Nullable<int> FAILED_LOGINS { get; set; }
        public Nullable<System.DateTime> LAST_GOOD_LOGIN { get; set; }
        public string LAST_GOOD_IP { get; set; }
        public string X_DUTY_CHEMIST { get; set; }
        public string IS_STAFF { get; set; }
        public string X_STOCK { get; set; }
    }
}
