//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMS_MESSAGE
    {
        public int SEQ_NUMBER { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public string USER_NAME { get; set; }
        public string ROLE { get; set; }
        public string USER_GROUP { get; set; }
        public string LAB { get; set; }
        public string ALL_USERS { get; set; }
        public string OBJECT_CLASS { get; set; }
        public string OBJECT_ID { get; set; }
        public Nullable<System.DateTime> DISPLAY_UNTIL { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE_TEXT { get; set; }
        public string HIGH_PRIORITY { get; set; }
    }
}
