//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string X_LAB { get; set; }
        public string ADDRESS { get; set; }
        public string BUILDING { get; set; }
        public string SITE { get; set; }
        public string ROOM_NUMBER { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string ZIP { get; set; }
        public string CONTACT { get; set; }
        public string OUTSIDE { get; set; }
        public string COMPANY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
    }
}
