//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOT
    {
        public int LOT_NUMBER { get; set; }
        public string LOT_NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string Product { get; set; }
        public string Product_GRADE { get; set; }
        public Nullable<int> Product_VERSION { get; set; }
        public string CLOSED { get; set; }
        public string LOT_COMMENT { get; set; }
        public string SUPPLIER { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string CUSTOMER { get; set; }
        public Nullable<int> REPORT_NUMBER { get; set; }
        public string REPRINT_FLAG { get; set; }
        public Nullable<System.DateTime> REPRINT_DATE { get; set; }
        public Nullable<System.DateTime> ProductION_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string ORDER_NUMBER { get; set; }
        public Nullable<int> ORIGINAL_LOT { get; set; }
        public Nullable<int> PARENT_LOT { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string FULL_TESTING_REQD { get; set; }
        public string IN_SPEC { get; set; }
        public string PRIMARY_IN_SPEC { get; set; }
        public string TEMPLATE { get; set; }
        public string SAMPLE_PLAN { get; set; }
        public string SIGNED { get; set; }
    }
}
