//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOT_SOURCES
    {
        public int LOT_NUMBER { get; set; }
        public string SAMPLING_POINT { get; set; }
        public int SOURCE_LOT { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
