//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOT_SAMPLING_POINT
    {
        public int LOT_NUMBER { get; set; }
        public string LOT_NAME { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string Product { get; set; }
        public Nullable<int> Product_VERSION { get; set; }
        public string Product_GRADE { get; set; }
        public string PRIMARY_GRADE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DISPOSITION { get; set; }
        public Nullable<System.DateTime> DISPOSITION_DATE { get; set; }
        public string DISPOSITION_BY { get; set; }
        public string RESULTS_MODIFIED { get; set; }
        public string RESULTS_MISSING { get; set; }
        public string SAMPLES_REVIEWED { get; set; }
        public string TESTING_DONE { get; set; }
        public string PRIMARY_IN_SPEC { get; set; }
        public string IN_SPEC { get; set; }
        public string RESULTS_REJECTED { get; set; }
    }
}
