//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_JOBS
    {
        public string LABSTATION { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string ALIAS { get; set; }
        public string APPROVAL_REPORT { get; set; }
        public string APPROVAL_TYPE { get; set; }
        public string ARC_RAW_DATA_TO { get; set; }
        public string AUTO_ADD_SAMPLES { get; set; }
        public string AUTO_APPROVE { get; set; }
        public string AUTO_DELETE { get; set; }
        public string AUTO_FILL_BATCH { get; set; }
        public string AUTO_PRINT { get; set; }
        public string AUTO_RESET { get; set; }
        public string WORKSHEET { get; set; }
        public string BATCH_INSTRUMENT { get; set; }
        public string CLASSIC_MODE { get; set; }
        public string COPY_RESULTS_TO { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string FOLDER_DESCRIPTION { get; set; }
        public string FOLDER_NAME { get; set; }
        public string GROUP_BY_REPLICATE { get; set; }
        public string INSERT_SAMPLES { get; set; }
        public Nullable<int> MAX_LINES { get; set; }
        public string METHOD_NAME { get; set; }
        public string SPLIT_COMPONENTS { get; set; }
        public string TEST_ANALYSIS { get; set; }
        public string USE_JOB_NAME { get; set; }
        public string INSTRUMENT_NAME { get; set; }
    }
}
