//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_SAMPLES
    {
        public string LABSTATION { get; set; }
        public string JOB_NAME { get; set; }
        public string ALIAS { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string INSTRUMENT_NAME { get; set; }
        public Nullable<int> TEST_NUMBER { get; set; }
    }
}
