//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_ROUTINE
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string SOURCE_CODE { get; set; }
        public string WINDOW_CLASS { get; set; }
        public string MENU_NAME { get; set; }
        public string USER_MENU_NAME { get; set; }
        public string SUB_MENU_NAME { get; set; }
        public string USER_SUB_MENU_NAME { get; set; }
        public string MENU_LABEL { get; set; }
        public string FUNCTION_ID { get; set; }
        public string IMAGE_NAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
