//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTEBOOK_REF
    {
        public int REFERENCE_NUM { get; set; }
        public string NOTEBOOK { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string PAGE_NUMBER { get; set; }
        public string NOTEBOOK_COMMENT { get; set; }
    }
}
