//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJ_GRP_TEMPLATE
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string GROUP_NAME { get; set; }
        public string ID_CONFIG { get; set; }
        public string EXT_LINK { get; set; }
        public string GLOBAL_FLAG { get; set; }
        public string AUTO_REFRESH_FLAG { get; set; }
        public Nullable<int> REFRESH_INTERVAL { get; set; }
        public string AUTO_REBUILD_FLAG { get; set; }
        public string READ_ONLY { get; set; }
        public string DATA_EXPLORER { get; set; }
        public string LABEL_MASK { get; set; }
        public string GROUP_BY_FIELD { get; set; }
        public string OBJECT_REPORT { get; set; }
        public string GROUP_REPORT { get; set; }
        public string SUMMARY_REPORT { get; set; }
    }
}
