//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT_GROUP_GRP
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string FOLDER_1 { get; set; }
        public string FOLDER_2 { get; set; }
        public string FOLDER_3 { get; set; }
        public string FOLDER_4 { get; set; }
        public string FOLDER_5 { get; set; }
        public string FOLDER_6 { get; set; }
        public string FOLDER_7 { get; set; }
        public string FOLDER_8 { get; set; }
        public string FOLDER_9 { get; set; }
        public string FOLDER_10 { get; set; }
    }
}
