//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_TEMPLATE
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string ID_CONFIG { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string ABOUT_ENTITY { get; set; }
        public string ABOUT_ENTITY_DESC { get; set; }
        public string ABOUT_AUTO_BROWSE { get; set; }
        public string ABOUT_MANDATORY { get; set; }
        public string FOR_ENTITY { get; set; }
        public string FOR_ENTITY_DESC { get; set; }
        public string FOR_AUTO_BROWSE { get; set; }
        public string FOR_MANDATORY { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string GROUP_TESTS_BY { get; set; }
        public string TESTS_CONSTRAINT { get; set; }
        public string CHECK_OPEN_ORDERS { get; set; }
        public Nullable<int> AGE_CHK_INTERVAL { get; set; }
        public string CHECK_TEST_FREQ { get; set; }
        public string AUTO_LOG_SAMPLES { get; set; }
        public string AUTO_SAMPLED { get; set; }
        public string AUTO_RECEIVED { get; set; }
        public string AUTO_QUICK_TEST { get; set; }
        public string FAST_TEST_ASSIGN { get; set; }
        public string AUTO_NEW_ORDER { get; set; }
        public string USE_TEST_LISTS { get; set; }
        public string REPORTS { get; set; }
        public string PRMPT_RUSH_REASON { get; set; }
        public string PRMPT_HOLD_REASONS { get; set; }
        public string CONFIRM_CHANGES { get; set; }
        public string ORDER_RELEASED_SUB { get; set; }
        public string TESTS_RELEASED_SUB { get; set; }
        public string MODIFIED_RSLTS_SUB { get; set; }
        public string REPORT_FORMAT { get; set; }
        public string AUTO_GENERATE_DESC { get; set; }
        public string ORDER_TYPE { get; set; }
    }
}
