//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ENTRY
    {
        public string ORDER_NUM { get; set; }
        public string ANALYSIS { get; set; }
        public string PROFILE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public Nullable<int> REPLICATE_COUNT { get; set; }
        public string INSTRUMENT { get; set; }
        public string TEST_LOCATION { get; set; }
        public string REPORTED_NAME { get; set; }
        public string REPORTED { get; set; }
        public string REQUIRES_APPROVAL { get; set; }
        public string APPROVAL_ROLE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_ON { get; set; }
        public string LABORATORY { get; set; }
        public string AMENDED { get; set; }
        public string CANCELED { get; set; }
        public string GROUP_NAME { get; set; }
        public string SAMPLE_LOGGED { get; set; }
        public string STAT { get; set; }
    }
}
