//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public string ORDER_NUM { get; set; }
        public string LAST_ORDER_NUM { get; set; }
        public string MERGED_ORDER_NUM { get; set; }
        public string MERGED { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CLOSED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string TEMPLATE { get; set; }
        public string EXT_LINK { get; set; }
        public string RUSH { get; set; }
        public string RUSH_REASON { get; set; }
        public Nullable<System.DateTime> REQUIRED_DATE { get; set; }
        public string ABOUT_ENTITY { get; set; }
        public string ABOUT_ENTITY_DESC { get; set; }
        public string FOR_ENTITY { get; set; }
        public string FOR_ENTITY_DESC { get; set; }
        public string STATUS { get; set; }
        public string OLD_STATUS { get; set; }
        public string IN_SPEC { get; set; }
        public string IN_CONTROL { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string ACCEPTED_BY { get; set; }
        public Nullable<System.DateTime> ACCEPTED_ON { get; set; }
        public string SAMPLED_BY { get; set; }
        public Nullable<System.DateTime> SAMPLED_ON { get; set; }
        public string RECEIVED_BY { get; set; }
        public Nullable<System.DateTime> RECEIVED_ON { get; set; }
        public string CANCELED_BY { get; set; }
        public Nullable<System.DateTime> CANCELED_ON { get; set; }
        public string CANCELED_REASON { get; set; }
        public string CLOSED_BY { get; set; }
        public Nullable<System.DateTime> CLOSED_ON { get; set; }
        public string REVIEWED_BY { get; set; }
        public Nullable<System.DateTime> REVIEWED_ON { get; set; }
        public string IMPORTANT_MESSAGE { get; set; }
        public string ON_HOLD { get; set; }
        public string ON_HOLD_BY { get; set; }
        public Nullable<System.DateTime> ON_HOLD_ON { get; set; }
        public string ON_HOLD_REASON { get; set; }
        public string OFF_HOLD_BY { get; set; }
        public Nullable<System.DateTime> OFF_HOLD_ON { get; set; }
        public string OFF_HOLD_REASON { get; set; }
        public string IS_LOCKED { get; set; }
        public string REQUIRES_APPROVAL { get; set; }
        public string OBSERVATIONS { get; set; }
        public string TEST_LIST { get; set; }
        public string COLLECT_PRIORITY { get; set; }
        public string TESTING_PRIORITY { get; set; }
        public Nullable<int> NUM_SAMPLES { get; set; }
        public Nullable<int> NUM_SAMPLED { get; set; }
        public string RELEASED { get; set; }
        public string READY_TO_RELEASE { get; set; }
        public string MODIFIED_RESULTS { get; set; }
        public string FINAL_REPORT { get; set; }
        public string REPORT_FORMAT { get; set; }
        public string OVERRIDE_TEST_FREQ { get; set; }
        public string LAB_GROUP { get; set; }
        public string SAMPLES_RECEIVED { get; set; }
        public string MASK_GROUP { get; set; }
        public string HAS_FLAGS { get; set; }
    }
}
