//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_FIELD_ATTRIB
    {
        public string ORDER_NUM { get; set; }
        public string FIELD_NAME { get; set; }
        public string FAILED_EDIT_CHECK { get; set; }
        public string FAILED_CHK_REASON { get; set; }
        public string EDIT_CHECK_CLEARED { get; set; }
        public string CLEAR_CHK_REASON { get; set; }
        public string CLEAR_CHK_BY { get; set; }
        public Nullable<System.DateTime> CLEAR_CHK_ON { get; set; }
        public string VERIFIED { get; set; }
        public string VERIFIED_BY { get; set; }
        public Nullable<System.DateTime> VERIFIED_ON { get; set; }
        public string FIELD_COMMENT { get; set; }
        public string DATA_MODIFIED { get; set; }
        public string MODIFIED_REASON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string PREVIOUS_VALUE { get; set; }
        public string OVERRIDE { get; set; }
        public string OVERRIDE_BY { get; set; }
        public Nullable<System.DateTime> OVERRIDE_ON { get; set; }
        public string OVERRIDE_REASON { get; set; }
        public Nullable<System.DateTime> FAILED_CHK_ON { get; set; }
        public string FAILED_CHK_BY { get; set; }
        public string INPUT_FAILED { get; set; }
        public string INPUT_FAILED_BY { get; set; }
        public Nullable<System.DateTime> INPUT_FAILED_ON { get; set; }
    }
}
