//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_LINKING
    {
        public int COUNTER { get; set; }
        public int LINK_NUMBER { get; set; }
        public Nullable<int> PERSON_NUMBER { get; set; }
    }
}
