//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public int PERSON_NUMBER { get; set; }
        public string ADDRESS_BOOK { get; set; }
        public string REMOVED { get; set; }
        public string ALIAS { get; set; }
        public string SALUTATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string MID_INIT { get; set; }
        public string LAST_NAME { get; set; }
        public string NAME_SUFX { get; set; }
        public string TITLE { get; set; }
        public string ORGANIZATION { get; set; }
        public string STREET_ADDR { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIP { get; set; }
        public string TEL_COUNTRY_CODE { get; set; }
        public string TEL_AREA_CODE { get; set; }
        public string PHONE { get; set; }
        public string EXTENSION { get; set; }
        public string CELL_AREA_CODE { get; set; }
        public string CELL_NUMBER { get; set; }
        public string FAX_AREA_CODE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string FAX_EXTENSION { get; set; }
        public string BEEPER_AREA_CODE { get; set; }
        public string BEEPER_NUMBER { get; set; }
        public string HOME_AREA_CODE { get; set; }
        public string HOME_NUMBER { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string PERSON_NOTE { get; set; }
        public string EXT_LINK { get; set; }
        public string GROUP_NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<int> RELATES_TO { get; set; }
        public string CONTACT_TYPE { get; set; }
    }
}
