//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIMS_ANALYZES_NAMES_REL
    {
        public Nullable<int> name_id { get; set; }
        public string analyze { get; set; }
        public string lims_name { get; set; }
        public int counter { get; set; }
    }
}
