//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIMS
    {
        public int ID { get; set; }
        public string N { get; set; }
        public string Product { get; set; }
        public string PROCESS_UNIT { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string ANALYSIS { get; set; }
    }
}
