//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIMS_LIMS_Product
    {
        public int ID { get; set; }
        public string N { get; set; }
        public string PIMS_Product { get; set; }
        public string LIMS_Product { get; set; }
        public string title { get; set; }
    }
}
