//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_HISTORY
    {
        public string INSTRUMENT { get; set; }
        public System.DateTime PM_DATE { get; set; }
        public string X_CERTIFICATION { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public Nullable<long> DAYS { get; set; }
    }
}
