//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_UNIT
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string Product { get; set; }
        public string Product_GRADE { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string RUNNING { get; set; }
        public string EXT_LINK { get; set; }
        public string PHASE { get; set; }
        public string BUILDING { get; set; }
        public string X_REPORTED_NAME { get; set; }
    }
}
