//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_SCHEDULE
    {
        public int SCHEDULE_NUMBER { get; set; }
        public Nullable<int> LOGIN_OFFSET { get; set; }
        public Nullable<int> LOGIN_TIME { get; set; }
        public string SCHD_COLLECT_TIME { get; set; }
        public string UNIT { get; set; }
        public string Product { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string TEST_LIST { get; set; }
        public string MON_COLLECT { get; set; }
        public string TUES_COLLECT { get; set; }
        public string WED_COLLECT { get; set; }
        public string THURS_COLLECT { get; set; }
        public string FRI_COLLECT { get; set; }
        public string SAT_COLLECT { get; set; }
        public string SUN_COLLECT { get; set; }
        public string WK_1_COLLECT { get; set; }
        public string WK_2_COLLECT { get; set; }
        public string WK_3_COLLECT { get; set; }
        public string WK_4_COLLECT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> LAST_RUN { get; set; }
        public string SCHEDULE_NAME { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string RUNNING { get; set; }
        public string PHASE { get; set; }
        public string REMOVED { get; set; }
        public Nullable<int> SCHED_RULE { get; set; }
        public string WK_5_COLLECT { get; set; }
        public Nullable<int> DAY_COLLECT { get; set; }
        public string JAN_COLLECT { get; set; }
        public string FEB_COLLECT { get; set; }
        public string MAR_COLLECT { get; set; }
        public string APR_COLLECT { get; set; }
        public string MAY_COLLECT { get; set; }
        public string JUN_COLLECT { get; set; }
        public string JUL_COLLECT { get; set; }
        public string AUG_COLLECT { get; set; }
        public string SEP_COLLECT { get; set; }
        public string OCT_COLLECT { get; set; }
        public string NOV_COLLECT { get; set; }
        public string DEC_COLLECT { get; set; }
        public string ANALYSES { get; set; }
        public Nullable<int> DAYS_AHEAD { get; set; }
        public Nullable<System.DateTime> R4_BASE_DATE { get; set; }
        public Nullable<int> R4_DAYS { get; set; }
    }
}
