//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROC_SCHED_PARENT
    {
        public string NAME { get; set; }
        public Nullable<int> FIRST_DAY_OF_WEEK { get; set; }
        public Nullable<int> TREAT_HOLIDAYS_AS { get; set; }
        public string NEEDS_RELOADING { get; set; }
        public string WORKSTATION { get; set; }
        public string RUNNING { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string GUI_CONFIG { get; set; }
    }
}
