//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string X_WORK { get; set; }
        public string ACTIVE { get; set; }
        public string X_DESCRIPTION_2 { get; set; }
        public string GROUP_NAME { get; set; }
        public string X_PROD_TYPE { get; set; }
        public string X_PROD_NAME { get; set; }
        public string X_COD_OKP { get; set; }
        public string X_NORM_DOC { get; set; }
        public string X_NTD_ALTER { get; set; }
        public string X_NTD { get; set; }
        public Nullable<int> X_CERTIFICATION { get; set; }
        public string X_CERTIF_DATE { get; set; }
        public string X_SEKCIA { get; set; }
        public string X_PROC_UNIT { get; set; }
        public string X_STAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<float> COST_FACTOR { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string TEST_LIST { get; set; }
        public Nullable<int> FULL_TEST_FREQ { get; set; }
        public Nullable<int> LOTS_TO_GO { get; set; }
        public string REPORT_FORMAT { get; set; }
        public string SAMPLE_PLAN { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string APPROVED { get; set; }
        public string APPROVAL_GROUP { get; set; }
        public string READY_FOR_APPROVAL { get; set; }
        public Nullable<int> APPROVAL_ID { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> X_NOTE { get; set; }
        public string bar_kod { get; set; }
        public Nullable<int> X_TZ { get; set; }
        public string TEMPLATE { get; set; }
        public string GRADE_TEMPLATE { get; set; }
        public string STAGE_TEMPLATE { get; set; }
        public string NUMERIC_SPEC_TEMP { get; set; }
        public string TEXT_SPEC_TEMP { get; set; }
        public string FORMULA_SPEC_TEMP { get; set; }
        public string SPC_SPEC_TEMP { get; set; }
        public string SIGNED { get; set; }
        public string REPORTED_SPEC_TEMP { get; set; }
    }
}
