//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_SPEC
    {
        public string RULE_TYPE { get; set; }
        public string Product { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string GRADE { get; set; }
        public string STAGE { get; set; }
        public string ANALYSIS { get; set; }
        public string COMPONENT { get; set; }
        public string UNITS { get; set; }
        public string ROUND { get; set; }
        public Nullable<int> PLACES { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string SPEC_RULE { get; set; }
        public Nullable<float> MIN_VALUE { get; set; }
        public Nullable<float> MAX_VALUE { get; set; }
        public string TEXT_VALUE { get; set; }
        public Nullable<float> LSL { get; set; }
        public Nullable<float> USL { get; set; }
        public Nullable<float> NOMINAL_VALUE { get; set; }
        public string SHOW_CHART { get; set; }
        public string CHART_TYPE { get; set; }
        public Nullable<int> SUBGROUP_SIZE { get; set; }
        public string FORMULA { get; set; }
        public string PARTIAL { get; set; }
        public string SPEC_TYPE { get; set; }
        public string REQUIRED { get; set; }
        public Nullable<int> NUM_RESULT_REPS { get; set; }
        public string CLASS { get; set; }
        public string SPECIFIC_ANALYSIS { get; set; }
        public string HI_CONTROL_1 { get; set; }
        public string HI_CONTROL_2 { get; set; }
        public string LO_CONTROL_1 { get; set; }
        public string LO_CONTROL_2 { get; set; }
        public string REPORTED_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> NUM_HISTORY_PTS { get; set; }
        public int ENTRY_CODE { get; set; }
        public string SEASON { get; set; }
        public string FACTOR_VALUES { get; set; }
        public string FACTOR_OPERATOR { get; set; }
    }
}
