//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_GRADE_STAGE
    {
        public string Product { get; set; }
        public int VERSION { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string GRADE { get; set; }
        public string STAGE { get; set; }
        public string ANALYSIS { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string SPEC_TYPE { get; set; }
        public Nullable<int> NUM_REPS { get; set; }
        public string PARTIAL { get; set; }
        public string EXT_LINK { get; set; }
        public string REPORTED_NAME { get; set; }
        public string VARIATION { get; set; }
        public string REQUIRED { get; set; }
        public string X_IS_GUARANTEE { get; set; }
        public Nullable<int> X_GUARANTEE_PERIOD { get; set; }
        public Nullable<int> X_G_TEST_NUMBER { get; set; }
        public Nullable<System.DateTime> ENDING_USEFUL_LIFE { get; set; }
        public Nullable<System.DateTime> LAST_COEFF_DEFIN { get; set; }
        public string STATE { get; set; }
    }
}
