//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_HISTORY
    {
        public Nullable<int> ENTRY_CODE { get; set; }
        public int ORDER_NUMBER { get; set; }
        public Nullable<int> RESULT_NUMBER { get; set; }
    }
}
