//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_GRADE
    {
        public string Product { get; set; }
        public int VERSION { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string GRADE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTINUE_CHECKING { get; set; }
        public string EXT_LINK { get; set; }
        public string TEST_LIST { get; set; }
        public string ALWAYS_CHECK { get; set; }
        public Nullable<int> FULL_TEST_FREQ { get; set; }
        public Nullable<int> LOTS_TO_GO { get; set; }
        public string REPORT_FORMAT { get; set; }
        public string X_ARBITR_NUM_TYPE { get; set; }
        public string X_STORAGE_PERIOD { get; set; }
    }
}
