//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_TEMPLATE
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string EXT_LINK { get; set; }
        public string GROUP_NAME { get; set; }
        public string REMOVED { get; set; }
        public string NAME_PREFIX { get; set; }
        public string ID_CONFIG { get; set; }
        public string CLOSE_ON_SAMP_LOG { get; set; }
        public string ITEM_TABLES { get; set; }
        public string RSLTS_IN_LIFECYCLE { get; set; }
        public string F5725 { get; set; }
        public string SAMPLE_DISP_FLDS { get; set; }
        public string TEST_DISP_FLDS { get; set; }
        public string MOD_SAMP_TEMP { get; set; }
        public string ITEM_TEMPLATES { get; set; }
        public string SHOW_ITEM_ICONS { get; set; }
        public string AUTO_REFRESH_VIEW { get; set; }
        public string SHOW_ALIQUOTS { get; set; }
        public string ROW_EDIT { get; set; }
        public string LABEL_MASK { get; set; }
        public string EDIT_TEST_TEMP { get; set; }
    }
}
