//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_COMP_CODES
    {
        public string TEMPLATE { get; set; }
        public string COMPONENT { get; set; }
        public int VERSION { get; set; }
        public string CODE { get; set; }
        public string VALUE { get; set; }
    }
}
