//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public string NAME { get; set; }
        public Nullable<int> TEMPLATE_VERSION { get; set; }
        public string TEMPLATE { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public string OLD_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public Nullable<System.DateTime> DATE_STARTED { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETED { get; set; }
        public Nullable<System.DateTime> DATE_REVIEWED { get; set; }
        public Nullable<float> COST_FACTOR { get; set; }
        public string CUSTOMER { get; set; }
        public string CUSTOMER_CONTACT { get; set; }
        public string OWNER { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<int> NUM_SAMPLES { get; set; }
        public Nullable<int> NUM_U { get; set; }
        public Nullable<int> NUM_I { get; set; }
        public Nullable<int> NUM_P { get; set; }
        public Nullable<int> NUM_C { get; set; }
        public Nullable<int> NUM_A { get; set; }
        public Nullable<int> NUM_R { get; set; }
        public Nullable<int> NUM_X { get; set; }
        public string EXT_LINK { get; set; }
        public string GROUP_NAME { get; set; }
        public string CLOSED { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string CONCLUSION { get; set; }
        public string Product { get; set; }
        public string STABILITY { get; set; }
        public string CHARGE_CODE { get; set; }
        public string USE_GROUP_LOGIN { get; set; }
        public string BATCH_TEMPLATE { get; set; }
        public string USE_GRID_LOGIN { get; set; }
        public string F5725 { get; set; }
        public string F25PROCESS { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CUSTOMER_TEMPLATE { get; set; }
        public string OWNER_LOCATION { get; set; }
        public string ALIQUOT { get; set; }
        public string SIGNED { get; set; }
        public string X_ANALYSIS { get; set; }
        public string X_CERT_CHAR_DESC { get; set; }
        public Nullable<float> X_CERT_ERROR { get; set; }
        public Nullable<float> X_CERT_VALUE { get; set; }
        public string X_COMPONENT { get; set; }
        public string X_CONTROL_METH { get; set; }
        public string X_GAMMA { get; set; }
        public string X_GSO { get; set; }
        public string X_INACCURACY_BITMAP { get; set; }
        public string X_LAB { get; set; }
        public Nullable<float> X_MISTAKE { get; set; }
        public string X_NEW_SKO_REPEAT { get; set; }
        public string X_NEW_SKO_REPROD { get; set; }
        public Nullable<System.DateTime> X_PER_FROM { get; set; }
        public Nullable<System.DateTime> X_PER_TO { get; set; }
        public string X_PRECISION_BITMAP { get; set; }
        public string X_RANGE { get; set; }
        public string X_REPEAT_BITMAP { get; set; }
        public string X_ROUNDING { get; set; }
        public string X_ROUNDING_2 { get; set; }
        public Nullable<float> X_SIGMA_S { get; set; }
        public Nullable<float> X_T_CALCULATE { get; set; }
        public Nullable<float> X_T_TABLE_VALUE { get; set; }
        public Nullable<float> X_TETTA_L { get; set; }
        public string X_VARIATION { get; set; }
        public string X_PROTOCOL_NO { get; set; }
        public Nullable<System.DateTime> X_PROTOCOL_DATE { get; set; }
        public string X_PROTOCOL_REVIEWER { get; set; }
        public string X_ND { get; set; }
        public string X_ND_DESC { get; set; }
        public string X_CTRL_SAMPLE_NAME { get; set; }
    }
}
