//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERY_TAG_PROPS
    {
        public string QUERY_TAG { get; set; }
        public string ACCESS_ROUTINE { get; set; }
        public Nullable<int> NUM_ARGS { get; set; }
        public string ARG_1_TYPE { get; set; }
        public string ARG_2_TYPE { get; set; }
        public string ARG_3_TYPE { get; set; }
        public string ARG_4_TYPE { get; set; }
        public string ARG_5_TYPE { get; set; }
        public string ARG_6_TYPE { get; set; }
        public string ARG_7_TYPE { get; set; }
        public string ARG_8_TYPE { get; set; }
        public string ARG_9_TYPE { get; set; }
        public string ARG_10_TYPE { get; set; }
        public string ARG_11_TYPE { get; set; }
        public string ARG_12_TYPE { get; set; }
        public string ARG_13_TYPE { get; set; }
        public string ARG_14_TYPE { get; set; }
        public string ARG_15_TYPE { get; set; }
        public string ARG_16_TYPE { get; set; }
        public string ARG_17_TYPE { get; set; }
        public string ARG_18_TYPE { get; set; }
        public string ARG_19_TYPE { get; set; }
        public string ARG_20_TYPE { get; set; }
        public string ARG_1_VALUE { get; set; }
        public string ARG_2_VALUE { get; set; }
        public string ARG_3_VALUE { get; set; }
        public string ARG_4_VALUE { get; set; }
        public string ARG_5_VALUE { get; set; }
        public string ARG_6_VALUE { get; set; }
        public string ARG_7_VALUE { get; set; }
        public string ARG_8_VALUE { get; set; }
        public string ARG_9_VALUE { get; set; }
        public string ARG_10_VALUE { get; set; }
        public string ARG_11_VALUE { get; set; }
        public string ARG_12_VALUE { get; set; }
        public string ARG_13_VALUE { get; set; }
        public string ARG_14_VALUE { get; set; }
        public string ARG_15_VALUE { get; set; }
        public string ARG_16_VALUE { get; set; }
        public string ARG_17_VALUE { get; set; }
        public string ARG_18_VALUE { get; set; }
        public string ARG_19_VALUE { get; set; }
        public string ARG_20_VALUE { get; set; }
        public string OTHER { get; set; }
    }
}
