//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_INGREDIENT
    {
        public int ENTRY_CODE { get; set; }
        public string RECIPE { get; set; }
        public int VERSION { get; set; }
        public string INGREDIENT { get; set; }
        public string RECIPE_INGREDIENT1 { get; set; }
        public Nullable<int> RECIPE_INGRED_VER { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public Nullable<float> QUANTITY_PERCENT { get; set; }
        public string QUANTITY_UNITS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public Nullable<int> PERCENT_LOST { get; set; }
        public Nullable<float> ADJUSTED_PERCENT { get; set; }
        public string USER_ADDED { get; set; }
        public string INST_GROUP { get; set; }
        public Nullable<float> QUANTITY_TOLERANCE { get; set; }
        public string EXCLUDE_FROM_QUANT { get; set; }
        public string OPTIONAL { get; set; }
    }
}
