//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_TEMPLATE
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string ID_CONFIG { get; set; }
        public string ROUND_INGRED_QTY { get; set; }
        public Nullable<int> INGRED_QTY_RND_TO { get; set; }
        public string ROUND_INGRED_PCT { get; set; }
        public Nullable<int> INGRED_PCT_RND_TO { get; set; }
        public string QUANTITY_BASED { get; set; }
        public string ITEM_TABLES { get; set; }
        public string ITEM_TEMPLATES { get; set; }
        public string REPORTS { get; set; }
        public string DEFAULT_UNITS { get; set; }
        public string ADD_TO_STOCK { get; set; }
    }
}
