//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_EXP_INGRED
    {
        public string RECIPE { get; set; }
        public int VERSION { get; set; }
        public string INGREDIENT { get; set; }
        public string QUANTITY { get; set; }
        public string QUANTITY_PERCENT { get; set; }
        public string QUANTITY_UNITS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
