//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_TEMP_GRPS
    {
        public int GROUP_NUMBER { get; set; }
        public string TEMPLATE { get; set; }
        public int VERSION { get; set; }
        public string GROUP_TITLE { get; set; }
        public string EDIT_GROUP_NAME { get; set; }
        public string VIEW_GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int ORDER_NUMBER { get; set; }
    }
}
