//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        public string NAME { get; set; }
        public int VERSION { get; set; }
        public string TEMPLATE { get; set; }
        public Nullable<int> TEMPLATE_VERSION { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string EXT_LINK { get; set; }
        public string CLOSED { get; set; }
        public Nullable<float> MAKES_QUANTITY { get; set; }
        public string X_UNITS { get; set; }
        public string X_NAME { get; set; }
        public string X_ND { get; set; }
        public string X_CONCENTRATION { get; set; }
        public string X_CONC_UNIT { get; set; }
    }
}
