//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGRESSION
    {
        public string TEMPLATE { get; set; }
        public string LOWER_SPEC_LIMIT { get; set; }
        public string UPPER_SPEC_LIMIT { get; set; }
        public string SPECIFIC_ANALYSIS { get; set; }
        public string CHART_ANALYSIS { get; set; }
        public string CHART_COMPONENT { get; set; }
        public string PROBABILITY_LEVEL { get; set; }
        public string LIN_REGRESSION { get; set; }
        public string EXP_REGRESSION { get; set; }
        public string LOG_REGRESSION { get; set; }
        public string POW_REGRESSION { get; set; }
        public string SHOW_UCL { get; set; }
        public string SHOW_LCL { get; set; }
        public string CALC_UCL_INTERCEPT { get; set; }
        public string CALC_LCL_INTERCEPT { get; set; }
        public string CALC_PRED_LINE_INT { get; set; }
    }
}
