//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTS
    {
        public int REPORT_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string REPORT_TYPE { get; set; }
        public string PURPOSE { get; set; }
        public string OBJECT_CLASS { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<int> PRINT_COUNT { get; set; }
        public string DATA_CHANGED { get; set; }
        public string RESULTS_CHANGED { get; set; }
        public string REPORT_FILE_NAME { get; set; }
        public string SUPERSEDED { get; set; }
        public string SUPERSEDED_BY { get; set; }
        public string ALLOW_EDIT { get; set; }
        public string ALLOW_PRINT { get; set; }
        public string REPORT_STATUS { get; set; }
        public string FAILURE_REASON { get; set; }
    }
}
