//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_SCHEDULER
    {
        public string NAME { get; set; }
        public string WORKSTATION { get; set; }
        public string REPORT_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_FLAG { get; set; }
        public string INCREMENT_FLAG { get; set; }
        public Nullable<int> FILE_VERSION { get; set; }
        public string PRINT_FLAG { get; set; }
        public string MAIL_FLAG { get; set; }
        public string MAIL_TO { get; set; }
        public string DAYS_OF_WEEK { get; set; }
        public Nullable<int> START_TIME { get; set; }
        public Nullable<int> END_TIME { get; set; }
        public Nullable<int> TIME_INTERVAL { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string DUE_NEXT { get; set; }
        public string LAST_RUN { get; set; }
        public string RUN_FLAG { get; set; }
        public string MONDAY { get; set; }
        public string TUESDAY { get; set; }
        public string WEDNESDAY { get; set; }
        public string THURSDAY { get; set; }
        public string FRIDAY { get; set; }
        public string SATURDAY { get; set; }
        public string SUNDAY { get; set; }
    }
}
