//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUN_CHART
    {
        public string TEMPLATE { get; set; }
        public string Y_VALUE_FIELD { get; set; }
        public string X_VAR_DESC { get; set; }
        public string TITLE { get; set; }
        public string TITLE_FONT { get; set; }
        public string X_LABEL_FONT { get; set; }
        public string X_LABEL_ITALIC { get; set; }
        public string X_LABEL_ANGLE { get; set; }
        public string WINDOW_LABEL { get; set; }
        public string SPECIFIC_ANALYSIS { get; set; }
        public string CHART_ANALYSIS { get; set; }
        public string CHART_COMPONENT1 { get; set; }
        public string CHART_COMPONENT2 { get; set; }
        public string CHART_COMPONENT3 { get; set; }
        public string CHART_COMPONENT4 { get; set; }
        public string CHART_COMPONENT5 { get; set; }
        public string MULTIPLE_GRAPHS { get; set; }
    }
}
