//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLING_POINT
    {
        public string NAME { get; set; }
        public string TEST_LIST { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string X_DEP { get; set; }
        public string PLANT { get; set; }
        public string SEKCIA { get; set; }
        public string SAMP_PLACE { get; set; }
        public string PLACE_NUMBER { get; set; }
        public string DESCRIPTION_2 { get; set; }
        public string PLACE_POINT { get; set; }
        public string SPACE_POINT { get; set; }
        public string ID_SAMPLING_POINT { get; set; }
        public string EXT_LINK { get; set; }
        public string PRIMARY_DISP_REQ { get; set; }
        public string SECONDARY_DISP_REQ { get; set; }
        public string Product { get; set; }
        public string PRIMARY_RUN { get; set; }
        public string SECONDARY_RUN { get; set; }
        public string TERTIARY_RUN { get; set; }
        public string ZONE { get; set; }
        public string WATER_SOURCE { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string SAMPLER_ID { get; set; }
        public string SERVICE_RESERVOIR { get; set; }
        public string TREATMENT_WORKS { get; set; }
        public string REPORTED_NAME { get; set; }
        public string X_ID_SAMPLING_POINT_ASUTP { get; set; }
    }
}
