//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE_PLAN_ENTRY
    {
        public string SAMPLE_PLAN { get; set; }
        public int ENTRY_CODE { get; set; }
        public Nullable<float> MIN_QUANTITY { get; set; }
        public Nullable<float> MAX_QUANTITY { get; set; }
        public Nullable<int> NUM_SAMPLES { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string TEST_LIST { get; set; }
        public string BATCH_TEMPLATE { get; set; }
        public string SAMPLING_POINT { get; set; }
    }
}
