//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE_RULES
    {
        public int ENTRY_CODE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string ANALYSIS { get; set; }
        public string VARIATION { get; set; }
        public string SAMPLE_TYPE { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public string COLLECTION_METHOD { get; set; }
        public string STORAGE_CONDITION { get; set; }
    }
}
