//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE_ACTION
    {
        public int SAMPLE_NUMBER { get; set; }
        public string ACTION_NAME { get; set; }
        public string ACTION_TEXT { get; set; }
        public System.DateTime ACTION_START_TIME { get; set; }
        public Nullable<System.DateTime> ACTION_STOP_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string COMPLETE { get; set; }
        public string WORKSTATION { get; set; }
        public string REMOVED { get; set; }
        public Nullable<System.DateTime> REMOVED_ON { get; set; }
        public string REMOVED_BY { get; set; }
        public string OVERRIDE { get; set; }
        public Nullable<int> SEQ_NUM { get; set; }
        public string TEMPLATE { get; set; }
    }
}
