//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE_TEMPLATE
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string GROUP_NAME { get; set; }
        public string TITLE { get; set; }
        public string INITIAL_STATUS { get; set; }
        public string ID_CONFIG { get; set; }
        public string EDIT_TESTS { get; set; }
        public string ENTER_RESULTS { get; set; }
        public string LABEL_ID { get; set; }
        public string RECEIPT_ID { get; set; }
        public string EXT_LINK { get; set; }
        public string ADD_Product_TESTS { get; set; }
        public string ADD_SPEC_TESTS { get; set; }
        public string OVERRIDE_OPTIONAL { get; set; }
        public string BATCH_RECEIPT { get; set; }
        public string OVERRIDE_RPTABLE { get; set; }
        public string BACKGROUND_LOGIN { get; set; }
        public string OVERRIDE_DISPLAYED { get; set; }
        public string USE_ANAL_LIMITS { get; set; }
        public string LABEL_MASK { get; set; }
        public string ALIQUOT_ON { get; set; }
        public string SAMP_EVENT_FIELDS { get; set; }
        public string EDIT_TESTS_BY_PROD { get; set; }
    }
}
