//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHED_TYPE_TEMP
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string OBJECT_LABEL { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string DESCRIPTION_FIELDS { get; set; }
        public string WHERE_CLAUSE { get; set; }
        public string LABEL_ID { get; set; }
        public string RECEIPT_ID { get; set; }
        public string COMPLETE_ACTION { get; set; }
        public string EXT_LINK { get; set; }
    }
}
