//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_ENTRY
    {
        public int ENTRY_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public string START_TIME { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string END_TIME { get; set; }
        public string SCHEDULE_TYPE { get; set; }
        public string OBJECT_KEY { get; set; }
        public string DESCRIPTION { get; set; }
        public string SCHEDULE_NOTE { get; set; }
        public string ENTRY_TYPE { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string SUBROUTINE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string GROUP_NAME { get; set; }
        public string COMPLETE { get; set; }
        public string WORKSTATION { get; set; }
        public string STATUS { get; set; }
        public string WARNING { get; set; }
    }
}
