//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER_ACTION
    {
        public string SERVER_NAME { get; set; }
        public int ACTION_NUMBER { get; set; }
        public string ACTION_TEXT { get; set; }
        public string IN_PROGRESS { get; set; }
    }
}
