//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNAPSHOT
    {
        public string OBJECT_CLASS { get; set; }
        public string OBJECT_KEY { get; set; }
        public string ADDED_BY { get; set; }
        public System.DateTime ADDED_ON { get; set; }
        public string SNAPSHOT_EVENT { get; set; }
        public string OBJECT_CHANGED_BY { get; set; }
        public Nullable<System.DateTime> OBJECT_CHANGED_ON { get; set; }
        public Nullable<int> OBJECT_VERSION { get; set; }
        public string LIMS_VERSION { get; set; }
        public string DBFILE_NAME_OBJ { get; set; }
        public string DBFILE_NAME_XML { get; set; }
        public string DBFILE_NAME_PDF { get; set; }
    }
}
