//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class STANDARD_REAGENT
    {
        public string NAME { get; set; }
        public string TEMPLATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<int> SEQUENCE_NUMBER { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> SAMPLE_NUMBER { get; set; }
        public string VENDOR_SERIAL_NUM { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> ACTIVATED_ON { get; set; }
        public string ACTIVATED_BY { get; set; }
        public string F5725 { get; set; }
    }
}
