//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class STD_REAG_TEMP
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<int> EXPIRATION_INTV { get; set; }
        public string ID_FORMULA { get; set; }
        public string EXT_LINK { get; set; }
        public string SAMPLE_TEMPLATE { get; set; }
        public string TEST_LIST { get; set; }
        public string KEEP_IN_STOCK { get; set; }
        public string VENDOR { get; set; }
        public string Product { get; set; }
        public string ACTIVATE_INCMPLT { get; set; }
        public string ID_CONFIG { get; set; }
        public string F5725 { get; set; }
    }
}
