//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_METHOD
    {
        public string NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
        public string X_ACCREDITATION { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string X_AUTHOR { get; set; }
        public Nullable<System.DateTime> X_DATE_START { get; set; }
        public string X_DATE_END { get; set; }
        public string X_ND_TYPE { get; set; }
        public string X_ANALOG { get; set; }
        public Nullable<int> ARCHIVE_DOC_ID { get; set; }
        public string X_NOTES { get; set; }
    }
}
