//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_METHOD_INV
    {
        public string T_TEST_METHOD { get; set; }
        public string T_TEST_METHOD_INV1 { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
