//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_METHOD_ENTRY
    {
        public string T_TEST_METHOD { get; set; }
        public string T_TEST_METHOD_ENTRY1 { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<System.DateTime> X_CHANGE_DATE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string X_DATE { get; set; }
        public Nullable<int> ARCHIVE_DOC_ID { get; set; }
        public Nullable<System.DateTime> X_DATE_START { get; set; }
        public string X_AUTHOR { get; set; }
    }
}
