//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_METHOD_INV_E
    {
        public string T_TEST_METHOD { get; set; }
        public string T_TEST_METHOD_INV { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string INVENTORY_TYPE { get; set; }
        public Nullable<int> INVENTORY_ITEM { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<float> PLANNED_QUANTITY { get; set; }
        public string UNITS { get; set; }
    }
}
