//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_AUDIT_RPT
    {
        public int COUNTER { get; set; }
        public string PARENT_KEY { get; set; }
        public string PARENT_TABLE { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string TABLE_KEY { get; set; }
        public string ACTION { get; set; }
        public string AUDIT_TYPE { get; set; }
        public string REASON { get; set; }
        public string USER_NAME { get; set; }
        public System.DateTime AUDIT_TIMESTAMP { get; set; }
        public string REPORTED_BY { get; set; }
        public Nullable<System.DateTime> REPORTED_ON { get; set; }
        public string PARTIAL_FLAG { get; set; }
        public string TABLE_KEY_1 { get; set; }
        public string TABLE_KEY_2 { get; set; }
        public string TABLE_KEY_3 { get; set; }
        public string TABLE_KEY_4 { get; set; }
        public string TABLE_KEY_5 { get; set; }
        public string TABLE_KEY_6 { get; set; }
        public string TABLE_KEY_7 { get; set; }
        public string TABLE_KEY_8 { get; set; }
        public string TABLE_KEY_9 { get; set; }
        public string TABLE_KEY_10 { get; set; }
        public string TABLE_FIELD { get; set; }
    }
}
