//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_FORMAT
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string HAS_ROW_HEADER { get; set; }
        public string DATA_IN_ROW_HEADER { get; set; }
        public string HAS_COL_HEADER { get; set; }
        public string DATA_IN_COL_HEADER { get; set; }
        public Nullable<int> COL_REPEATS { get; set; }
        public Nullable<int> ROW_REPEATS { get; set; }
        public string HAS_FOOTER_ROW { get; set; }
        public string SUM_FOOTER { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public string TABLE_HTML { get; set; }
    }
}
