//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_MASTER
    {
        public string NAME { get; set; }
        public string PRETTY_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string INSERT_FLAG { get; set; }
        public string USES_EDITOR { get; set; }
        public string CONFIGURE_DIALOG { get; set; }
        public string KEY_FIELDS { get; set; }
        public string DESCRIPTION_FIELDS { get; set; }
        public string GROUP_NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string BROWSE_ENTIRE_TABLE { get; set; }
        public string WIZARD_FIELDS { get; set; }
        public string USER_ADDED { get; set; }
        public string PARENT_TABLE { get; set; }
        public string REPORT_NAME { get; set; }
        public string APPROVAL_ROUTING { get; set; }
        public string DYNAMIC_TABLE { get; set; }
        public string TABLE_GROUP { get; set; }
        public string BITMAP_NAME { get; set; }
    }
}
