//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_DISP_ENTRY
    {
        public string TEST_DISP_FLDS { get; set; }
        public string TEST_FIELD { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
