//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_LIST_ENTRY
    {
        public string NAME { get; set; }
        public string ANALYSIS { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string STD_TEST { get; set; }
        public Nullable<int> REPLICATE_COUNT { get; set; }
        public string PARAMETER_NAME { get; set; }
        public string PARAMETER_VALUE { get; set; }
        public Nullable<int> TEST_PRIORITY { get; set; }
        public string INSTRUMENT { get; set; }
        public string TEST_LOCATION { get; set; }
        public string ASSIGN_IF_PRESENT { get; set; }
        public string VARIATION { get; set; }
        public string F25CNTR_TST { get; set; }
        public Nullable<int> ANALYSIS_COUNT { get; set; }
        public string REPORTED_NAME { get; set; }
        public string REPORTED { get; set; }
    }
}
