//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        public Nullable<int> SAMPLE_NUMBER { get; set; }
        public int TEST_NUMBER { get; set; }
        public Nullable<int> CHARGE_ENTRY { get; set; }
        public string ANALYSIS { get; set; }
        public Nullable<int> VERSION { get; set; }
        public Nullable<int> REPLICATE_COUNT { get; set; }
        public string STATUS { get; set; }
        public string OLD_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public Nullable<System.DateTime> DATE_STARTED { get; set; }
        public string ASSIGNED_OPERATOR { get; set; }
        public string PREP { get; set; }
        public Nullable<System.DateTime> PREP_DATE { get; set; }
        public string PREP_BY { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETED { get; set; }
        public Nullable<System.DateTime> DATE_REVIEWED { get; set; }
        public string REVIEWER { get; set; }
        public string REPLICATE_TEST { get; set; }
        public string INSTRUMENT { get; set; }
        public Nullable<int> TEST_PRIORITY { get; set; }
        public string IN_SPEC { get; set; }
        public string IN_CAL { get; set; }
        public string TEST_COMMENT { get; set; }
        public string TEST_LOCATION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string GROUP_NAME { get; set; }
        public string PARAMETER_NAME { get; set; }
        public string PARAMETER_VALUE { get; set; }
        public Nullable<System.DateTime> EXPECTED_DATE { get; set; }
        public string LAB { get; set; }
        public string RESOLVE_REQD { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string STAGE { get; set; }
        public string PRIMARY_IN_SPEC { get; set; }
        public string BATCH { get; set; }
        public string IN_CONTROL { get; set; }
        public string REPORTED_NAME { get; set; }
        public string VARIATION { get; set; }
        public string TEST_LIST { get; set; }
        public string RE_TESTED { get; set; }
        public string MODIFIED_RESULTS { get; set; }
        public Nullable<int> ALIQUOTED_TO { get; set; }
        public string ON_WORKSHEET { get; set; }
        public string DOUBLE_BLIND { get; set; }
        public string LOCATION { get; set; }
        public string X_COPY_TEST { get; set; }
        public string DISP_FLDS { get; set; }
        public string DISPLAY_RESULTS { get; set; }
        public string ALIQUOT_GROUP { get; set; }
        public string SPLIT_REPLICATES { get; set; }
        public string CROSS_SAMPLE { get; set; }
        public string RELEASED { get; set; }
        public string RELEASED_BY { get; set; }
        public Nullable<System.DateTime> RELEASED_ON { get; set; }
        public string RELEASE_COMMENT { get; set; }
        public string DOUBLE_ENTRY { get; set; }
        public Nullable<int> ANALYSIS_COUNT { get; set; }
        public Nullable<int> BATCH_PARENT_TEST { get; set; }
        public Nullable<int> BATCH_SIBLING_TEST { get; set; }
        public Nullable<int> PARENT_TEST { get; set; }
        public Nullable<int> ORIGINAL_TEST { get; set; }
        public string CHILD_OUT_SPEC { get; set; }
        public string SIGNED { get; set; }
        public Nullable<int> BATCH_ORIGINAL_TEST { get; set; }
        public Nullable<int> TEST_SEQUENCE_NO { get; set; }
        public string X_INSTRUMENT_LIST { get; set; }
    }
}
