//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_LIST_COMP
    {
        public string TEST_LIST { get; set; }
        public string ANALYSIS { get; set; }
        public Nullable<int> ANALYSIS_VERSION { get; set; }
        public string COMPONENT { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string UNITS { get; set; }
        public string ROUND { get; set; }
        public Nullable<int> PLACES { get; set; }
        public Nullable<int> REPLICATE_COUNT { get; set; }
        public Nullable<float> MIN_LIMIT { get; set; }
        public Nullable<float> MAX_LIMIT { get; set; }
        public string REPORTABLE { get; set; }
        public string OPTIONAL { get; set; }
        public string DISPLAYED { get; set; }
        public Nullable<int> ANALYSIS_COUNT { get; set; }
        public string FACTOR_VALUES { get; set; }
        public Nullable<int> RESULT_ORDER_NO { get; set; }
    }
}
