//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEPOINT
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> INTERVAL { get; set; }
        public Nullable<int> TIME_WINDOW { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
        public string CALENDAR_DAYS { get; set; }
        public Nullable<int> NUM_MONTHS { get; set; }
    }
}
