//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS
    {
        public string UNIT_CODE { get; set; }
        public string DISPLAY_STRING { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string EXT_LINK { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public string BASE { get; set; }
        public Nullable<float> OFFSET { get; set; }
        public Nullable<float> FACTOR { get; set; }
        public string FORMULA_SUB { get; set; }
    }
}
