//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DLG_MENUS
    {
        public string USER_DIALOG_TEMP { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_LABEL { get; set; }
        public string MENU_ITEM { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string SUBROUTINE { get; set; }
        public string BITMAP { get; set; }
    }
}
