//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DIALOG_TEMP
    {
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string VALIDATION_SUB { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string TEMPLATE_TABLE { get; set; }
        public string ALLOW_OPEN { get; set; }
        public string ALLOW_CREATE { get; set; }
        public string ALLOW_DELETE { get; set; }
        public string ALLOW_SAVE { get; set; }
    }
}
