//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INSTRUMENT_LOG
    {
        public int COUNTER { get; set; }
        public string USER_NAME { get; set; }
        public string INSTRUMENT { get; set; }
        public string EVENT_TYPE { get; set; }
        public string EXT_LINK { get; set; }
        public string LOG_ENTRY { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> ENTERED_ON { get; set; }
    }
}
