//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARIABLE_CHART
    {
        public string TEMPLATE { get; set; }
        public string X_VALUE_FIELD { get; set; }
        public string Y_VALUE_FIELD { get; set; }
        public string X_VAR_DESC { get; set; }
        public string Y_VAR_DESC { get; set; }
        public string TITLE { get; set; }
        public string TITLE_FONT { get; set; }
        public string SUBGROUP_SIZE { get; set; }
        public string CENTER_LINE { get; set; }
        public string TARGET { get; set; }
        public string SHOW_TARGET { get; set; }
        public string LOWER_CTRL_LIMIT { get; set; }
        public string UPPER_CTRL_LIMIT { get; set; }
        public string LOWER_INNER_LIMIT { get; set; }
        public string UPPER_INNER_LIMIT { get; set; }
        public string SHOW_INNER_LIMITS { get; set; }
        public string LOWER_SPEC_LIMIT { get; set; }
        public string UPPER_SPEC_LIMIT { get; set; }
        public string SHOW_SPEC_LIMITS { get; set; }
        public string LOWER_WARN_LIMIT { get; set; }
        public string UPPER_WARN_LIMIT { get; set; }
        public string SHOW_WARN_LIMITS { get; set; }
        public string POINTS_TO_DISPLAY { get; set; }
        public string Y_AXIS_SCALE { get; set; }
        public string Y_AXIS_CHART_TYPE { get; set; }
        public string Y_AXIS_MIN { get; set; }
        public string Y_AXIS_MAX { get; set; }
        public string Y_AXIS_LABEL_START { get; set; }
        public string Y_AXIS_LABEL_INC { get; set; }
        public string Y_AXIS_TICK_START { get; set; }
        public string Y_AXIS_TICK_INC { get; set; }
        public string SYMBOL_MAX_SIZE { get; set; }
        public string SYMBOL_MIN_SIZE { get; set; }
        public string SYMBOL_V_PERCENT { get; set; }
        public string SYMBOL_H_PERCENT { get; set; }
        public string SYMBOL_WEIGHT { get; set; }
        public string X_LABEL_FONT { get; set; }
        public string X_LABEL_ITALIC { get; set; }
        public string X_LABEL_ANGLE { get; set; }
        public string X_FONT_MAX_SIZE { get; set; }
        public string X_FONT_MIN_SIZE { get; set; }
        public string COMMENT_MAX_SIZE { get; set; }
        public string COMMENT_MIN_SIZE { get; set; }
        public string COMMENT_V_PERCENT { get; set; }
        public string COMMENT_H_PERCENT { get; set; }
        public string COMMENT_WEIGHT { get; set; }
        public string COMMENT_FONT { get; set; }
        public string COLOR_IN_CONTROL { get; set; }
        public string COLOR_OUT_CONTROL { get; set; }
        public string COLOR_RULES_VIO { get; set; }
        public string COLOR_BACKGROUND { get; set; }
        public string SYMBOL_IN_CONTROL { get; set; }
        public string SYMBOL_OUT_CONTROL { get; set; }
        public string SYMBOL_RULES_VIO { get; set; }
        public string USE_PATTERN_RULES { get; set; }
        public string WE_2OF3_ABOVE_UCL { get; set; }
        public string WE_2OF3_BELOW_LCL { get; set; }
        public string WE_4OF5_ABOVE_UCL { get; set; }
        public string WE_4OF5_BELOW_LCL { get; set; }
        public string WE_8_ABOVE_CL { get; set; }
        public string WE_8_BELOW_CL { get; set; }
        public string RUN_RULE_1_DESC { get; set; }
        public string RUN_RULE_1_PATTERN { get; set; }
        public string RUN_RULE_1_TRIGGER { get; set; }
        public string RUN_RULE_2_DESC { get; set; }
        public string RUN_RULE_2_PATTERN { get; set; }
        public string RUN_RULE_2_TRIGGER { get; set; }
        public string RUN_RULE_3_DESC { get; set; }
        public string RUN_RULE_3_PATTERN { get; set; }
        public string RUN_RULE_3_TRIGGER { get; set; }
        public string ZONE_RULE_DESC { get; set; }
        public string ZONE_RULE_INSIDE { get; set; }
        public string ZONE_RULE_TRIGGER { get; set; }
        public string ZONE_RULE_TOTAL { get; set; }
        public string ZONE_RULE_ABOVE { get; set; }
        public string ZONE_RULE_BELOW { get; set; }
        public string LABEL_HEADER { get; set; }
        public string LABEL_FIELD { get; set; }
        public string INITIAL_CHART { get; set; }
        public string WINDOW_LABEL { get; set; }
        public string SPECIFIC_ANALYSIS { get; set; }
        public string CHART_ANALYSIS { get; set; }
        public string CHART_COMPONENT { get; set; }
        public string ZONE_RULE2_DESC { get; set; }
        public string ZONE_RULE2_INSIDE { get; set; }
        public string ZONE_RULE2_TRIGGER { get; set; }
        public string ZONE_RULE2_TOTAL { get; set; }
        public string ZONE_RULE2_ABOVE { get; set; }
        public string ZONE_RULE2_BELOW { get; set; }
        public string WG_MINUS_10X { get; set; }
        public string WG_PLUS_10X { get; set; }
        public string WG_MINUS_22S { get; set; }
        public string WG_PLUS_22S { get; set; }
        public string WG_MINUS_41S { get; set; }
        public string WG_PLUS_41S { get; set; }
        public string WG_R_4S { get; set; }
        public string DISPLAY_ALL_POINTS { get; set; }
        public string LEVEY_JENNINGS { get; set; }
        public string MOVING_AVERAGE { get; set; }
        public string STD_DEV_TYPE { get; set; }
        public Nullable<int> MISSING_DATA_MODE { get; set; }
    }
}
