//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISUAL_WORKFLOW
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string MENU_TITLE { get; set; }
        public string OPEN_ON_LOGIN { get; set; }
        public string GROUP_NAME { get; set; }
        public string PAGE_FILE { get; set; }
        public string LOG_OUT_ON_CLOSE { get; set; }
        public string OPEN_NEW_WINDOW { get; set; }
        public Nullable<int> UPDATE_FREQUENCY { get; set; }
        public string BACKGROUND_IMAGE { get; set; }
        public string CSS_FILE_NAME { get; set; }
        public string CSS_DIR_PATH { get; set; }
        public string HEAD_TAGS { get; set; }
    }
}
