//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_FUNCTION
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string PRIVATE { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string FUNCTION_NAME { get; set; }
        public Nullable<int> NUM_ARGUMENTS { get; set; }
        public string RETURN_VARIABLE { get; set; }
        public string RETURN_TYPE { get; set; }
        public string RETURN_DESCRIPTION { get; set; }
        public string ARG_1_NAME { get; set; }
        public string ARG_1_TYPE { get; set; }
        public string ARG_1_DESCRIPTION { get; set; }
        public string ARG_1_OPTIONAL { get; set; }
        public string ARG_1_DEFAULT { get; set; }
        public string ARG_2_NAME { get; set; }
        public string ARG_2_TYPE { get; set; }
        public string ARG_2_DESCRIPTION { get; set; }
        public string ARG_2_OPTIONAL { get; set; }
        public string ARG_2_DEFAULT { get; set; }
        public string ARG_3_NAME { get; set; }
        public string ARG_3_TYPE { get; set; }
        public string ARG_3_DESCRIPTION { get; set; }
        public string ARG_3_OPTIONAL { get; set; }
        public string ARG_3_DEFAULT { get; set; }
        public string ARG_4_NAME { get; set; }
        public string ARG_4_TYPE { get; set; }
        public string ARG_4_DESCRIPTION { get; set; }
        public string ARG_4_OPTIONAL { get; set; }
        public string ARG_4_DEFAULT { get; set; }
        public string ARG_5_NAME { get; set; }
        public string ARG_5_TYPE { get; set; }
        public string ARG_5_DESCRIPTION { get; set; }
        public string ARG_5_OPTIONAL { get; set; }
        public string ARG_5_DEFAULT { get; set; }
        public string ARG_6_NAME { get; set; }
        public string ARG_6_TYPE { get; set; }
        public string ARG_6_DESCRIPTION { get; set; }
        public string ARG_6_OPTIONAL { get; set; }
        public string ARG_6_DEFAULT { get; set; }
        public string ARG_7_NAME { get; set; }
        public string ARG_7_TYPE { get; set; }
        public string ARG_7_DESCRIPTION { get; set; }
        public string ARG_7_OPTIONAL { get; set; }
        public string ARG_7_DEFAULT { get; set; }
        public string ARG_8_NAME { get; set; }
        public string ARG_8_TYPE { get; set; }
        public string ARG_8_DESCRIPTION { get; set; }
        public string ARG_8_OPTIONAL { get; set; }
        public string ARG_8_DEFAULT { get; set; }
        public string ARG_9_NAME { get; set; }
        public string ARG_9_TYPE { get; set; }
        public string ARG_9_DESCRIPTION { get; set; }
        public string ARG_9_OPTIONAL { get; set; }
        public string ARG_9_DEFAULT { get; set; }
        public string ARG_10_NAME { get; set; }
        public string ARG_10_TYPE { get; set; }
        public string ARG_10_DESCRIPTION { get; set; }
        public string ARG_10_OPTIONAL { get; set; }
        public string ARG_10_DEFAULT { get; set; }
        public string ARG_11_NAME { get; set; }
        public string ARG_11_TYPE { get; set; }
        public string ARG_11_DESCRIPTION { get; set; }
        public string ARG_11_OPTIONAL { get; set; }
        public string ARG_11_DEFAULT { get; set; }
        public string ARG_12_NAME { get; set; }
        public string ARG_12_TYPE { get; set; }
        public string ARG_12_DESCRIPTION { get; set; }
        public string ARG_12_OPTIONAL { get; set; }
        public string ARG_12_DEFAULT { get; set; }
        public string NEW_FUNCTION { get; set; }
        public string MODULE { get; set; }
    }
}
