//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSHEET_OBJECTS
    {
        public int WORKSHEET_OBJ_NO { get; set; }
        public Nullable<int> WORKSHEET_NUMBER { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string OBJECT_NAME { get; set; }
        public Nullable<int> OBJECT_ID { get; set; }
        public Nullable<int> OBJECT_INDEX { get; set; }
        public Nullable<int> SAMPLE_REP { get; set; }
        public Nullable<int> TEST_REP { get; set; }
        public Nullable<int> RESULT_REP { get; set; }
    }
}
