//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_DETAIL
    {
        public string WORKFLOW { get; set; }
        public string ELEMENT_NAME { get; set; }
        public string OPEN_WINDOW { get; set; }
        public string OPEN_WINDOW_PARAM { get; set; }
        public string QUERY_TAG { get; set; }
        public string SUBROUTINE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string FUNCTION_PRIV { get; set; }
        public string ELEMENT_TYPE { get; set; }
        public string LAYOUT_PARAMETERS { get; set; }
        public string MENU_WINDOW { get; set; }
        public string MENU_ITEM { get; set; }
    }
}
