//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSHEET
    {
        public int WORKSHEET_NUMBER { get; set; }
        public string WORKSHEET_NAME { get; set; }
        public string TEMPLATE { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string COMPLETED_BY { get; set; }
        public Nullable<System.DateTime> COMPLETED_ON { get; set; }
        public string REVIEWED_BY { get; set; }
        public Nullable<System.DateTime> REVIEWED_ON { get; set; }
        public Nullable<System.DateTime> PRINTED_ON { get; set; }
        public string PRINTED_BY { get; set; }
        public string CANCELED_BY { get; set; }
        public Nullable<System.DateTime> CANCELED_ON { get; set; }
        public string SECURED { get; set; }
        public string SIGN_ON_SAVE { get; set; }
        public string REMOVED { get; set; }
        public string APPROVED { get; set; }
        public string ARCHIVED { get; set; }
        public string APPROVAL_ROUTING { get; set; }
        public string APPROVAL_GROUP { get; set; }
        public string GROUP_NAME { get; set; }
        public string FILE_LINK_DIR { get; set; }
        public string DATA_MODIFIED { get; set; }
        public string FILE_LINK { get; set; }
    }
}
