//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSHEET_TEMPLATE
    {
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string GROUP_NAME { get; set; }
        public string TITLE { get; set; }
        public string SECURED { get; set; }
        public string SIGN_ON_SAVE { get; set; }
        public string ID_CONFIG { get; set; }
        public string FORM_NAME { get; set; }
        public string COVER_FORM { get; set; }
        public string APPROVAL_ROUTING { get; set; }
        public string APPROVAL_GROUP { get; set; }
        public string EXT_LINK { get; set; }
        public string REVIEW_REQUIRED { get; set; }
    }
}
