//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSHEET_TMP_FLDS
    {
        public string TEMPLATE { get; set; }
        public string FIELD_NAME { get; set; }
        public string ENTRY_MODE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string FIELD_LABEL { get; set; }
        public string FORMULA { get; set; }
        public string ALLOW_USER_ENTRY { get; set; }
        public string DATA_TYPE { get; set; }
        public string DEPENDS_ON { get; set; }
        public string FIELD_TABLE_NAME { get; set; }
        public string TABLE_KEY_FIELD { get; set; }
        public string KEY_FIELD_VALUE { get; set; }
        public string FIELD_REFERENCE { get; set; }
        public string TABLE_VALUE_FIELD { get; set; }
        public Nullable<int> SAMPLE_REPLICATE { get; set; }
        public Nullable<int> TEST_REPLICATE { get; set; }
        public Nullable<int> RESULT_REPLICATE { get; set; }
        public string STORE_IN_DB { get; set; }
    }
}
