//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_ANALYSIS_REAGENT
    {
        public string ANALYSIS { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string ITEM_NAME { get; set; }
        public int VERSION { get; set; }
        public Nullable<float> X_CONSUMPTION_RATE { get; set; }
    }
}
