//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_DAVNASPAR
    {
        public int T { get; set; }
        public float P { get; set; }
        public Nullable<float> СН4 { get; set; }
        public Nullable<float> C2H2 { get; set; }
        public Nullable<float> C2H4 { get; set; }
        public Nullable<float> C3H8 { get; set; }
        public Nullable<float> C3H6 { get; set; }
        public Nullable<float> IC4H10 { get; set; }
        public Nullable<float> NC4H10 { get; set; }
        public Nullable<float> C4H8 { get; set; }
        public Nullable<float> IC5H12 { get; set; }
        public Nullable<float> NC4H12 { get; set; }
        public Nullable<float> C5H10 { get; set; }
    }
}
