//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_FOREIGN_STAFF
    {
        public string PEOPLE_NAME { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string FULL_NAME { get; set; }
        public string BREF_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string X_POSITION_TYPE { get; set; }
        public string PROCESS_UNIT { get; set; }
        public string REMOVED { get; set; }
    }
}
