//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_GLK_ENTRY
    {
        public string X_GLK { get; set; }
        public int X_GLK_ENTRY1 { get; set; }
        public string PROCESS_UNIT { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> ARCHIVE_DOC_ID { get; set; }
        public int ORDER_NUMBER { get; set; }
    }
}
