//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_GSO_MET_CHAR
    {
        public string X_GSO { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string CHAR_NAME { get; set; }
        public string CHAR_VALUE { get; set; }
        public string CHAR_UNITS { get; set; }
        public string X_ERROR_VALUE { get; set; }
        public string X_ERROR_UNITS { get; set; }
        public string X_CHAR_TYPE { get; set; }
    }
}
