//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_GSO
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string X_NTD { get; set; }
        public string REMOVED { get; set; }
        public string X_NAME { get; set; }
        public string X_TYPE { get; set; }
        public string X_INDEX { get; set; }
        public string X_FUNCTION { get; set; }
        public string X_DEVELOPER { get; set; }
        public string X_PRODUCER { get; set; }
        public string X_EXP_LIFE { get; set; }
        public string X_DELIVERY { get; set; }
        public string X_APPROVAL_CERT { get; set; }
        public string X_BATCH { get; set; }
    }
}
