//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INSTR_PM_PLAN
    {
        public string INSTRUMENTS { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string X_MAINTENANCE_PLAN { get; set; }
        public Nullable<int> X_PM_VERSION { get; set; }
        public Nullable<System.DateTime> X_PM_DATE { get; set; }
        public string X_DONE { get; set; }
        public Nullable<System.DateTime> X_DONE_DATE { get; set; }
        public string X_OPERATOR { get; set; }
        public string EXT_LINK { get; set; }
    }
}
