//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INSTR_SI_TYPE_DOC
    {
        public string X_INSTR_SI_TYPES { get; set; }
        public int X_KEY { get; set; }
        public Nullable<System.DateTime> X_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> ARCHIVE_DOC_ID { get; set; }
    }
}
