//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INSTR_TECH_CHAR
    {
        public string INSTRUMENTS { get; set; }
        public string X_KEY { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string X_NAME { get; set; }
        public string X_VALUE { get; set; }
        public string X_UNITS { get; set; }
        public string X_RANGE { get; set; }
        public string X_UNITS_R { get; set; }
        public string X_CLASS { get; set; }
        public string X_UNITS_C { get; set; }
        public string X_MISTAKE { get; set; }
        public string X_UNITS_M { get; set; }
        public string X_RISK { get; set; }
    }
}
