//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INSTR_REG_CARD
    {
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> X_DOC_DATE { get; set; }
        public string X_DOC_NUM { get; set; }
        public string X_CONTROL { get; set; }
        public string X_RESULT_CONTROL { get; set; }
        public string INSTRUM_SAMPLE { get; set; }
        public string INSTRUMENTS { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string X_FINISH { get; set; }
        public string X_PROT_NUM { get; set; }
        public string X_OPERATOR { get; set; }
        public string X_ORGANIZATION { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> ARCHIVE_DOC_ID { get; set; }
        public string X_DOC_NAME { get; set; }
        public Nullable<System.DateTime> ENTERED_DATE { get; set; }
        public string ENTERED_BY { get; set; }
        public string X_MAINTENANCE_PLAN { get; set; }
        public Nullable<int> X_PM_VERSION { get; set; }
    }
}
