//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INVENT_INFLOW
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> PLANNED_DATE { get; set; }
        public string NUM { get; set; }
        public string VENDOR { get; set; }
        public string RECEIVER { get; set; }
        public string EXT_LINK { get; set; }
        public string OCCUPIED_BY { get; set; }
        public Nullable<System.DateTime> OCCUPIED_ON { get; set; }
        public string STATUS { get; set; }
    }
}
