//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INVENT_INFLOW_E
    {
        public int ID { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string TEMPLATE { get; set; }
        public Nullable<int> INVENTORY_ITEM { get; set; }
        public string REAG_DRY_TYPE { get; set; }
        public string X_BATCH { get; set; }
        public string QUALITY { get; set; }
        public Nullable<System.DateTime> X_START_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string UNITS { get; set; }
        public string LOCATION { get; set; }
        public string ALLOCATE_TO { get; set; }
        public string X_DOCUMENT { get; set; }
        public string EXT_LINK { get; set; }
        public string X_SUBSTANCE_FORM { get; set; }
        public Nullable<int> INVENTORY_ENTRY { get; set; }
        public string INGREDIENT { get; set; }
    }
}
