//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_INVENT_MOVE_REQ
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public string DESCRIPTION { get; set; }
        public string REMOVED { get; set; }
        public string REQUEST_NO { get; set; }
        public string LAB { get; set; }
        public string LOCATION { get; set; }
        public string REASON { get; set; }
        public string TRANSFERRED_BY { get; set; }
        public string OCCUPIED_BY { get; set; }
        public Nullable<System.DateTime> OCCUPIED_ON { get; set; }
        public Nullable<int> INVENT_PULL_ID { get; set; }
        public string STATUS { get; set; }
    }
}
