//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_IQC_METROLOG_CHAR
    {
        public string ANALYSIS { get; set; }
        public int VERSION { get; set; }
        public string ENTRY_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string X_RULE { get; set; }
        public Nullable<float> X_MIN { get; set; }
        public Nullable<float> X_MAX { get; set; }
        public Nullable<float> X_REPROD_NORM { get; set; }
        public Nullable<float> X_SKO_REPROD { get; set; }
        public string X_REPROD_COMP { get; set; }
        public string X_REPROD_UNITS { get; set; }
        public Nullable<float> X_REPEAT_NORM { get; set; }
        public Nullable<float> X_SKO_REPEAT { get; set; }
        public string X_REPEAT_COMP { get; set; }
        public string X_REPEAT_UNITS { get; set; }
        public Nullable<float> X_INACCURACY { get; set; }
        public string X_INACCURACY_UNITS { get; set; }
        public Nullable<float> X_CERT_VALUE { get; set; }
        public string X_CERT_CHAR_DESC { get; set; }
        public Nullable<float> X_CERT_ERROR { get; set; }
        public string X_COMPONENT { get; set; }
    }
}
