//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_KSM_ENTRY
    {
        public int X_KSM { get; set; }
        public int X_KSM_ENTRY1 { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string Product { get; set; }
        public string GRADE { get; set; }
    }
}
