//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_LAB_INFO_DEP
    {
        public string X_LAB_INFO { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string DEP_NAME { get; set; }
        public string ADDRESS { get; set; }
    }
}
