//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_LAB_INFO
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string LAB_NAME { get; set; }
        public string LAB_ADDRESS { get; set; }
        public string DIRECTOR { get; set; }
        public string ATTESTAT_NUMBER { get; set; }
        public string TR_TS { get; set; }
    }
}
