//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_LOGIN_USER_LOG
    {
        public long num_login { get; set; }
        public string comp_name { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> date_login { get; set; }
    }
}
