//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_MENUS_SUB_ENTRY
    {
        public string X_MENUS { get; set; }
        public string ENTRY { get; set; }
        public string SUB_MENU_NAME { get; set; }
        public string SUB_MENU_TITLE { get; set; }
        public string SUBROUTINE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string BITMAP { get; set; }
        public string ACCESS_PRIV { get; set; }
        public string GROUP_NAME { get; set; }
    }
}
