//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_PASSPORT_TEMPLATES
    {
        public string Product { get; set; }
        public int VERSION { get; set; }
        public string TMPL_NAME { get; set; }
        public string GRADE { get; set; }
        public string TEMPLATE_TYPE { get; set; }
        public string TEMPLATE_PATH { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
