//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_PERIOD_QUALITY_ANA
    {
        public string X_PERIOD_QUALITY { get; set; }
        public int VERSION { get; set; }
        public string ANALYSIS { get; set; }
        public string DESCRIPTION { get; set; }
        public string X_NTD { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string STATE { get; set; }
        public Nullable<int> COUNT_AFTER_DURATION { get; set; }
        public Nullable<int> COUNT_AFTER_REJECT { get; set; }
        public Nullable<System.DateTime> ENDING_USEFUL_LIFE { get; set; }
        public Nullable<System.DateTime> LAST_COEFF_DEFIN { get; set; }
        public string CAPABILITY_PROLONG { get; set; }
        public Nullable<int> COUNT_FOR_RESULT { get; set; }
        public Nullable<int> TEST_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
