//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Product_PROC_UNIT
    {
        public string Product { get; set; }
        public int VERSION { get; set; }
        public string X_PROCESS_UNIT { get; set; }
        public string X_PROD_TYPE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    }
}
