//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_PROD_CERTS
    {
        public string Product { get; set; }
        public int VERSION { get; set; }
        public string DOC_ID { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string GRADE { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOC_NUMBER { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<int> ARCHIVE_DOC_ID { get; set; }
    }
}
