//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_ROOMS
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string BUILDING { get; set; }
        public string PHONE { get; set; }
        public string X_DEPART { get; set; }
        public string X_GROUP { get; set; }
        public string X_ACCREDITATION { get; set; }
        public string X_USE { get; set; }
        public string X_SPEC { get; set; }
        public string X_AREA { get; set; }
        public string X_TEMP { get; set; }
        public string X_HUM { get; set; }
        public string X_LIGHT { get; set; }
        public string X_GAS { get; set; }
        public string X_NOICE { get; set; }
        public string X_HIND { get; set; }
        public string X_INVENT { get; set; }
        public string X_AGREE { get; set; }
        public string X_NUM { get; set; }
        public Nullable<System.DateTime> X_DATE { get; set; }
        public string X_SAVE { get; set; }
        public string X_NOTES { get; set; }
        public Nullable<System.DateTime> X_STARTUP { get; set; }
        public Nullable<System.DateTime> X_LAST_REPAIRED { get; set; }
        public string X_NEED_REPAIR { get; set; }
        public string X_LAB { get; set; }
    }
}
