//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_UNIT_RPT_ANALYSIS
    {
        public string X_UNIT_RPT_INFO { get; set; }
        public int X_UNIT_RPT_ROW { get; set; }
        public int X_UNIT_RPT_ANALYSIS1 { get; set; }
        public string Product { get; set; }
        public int Product_VERSION { get; set; }
        public int ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
        public string ANALYSIS { get; set; }
        public Nullable<int> ANALYSIS_VERSION { get; set; }
    }
}
