//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_UNIT_RPT_ROW
    {
        public string X_UNIT_RPT_INFO { get; set; }
        public int X_UNIT_RPT_ROW1 { get; set; }
        public int ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string Product { get; set; }
        public Nullable<int> Product_VERSION { get; set; }
        public string RPT_Product { get; set; }
        public string SAMPLING_POINT { get; set; }
        public string RPT_SAMPLING_POINT { get; set; }
        public string GRADE { get; set; }
        public string PROCESS_UNIT { get; set; }
    }
}
