//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_USER_TRAIN_CHILD
    {
        public string X_USER_CONFIG { get; set; }
        public string TRAININGS { get; set; }
        public string DESCRIPTION { get; set; }
        public string X_USER_TRAIN_STATUS { get; set; }
        public Nullable<System.DateTime> X_PLANNED_DATE { get; set; }
        public string X_ACCREDITATION { get; set; }
        public string EXT_LINK { get; set; }
        public int ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> X_COMPLETED_DATE { get; set; }
        public string PSWD { get; set; }
        public string X_TRAININGS { get; set; }
    }
}
