//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_USER_RSRCHS_CHILD
    {
        public string X_USER_CONFIG { get; set; }
        public int X_USER_RSRCHS_CHILD1 { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string CHANGED_BY { get; set; }
        public System.DateTime CHANGED_ON { get; set; }
        public string RESEARCH { get; set; }
    }
}
