//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_USER_CONFIG
    {
        public string NAME { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string X_BIRTHDAY { get; set; }
        public string X_PROV_TYPE { get; set; }
        public string X_EDUCATION { get; set; }
        public string X_PROTOKOL { get; set; }
        public string X_EXPERIENCE { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public string X_ACCREDITATION { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public string X_FULL_NAME { get; set; }
        public string X_SNILS { get; set; }
        public string X_CONTRACT_TYPE { get; set; }
        public string X_CONTRACT_NUMBER { get; set; }
        public Nullable<System.DateTime> X_CONTRACT_DATE { get; set; }
        public string X_WORK_PLACE_TYPE { get; set; }
        public string X_BIRTHPLACE { get; set; }
        public string X_LAB { get; set; }
        public string X_VACATION { get; set; }
    }
}
