//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_USER_EDU_CHILD
    {
        public string X_USER_CONFIG { get; set; }
        public int X_USER_EDU_CHILD1 { get; set; }
        public string EDUCATION { get; set; }
        public string X_UNIVER { get; set; }
        public Nullable<System.DateTime> X_DATE { get; set; }
        public string X_SPECIAL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public string X_DIPLOM_DETAILS { get; set; }
    }
}
