//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_VKK_PROJ_COMP
    {
        public string PROJECT { get; set; }
        public string COMPONENT { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public string EXT_LINK { get; set; }
        public Nullable<float> X_CERT_VALUE { get; set; }
        public Nullable<float> X_NEW_SKO_REPEAT { get; set; }
        public Nullable<float> X_NEW_SKO_REPROD { get; set; }
        public Nullable<float> X_NEW_INACCURACY { get; set; }
        public string X_ROUND_REPEAT { get; set; }
        public string X_ROUND_REPROD { get; set; }
        public string X_ROUND_INAC { get; set; }
        public Nullable<float> X_SIGMA_R_BOL { get; set; }
        public string X_DELTA_L { get; set; }
        public string X_DELTA_SL { get; set; }
        public string X_ROUND_RESULT { get; set; }
        public Nullable<float> X_N_COUNT { get; set; }
        public Nullable<float> X_REPROD_NORM { get; set; }
        public Nullable<float> X_SKO_REPROD { get; set; }
        public string X_REPROD_UNITS { get; set; }
        public string X_INACCURACY_UNITS { get; set; }
        public Nullable<float> X_REPEAT_NORM { get; set; }
        public Nullable<float> X_SKO_REPEAT { get; set; }
        public string X_REPEAT_UNITS { get; set; }
        public Nullable<float> X_INACCURACY { get; set; }
        public string X_DELTA_L_REP { get; set; }
    }
}
