//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_VKK_REPORT
    {
        public string PROJECT { get; set; }
        public int SAMPLE_NUMBER { get; set; }
        public Nullable<float> INACCURACY_CONTROL { get; set; }
        public Nullable<float> PRECISION_CONTROL { get; set; }
        public Nullable<float> REPEAT_CONTROL { get; set; }
        public string RULES_VIOLATIONS { get; set; }
        public string INACCURACY_VIOLATIONS { get; set; }
        public string PRECISION_VIOLATIONS { get; set; }
        public string REPEAT_VIOLATIONS { get; set; }
        public Nullable<float> X1 { get; set; }
        public Nullable<float> X2 { get; set; }
        public Nullable<float> X3 { get; set; }
        public Nullable<float> MEAN_VALUE { get; set; }
        public Nullable<float> VALUE_WITH_ADDITIVE { get; set; }
        public Nullable<float> ADDITIVE_VALUE { get; set; }
        public Nullable<float> DILUTION_VALUE { get; set; }
        public Nullable<float> VALUE_WITH_ADDITIVE_DILUTION { get; set; }
        public Nullable<float> VALUE_WITH_DILUTION { get; set; }
        public Nullable<float> ACCESS_VALUE { get; set; }
        public Nullable<float> VALUE_CONTROL_METH { get; set; }
        public string IN_CONTROL_RANGE { get; set; }
        public Nullable<float> MEAN_VALUE_2 { get; set; }
        public string CHECK_ADD_DIL { get; set; }
    }
}
