//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_VKK_ND
    {
        public string PROJECT { get; set; }
        public int SAMPLE_NUMBER { get; set; }
        public Nullable<float> X_CERT_VALUE { get; set; }
        public Nullable<float> X1 { get; set; }
        public Nullable<float> X2 { get; set; }
        public Nullable<float> XMEAN { get; set; }
        public Nullable<float> DISPERS { get; set; }
        public Nullable<float> XIXN { get; set; }
        public string OK { get; set; }
        public string REASON { get; set; }
    }
}
