//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimsP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZIPCODES
    {
        public int ENTRY_CODE { get; set; }
        public string ZIP_CODE { get; set; }
        public string ZIP_CODE_TYPE { get; set; }
        public string CITY { get; set; }
        public string CITY_TYPE { get; set; }
        public string COUNTY { get; set; }
        public string COUNTY_FIPS { get; set; }
        public string STATE { get; set; }
        public string STATE_CODE { get; set; }
        public string STATE_FIPS { get; set; }
        public string MSA { get; set; }
        public string AREA_CODE { get; set; }
        public string TIME_ZONE { get; set; }
        public Nullable<int> GMT_OFFSET { get; set; }
        public string DST { get; set; }
        public Nullable<float> LATITUDE { get; set; }
        public Nullable<float> LONGITUDE { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string GROUP_NAME { get; set; }
        public string USER_ADDED { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public string CHANGED_BY { get; set; }
        public string REMOVED { get; set; }
    }
}
